-- Page handler

-- Commands
-- the section is not intended for end-user editing
dofile(LockOn_Options.script_path.."command_defs.lua")

KeyCommands = {	{command = Keys.PlaneModeBVR},
				{command = Keys.PlaneModeVS},
				{command = Keys.PlaneModeBore},
				{command = Keys.PlaneModeGround},
				{command = Keys.PlaneModeFI0},
				{command = Keys.ChangeGunRateOfFire},
				{command = Keys.ChangeRippleQuantity},
				{command = Keys.ChangeRippleInterval},
				{command = Keys.ChangeRippleIntervalDown},
				{command = Keys.ChangeReleaseMode},
				{command = Keys.SwitchMasterArm},
				{command = Keys.PlaneSalvoOnOff},
				{command = Keys.PlaneChangeWeapon},
				{command = Keys.PlaneDesignate_CageOn , arg = 601, arg_increment = 1.0 ,direct_set = true, arg_lim = {0.0, 1.0}},
				{command = Keys.PlaneDesignate_CageOff, arg = 601, arg_increment = 0   ,direct_set = true, arg_lim = {0.0, 1.0}},
				{command = Keys.PlaneDesignate_CageOn_vertical},
				{command = Keys.PlaneDesignate_CageOn_horizontal},
				{command = Keys.PlaneCancelWeaponsDelivery},
				{command = Keys.Plane_CancelWeaponsDelivery_up},
				{command = Keys.Plane_LockOn_start , arg = 607, arg_increment = 1.0, arg_lim = {0.0, 1.0}},
				{command = Keys.Plane_LockOn_finish, arg = 607, arg_increment =-1.0, arg_lim = {0.0, 1.0}},				
				{command = Keys.Plane_AutomaticTracking_Gunsight_switch},
				{command = Keys.Plane_AutomaticTurn},
				{command = Keys.Plane_AutomaticTurn_up},
				{command = Keys.Plane_GroundMovingTarget},
				{command = Keys.Plane_GroundMovingTarget_up},
				{command = Keys.Plane_AirborneTarget},
				{command = Keys.Plane_AirborneTarget_up},
				{command = Keys.Plane_HeadOnAspect},
				{command = Keys.Plane_HeadOnAspect_up},
				{command = Keys.Plane_ChangeDeliveryMode_right},
				{command = Keys.Plane_ChangeDeliveryMode_left},
				{command = Keys.Plane_WeaponMode_Manual_Auto},
				{command = Keys.PlaneLaunchPermissionOverride},
				{command = Keys.Plane_WeaponMode_switch},
				{command = Keys.Plane_AmmoTypeSelect},
				{command = Keys.Plane_FireRate},
				
				{command = Keys.WeaponsControlSystem},
				{command = Keys.WeaponsControlSystemCover},
				{command = Keys.SelectWeapon_Internal, arg = 612,arg_increment = 1,direct_set = true, arg_lim = {-1,1}},
				{command = Keys.SelectWeapon_External, arg = 612,arg_increment =-1,direct_set = true, arg_lim = {-1,1}},
				{command = Keys.SelectWeapon_ALL, arg = 611,arg_increment =-1,direct_set = true, arg_lim = {-1,1}},
				{command = Keys.SelectWeapon_AA, arg = 611,arg_increment  = 1,direct_set = true, arg_lim = {-1,1}},
                {command = Keys.SelectWeapon_hor_up, arg = 612,arg_increment = 0,direct_set = true, arg_lim = {-1,1}},
                {command = Keys.SelectWeapon_vert_up, arg = 611,arg_increment = 0,direct_set = true, arg_lim = {-1,1}},
                {command = Keys.iCommandPlaneJettisonWeapons},
                {command = Keys.iCommandPlaneJettisonFuelTanks},
                {command = Keys.iCommandPlane_JettisonMode_explosion},
				{command = Keys.iCommandPlaneJettisonFuelTanksUp},
				{command = Keys.iCommandPlaneJettisonWeaponsUp},
				{command = Keys.iCommand_WEAP_INTERF_MasterSimulate},
                {command = Keys.iCommandPlane_LaserCode_Next},
			    {command = Keys.iCommandPlane_LaserCode_Previous},
			    {command = Keys.iCommandWeaponsBallisticSelectorRight},
			    {command = Keys.iCommandWeaponsBallisticSelectorLeft},
			    {command = Keys.PlaneModeCannon}, 
   			  }
