return
{
-- [color=0xffffffff]
-- [color=0x6090c0ff]
-- •
--------------------------------------------------------------
-- PAGE1
--------------------------------------------------------------
{
{'header1', [[[color=0xffffffff]GAME MODES]]},
{'text', [[
DCS: UH-1H Huey offers two “game mode” options: Game Flight Mode and Game Avionics Mode, which together turn this realistic simulation into an easy to play flying action game. Game modes can be selected in the OPTIONS – GAMEPLAY tab from the main menu using either the individual option bullets or the PRESETS buttons at the bottom of the menu.
]]},
{'picture', [[image manual page1.png]]}
},
--------------------------------------------------------------
-- PAGE2
--------------------------------------------------------------
{
{'text', [[
Game Flight mode makes the helicopter much easier to fly. This mode is especially recommended for beginners and users without a joystick. Game Avionics mode adds arcade-type indication to the screen and simplifies target detection, weapons selection and firing.
]]},
{'text', [[
[b]Game Avionics mode uses a separate input profile from Simulation mode. See the OPTIONS – CONTROLS – “UH-1H Game” input profile for a full list of input commands when using Game Avionics mode.[/b]
]]},
{'picture', [[image manual page2.png]]}
},
--------------------------------------------------------------
-- PAGE3
--------------------------------------------------------------
{
{'text', [[Game Avionics mode includes the following special indicators:]]},
{'picture', [[image manual page3.png]]}
},
--------------------------------------------------------------
-- PAGE4
--------------------------------------------------------------
{
{'text', [[
[b]NOSE POSITION.[/b] The line of sight of the aircraft (direction of the nose).
[b]AIMING RETICLE.[/b] The aiming point for the selected weapon.
[b]RADAR.[/b] The 360 degree radar screen displays all of the units around your aircraft. You can cycle the scale of the display between 1, 5, 10, 20 or 50 km. The blue and white circle indicates your landing airfield.
[b]ENEMY UNITS (RED).[/b] Units belonging to the enemy coalition.
[b]FRIENDLY UNITS (GREEN).[/b] Units belonging to the friendly coalition.
[b]LIFEBAR.[/b] The lifebar of the helicopter indicating the amount of damage taken.
[b]SELECTED WEAPON.[/b] Indicates the currently selected weapon and amount of ammunition remaining.
When playing in Game Mode, you can jump into the cockpit view by pressing [color=0x6090c0ff]F1[/color]. To return to the external Chase view, press [color=0x6090c0ff]F4[/color].
]]},
},
--------------------------------------------------------------
-- PAGE5
--------------------------------------------------------------
{
{'picture', [[image manual page5_1.png]]},
{'picture', [[image manual page5_2.png]]}
},
--------------------------------------------------------------
-- PAGE6
--------------------------------------------------------------
{
{'header2', [[Common Game Avionics Mode Key Commands]]},
{'text', [[
Below is a list of essential commands used when flying the UH-1H in Game Avionics Mode:
]]},
{'picture', [[image manual page6.png]]}
},
--------------------------------------------------------------
-- PAGE7
--------------------------------------------------------------
{
{'header1', [[[color=0xffffffff]HELICOPTER CONTROLS]]},
{'text', [[
Primary helicopter flight controls include the cyclic control stick, collective control lever, and anti-torque pedals. The cyclic is the equivalent of a joystick and is used to raise or lower the nose and roll the helicopter left and right for turns. The collective is positioned by the pilot’s side and is moved up and down to control the amount of lift being generated by the main rotor, essentially used to gain or lose altitude (climb/descend). The pedals are used to turn (yaw) the nose left or right along the horizon with minimal roll and can be used to rotate the helicopter when hovering.
When flying from the cockpit, you can toggle the Controls Indicator display by pressing [color=0x6090c0ff]RCTRL + ENTER[/color] to see a visual reference of the positions of your flight controls.
]]}
},
--------------------------------------------------------------
-- PAGE8
--------------------------------------------------------------
{
{'picture', [[image manual page8.png]]}
},

--------------------------------------------------------------
-- PAGE9
--------------------------------------------------------------
{
{'text', [[
You can control the helicopter by either joystick or keyboard. However a joystick with a rudder axis or separate rudder pedals is recommended. We have provided a sample control configuration for both joystick and keyboard below.
]]},
{'picture', [[image manual page9.png]]}
},
--------------------------------------------------------------
-- PAGE10
--------------------------------------------------------------
{
{'picture', [[image manual page10.png]]},
{'text', [[
Helicopters are generally unstable and require constant and coordinated control input. A change in one of the controls will always require corresponding adjustments in the other controls. If you find the Simulation flight model too difficult or if you lack sufficient flight control hardware to fly it effectively, Game Flight Mode will offer the same flight physics, but with increased stability and controllability.
Pressing Climb [color=0x6090c0ff]Num+[/color] or Descend [color=0x6090c0ff]Num-[/color] on the keyboard will increase and decrease the amount of lift being generated by the main rotor, resulting in a gain or loss of altitude.
Pressing Nose Down [color=0x6090c0ff]↑[/color] on the keyboard or pushing the joystick forward will lower the helicopter’s nose and begin forward acceleration. Pressing Nose Up [color=0x6090c0ff]↓[/color] on the keyboard or pulling the joystick back will raise the nose and slow the helicopter down or make it fly backwards from a hover.
]]}
},
--------------------------------------------------------------
-- PAGE11
--------------------------------------------------------------
{
{'text', [[
Pressing Roll Right [color=0x6090c0ff]→[/color] or Roll Left [color=0x6090c0ff]←[/color] on the keyboard or pushing the joystick to the sides will cause the helicopter to roll and begin a turn in the direction of roll. The greater the roll angle, the faster the rate of turn. To stop the turn and return to level flight, roll the helicopter in the opposite direction of the turn until the horizon is level again.
Pressing Nose Left [color=0x6090c0ff]Z[/color] or Nose Right [color=0x6090c0ff]X[/color] on the keyboard will cause the helicopter to turn its nose to the left or right (yaw) with minimal roll, similar to turning the wheel in a car. The amount of yaw available is limited and depends largely on airspeed. When flying fast, the oncoming airflow makes it difficult for the helicopter to yaw against it. Yaw control is primarily used to control the helicopter’s direction in a hover and maintain straight and level flight when flying at higher speeds.
]]}
},
--------------------------------------------------------------
-- PAGE12
--------------------------------------------------------------
{
{'header1', [[[color=0xffffffff]INSTRUMENT PANEL]]},
{'picture', [[image manual page12.png]]}
},
--------------------------------------------------------------
-- PAGE13
--------------------------------------------------------------
{
{'text', [[
1. Glareshield
2. Secondary lights
3. Master caution
4. RPM warning light
5. Fire detector test switch
6. Fire warning indicator light
7. Fuel gage test switch
8. Airspeed indicator
9. Attitude indicator
10. Dual tachometer
11. Altimeter indicator (AAU-31/A)
12. Attitude indicator
13. Radio compass indicator
14. Altimeter indicator (AAU-32/A)
15. Vertical velocity indicator
16. Compass correction card holder
17. Fuel pressure indicator
18. IFF code hold switch
19. IFF code hold light
20. Transmission oil pressure indicator
21. Main generator loadmeter
22. Standby generator loadmeter
23. Engine oil pressure indicator
24. AC voltmeter
25. Compass slaving switch
26. DC voltmeter
27. Transmission oil temperature indicator
28. Engine oil temperature
29. Fuel quantity indicator
30. Exhaust gas temperature indicator
31. Gas producer tachometer indicator
32. Turn and slip indicator
33. Torquemeter indicator
34. Marker beacon volume control
35. Marker beacon Sensing Switch
]]}
},
--------------------------------------------------------------
-- PAGE14
--------------------------------------------------------------
{
{'text', [[
36. Cargo release armed light
37. Clock
38. Marker beacon light
39. Omni indicator
40. Magnetic compass
41. Radio compass indicator
42. Vertical velocity indicator
]]},
{'header1', [[[color=0xffffffff]STARTING THE HELICOPTER]]},
{'text', [[
The automatic start-up procedure can be activated by pressing [color=0x6090c0ff]LWIN + HOME[/color]. 
Automatic shut down can be activated by pressing [color=0x6090c0ff]LWIN + END[/color].

1. Overhead switches and circuit breakers:
	• AC POWER switches: 
		+ PHASE switch–AC. [color=0x6090c0ff]LSHIFT +R[/color] 
		+ INVTR switch–OFF. [color=0x6090c0ff]LSHIFT + I[/color]
	• DC POWER switches: 
		+ MAIN GEN switch–ON and cover down. [color=0x6090c0ff]LSHIFT +Q[/color] 
		+ VM selector–ESS BUS. [color=0x6090c0ff]LSHIFT + H[/color] 
		+ STARTER GEN switch–START. [color=0x6090c0ff]LSHIFT + X[/color] 
		+ BAT switch–ON. [color=0x6090c0ff]LSHIFT + P[/color]
]]},
},
--------------------------------------------------------------
-- PAGE15
--------------------------------------------------------------
{
{'picture', [[image manual page15.png]]},
{'text', [[
2 Center pedestal switches: 
	• GOV switch–AUTO. [color=0x6090c0ff]G[/color]
	• FUEL switches:
		+ MAIN FUEL switch–ON. [color=0x6090c0ff]F[/color]
		+ All other switches–OFF.
]]}
},
--------------------------------------------------------------
-- PAGE16
--------------------------------------------------------------
{
{'picture', [[image manual page16_1.png]]},
{'text', [[
	• HYD CONT switch–ON. [color=0x6090c0ff]LALT + I[/color]
	• FORCE TRIM switch–ON. [color=0x6090c0ff]LALT + U[/color]
	• CHIP DET switch–BOTH. [color=0x6090c0ff]LALT + V[/color]
]]},
{'picture', [[image manual page16_2.png]]},
{'text', [[
3 Throttle – set to IDLE for engine start: 
	• Press and hold [color=0x6090c0ff]PgUp[/color] to increase throttle from FULL CLOSE to FULL OPEN. 
	• Press and hold [color=0x6090c0ff]PgDn[/color] to decrease throttle from FULL OPEN to the IDLE STOP position.
]]}
},
--------------------------------------------------------------
-- PAGE17
--------------------------------------------------------------
{
{'picture', [[image manual page17.png]]},
{'text', [[
4 Engine:
	• Start switch - press and hold; note start time. [color=0x6090c0ff]HOME[/color]
	• Main rotor – Check that the main rotor is turning as Gas Producer speed reaches 15%. If the rotor is not turning, abort the start.
	• Start switch – Release at 40% Gas Producer speed or after 40 seconds, whichever occurs first. 
]]}
},
--------------------------------------------------------------
-- PAGE18
--------------------------------------------------------------
{
{'text', [[

	• Throttle — Slowly increase to set normal RPM. [color=0x6090c0ff]PgUp[/color]
	• INVTR switch − MAIN ON. [color=0x6090c0ff]LSHIFT + U[/color]
]]},
{'header1', [[[color=0xffffffff]FLYING THE HELICOPTER]]},
{'header2', [[Takeoff]]},
{'text', [[
Because the UH-1 undercarriage uses skids instead of wheels, takeoffs are normally performed using a vertical “pickup” from the ground into the air, followed by forward acceleration and climb to transition into forward flight. Performing a vertical takeoff can be challenging at first, especially when playing in Simulation mode, as it requires coordinated, continuous, and smooth inputs of the cyclic, pedals, and collective.
]]},
{'picture', [[image manual page18.png]]},
{'text', [[
To begin the takeoff, gently raise the collective ([color=0x6090c0ff]Num+[/color]). The cyclic will generally need to be pulled back and to the left (about 20% in each direction) to maintain a stable attitude. The left pedal will also need to pressed in about 30% of the way to prevent the helicopter from yawing to the right. Continue to [b]slowly[/b] raise the collective and use careful stick and pedal inputs to maintain the position of the nose and prevent any sliding along the ground. When done correctly, the helicopter will slowly lift off the ground and into a stable, low altitude hover with minimum changes in position and direction.
]]}
},
--------------------------------------------------------------
-- PAGE19
--------------------------------------------------------------
{
{'text', [[
After lifting off to an altitude of a few feet off the ground, lower the nose slightly by releasing some back pressure on the stick to begin accelerating forward. Slightly increase collective as you move the stick forward to prevent a loss of altitude as the nose lowers.
Here is an example of the approximate positions of the flight controls during a vertical takeoff, hover, and vertical landing:
]]},
{'picture', [[image manual page19.png]]},
{'text', [[
To accelerate forward, keep the helicopter's nose slightly down. To slow down, raise the nose up (pull the stick back). If you keep the helicopter's nose raised after it stops moving forward, it will begin to fly backwards. Use the collective ([color=0x6090c0ff]Num+[/color] / [color=0x6090c0ff]Num-[/color]) to increase/decrease the amount of lifting power being generated by the rotor and control altitude as the nose is raised or lowered.
]]}
},
--------------------------------------------------------------
-- PAGE20
--------------------------------------------------------------
{
{'picture', [[image manual page20_1.png]]},
{'text', [[
As your airspeed builds, the nose will tend to rise up. Anticipate this and compensate for it by pushing the cyclic forward. As you transition from a hover into forward flight above 30 knots, the cyclic will move from a back-and-left position to an approximate forward-and-center position. Similarly, as airspeed builds the amount of pedal input required will be reduced. At fast airspeeds, such as above 80 knots, the helicopter will tend to roll left, so increasing cyclic to the right will also be necessary to maintain level flight.
]]},
{'header2', [[Turning]]},
{'picture', [[image manual page20_2.png]]}
},
--------------------------------------------------------------
-- PAGE21
--------------------------------------------------------------
{
{'text', [[
If the helicopter is in forward flight, turn by rolling in the direction of the turn ([color=0x6090c0ff]←[/color] / [color=0x6090c0ff]→[/color] or cyclic to the left/right). Turn rate can be increased with some additional pedal input into the turn and a slight pull of the cyclic.
In a hover or at very low airspeeds, the helicopter can be turned using the pedals ( [color=0x6090c0ff]Z[/color] / [color=0x6090c0ff]X[/color] ) to rotate the nose along the horizon.
]]},
{'header2', [[Hover]]},
{'text', [[
One of the essential skills of helicopter control is hovering. Like takeoff, hovering requires careful, smooth, and coordinated control input.
To enter a hover from forward flight, you will need to first reduce your airspeed without losing altitude. To do so, simultaneously raise the nose up about 20 degrees by pulling the cyclic back and decrease collective to prevent altitude gain. Keep a careful eye on the vertical velocity and airspeed indicators. As your speed bleeds off to below 50 knots, be ready to increase collective and lower the nose to attain a near hovering position at a low airspeed. Timely increase of the collective is critical as your airspeed bleeds off to below 30 knots in order to avoid entering a vortex ring state (VRS), where the helicopters gets “sucked” into its own downwash and begins to plummet toward the ground.
Keep in mind that increasing and decreasing collective will always require corresponding adjustments in cyclic and pedals in order to maintain stable flight. In general, increasing collective will tend to also pull the nose right, requiring additional left pedal input to compensate. Conversely, decreasing collective will tend to pull the nose to the left, requiring increased right pedal input to compensate.
]]}
},
--------------------------------------------------------------
-- PAGE22
--------------------------------------------------------------
{
{'header2', [[Landing]]},
{'text', [[
To perform a landing, begin a stable descent toward the landing point. Keep your airspeed around 80 knots and rate of descent under control by using the collective and cyclic controls. Try to enter a hover over the landing point and then carefully reduce collective to lower the helicopter to the ground.
A run-on landing is also possible, where the helicopter lands with some forward speed and skids to a stop on the ground.
]]},
{'header2', [[Trim]]},
{'text', [[
The helicopter is rarely flown with either the cyclic or pedals in the neutral position. In the real helicopter, the pilot is able to press a trim button on the cyclic to set the controls in their current position. However, because most PC controllers don’t have a similar trim capability, a special trim function is available in the simulation. To trim the controls in their current position, press and release the Trimmer button [color=0x6090c0ff]T[/color], then quickly return the stick and pedals to the neutral position. You can cancel trim at any time by pressing [color=0x6090c0ff]LCTRL + T[/color].
]]},
{'picture', [[image manual page22.png]]}
},
--------------------------------------------------------------
-- PAGE23
--------------------------------------------------------------
{
{'header1', [[[color=0xffffffff]WEAPONS EMPLOYMENT]]},
{'text', [[
The DCS UH-1H is equipped with the M23 armament system, M21 armament sub-system, and M93 armament sub-system. The M23 armament system includes two swiveling M60D machine guns operated by the door gunners. The M21 armament sub-system includes the M134 miniguns and rocket launchers attached to the external weapon stations of the helicopter. The M93 armament sub-system includes two M134 miniguns on a similar swiveling mount as the M60D guns of the M23 armament system, but providing much more firepower.
]]},
{'header2', [[Weapon Systems and Autopilot Status Indicator]]},
{'text', [[
DCS: UH-1H includes a special weapon systems and autopilot status indicator on the right side of the screen to help quickly assess the status of your weapon systems and autopilot modes, as well as get quick hints of the keyboard commands required to operate them. The display can be turned on and off by pressing [color=0x6090c0ff]LCTRL + LSHIFT + H[/coior].
]]},
{'picture', [[image manual page23.png]]}
},
--------------------------------------------------------------
-- PAGE24
--------------------------------------------------------------
{
{'text', [[
[b]AVAILABLE WEAPONS.[/b] Displays the weapons currently loaded on the helicopter.

[b]MASTER ARM SETTING.[/b] Displays the position of the Master Arm switch (OFF/SAFE/ARMED) and the keyboard commands used to change it. Needs to be set to ARMED to fire weapons.

[b]ACTIVE WEAPON.[/b] Displays the currently selected (active) weapon system, rounds remaining, and the keyboard commands used to change weapon systems.

[b]FIRE SETTINGS.[/b] Displays the fire settings for the selected weapon and the keyboard command used to change them. When the M134 gun system is active, the fire setting can be set between the left, right, and both guns, each on one side of the helicopter. When rocket launchers are active, the fire setting indicates the maximum number of pairs of rockets to be released while the weapons trigger is depressed.

[b]AUTOPILOT STATUS.[/b] Displays the status of the autopilot (ON/OFF) and the keyboard command used to change it.

[b]AUTOPILOT MODE.[/b] Displays the currently selected autopilot mode (ATTITUDE HOLD/LEVEL FLIGHT/ORBIT).

[b]ATTITUDE HOLD HINT.[/b] Displays the keyboard commands used to selected ATTITUDE HOLD autopilot mode.
[b]LEVEL FLIGHT HINT.[/b] Displays the keyboard commands used to selected LEVEL FLIGHT autopilot mode.
[b]ORBIT HINT.[/b] Displays the keyboard commands used to selected ORBIT autopilot mode.
]]}
},
--------------------------------------------------------------
-- PAGE25
--------------------------------------------------------------
{
{'header2', [[M23 and M93 Armament Systems]]},
{'text', [[
To use the side door guns of the M23 or M93 armament systems, simply press [color=0x6090c0ff]3[/color] or [color=0x6090c0ff]4[/color] to take the position of the desired side door gunner.
]]},
{'picture', [[image manual page25.png]]},
{'text', [[
To aim the gun, press [color=0x6090c0ff]LALT + C[/color] to enable mouse pan control mode. Once turned on, you can aim the gun using the mouse and fire by pressing [color=0x6090c0ff]SPACE[/color]. You can use the mouse wheel or the [color=0x6090c0ff]Num*[/color] and [color=0x6090c0ff]Num/[/color] keys to zoom the view in and out, as well as adjust the 3D position of the view by holding the mouse wheel down while moving the mouse.
When you switch to a gunner’s position, the autopilot turns on automatically to fly the helicopter according to the set autopilot mode. Autopilot can be turned on and off at any time by pressing [color=0x6090c0ff]LWIN + A[/color].
]]}
},
--------------------------------------------------------------
-- PAGE26
--------------------------------------------------------------
{
{'header2', [[M21 Armament Subsystem]]},
{'text', [[
The M21 armament sub-system consists of two M134 6x barrel 7.62mm high rate of fire machine guns and two 7 tube M158 2.75 inch aircraft rocket launchers.
]]},
{'header3', [[[color=0xffffffff]M134 7.62mm “Minigun”]]},
{'text', [[
The M134 automatic guns can be fired in either Stowed or Flexible modes. In Stowed mode, the guns are kept pointing straight and are aimed by pointing the nose of the helicopter directly toward the target. In Flexible mode, the guns can be steered horizontally and vertically using the left pilot’s flexible aiming sight to point at the target, allowing the right pilot to fly the helicopter away from the target while the left pilot engages.
The left pilot can fire the 7.62mm subsystem automatic guns from the Stowed or Flexible position, while the right pilot can only fire the subsystem from the Stowed position.
]]},
{'header3', [[[color=0xffffffff]Stow Mode]]},
{'text', [[
The guns may be stowed in a predetermined position and fired as a fixed weapon by the left or right pilot. This permits straight-ahead firing in an emergency by use of the firing switch on the pilot's or gunner's cyclic stick. To fire the automatic guns in the stow position, the armament selector switch is moved to “7.62” ([color=0x6090c0ff]RALT + ] [/color]/ [color=0x6090c0ff]RALT + [ [/color]) and the OFF-SAFE-ARMED switch to ARMED ([color=0x6090c0ff]RSHIFT + ] [/color] / [color=0x6090c0ff]RSHIFT + [ [/color]).
The pilot uses the XM60 infinity sight for stow fire by turning the elevation depression knob until the sight reticle pipper coincides with the strike of the bullets. Press [color=0x6090c0ff]RSHIFT + M[/color] to lower/raise the sight and [color=0x6090c0ff]RCTRL + M[/color] to turn the reticle lamp on/off.
]]}
},
--------------------------------------------------------------
-- PAGE27
--------------------------------------------------------------
{
{'picture', [[image manual page27.png]]},
{'header3', [[[color=0xffffffff]Flexible Mode]]},
{'text', [[
To employ the guns in Flexible mode:
	• Disengage the sighting station from its stowed position. [color=0x6090c0ff]M[/color]
	• Aim by moving the sighting station using the Numpad [color=0x6090c0ff]←[/color] / [color=0x6090c0ff]→[/color] / [color=0x6090c0ff]↑[/color] / [color=0x6090c0ff]↓[/color] keys or enable mouse pan mode by pressing [color=0x6090c0ff]LALT + C[/color] to aim with the mouse. 
	• Fire by pressing the [color=0x6090c0ff]SPACE[/color] key.
When Flexible Mode is engaged, the “Flexible Mode Active” indication is added to the Weapon Systems and Autopilot Status Indicator.

When you are in the left pilot’s position and have Flexible Mode active, the autopilot turns on automatically to fly the helicopter according to the set autopilot mode. The autopilot can be turned on and off manually by pressing [color=0x6090c0ff]LWIN + A[/color]. The autopilot engages when the following conditions are all true:
	• Flexible Mode Active
	• OFF-SAFE-ARMED switch is in the ARMED position
]]}
},
--------------------------------------------------------------
-- PAGE28
--------------------------------------------------------------
{
{'picture', [[image manual page28_1.png]]},
{'picture', [[image manual page28_2.png]]}
},
--------------------------------------------------------------
-- PAGE29
--------------------------------------------------------------
{
{'header3', [[[color=0xffffffff]M158 2.75” Unguided Rockets]]},
{'text', [[
The 2.75-inch rocket launchers are fixed to the support assembly and can only be fired from the Stow position. When the armament selector switch is positioned at “2.75”, the primary subsystem mode is rocket firing by means of cyclic stick firing switches.
To employ unguided rockets:
	• Prepare the XM60 infinity sight for rocket fire. Press [color=0x6090c0ff]RSHIFT + M[/color] to lower/raise the sight and [color=0x6090c0ff]RCTRL + M[/color] to turn the reticle lamp on/off. 
	• Set the armament selector switch to “2.75”. [color=0x6090c0ff]RALT + ] [/color] / [color=0x6090c0ff]RALT + [ [/color]
	• Set the rocket PAIR SELECTOR switch (to the desired number of rocket pairs to be fired. [color=0x6090c0ff]RCTRL + ] [/color] / [color=0x6090c0ff]RCTRL + [ [/color]
	• Position the OFF-SAFE-ARMED switch to ARMED and check to see that the SAFE indicator light goes out and the ARMED indicator light illuminates. [color=0x6090c0ff]RSHIFT + ] [/color] / [color=0x6090c0ff]RSHIFT+ [ [/color]
	• Using the sight reticle pipper as a reference aiming point, acquire the target by flying a target collision course, changing the attitude of the helicopter as necessary to align the sight reticle on the target.
	• When the proper sight picture has been developed, fire the rockets by depressing the firing switch on the cyclic control stick. [color=0x6090c0ff]SPACE[/color]
]]}
},
--------------------------------------------------------------
-- PAGE30
--------------------------------------------------------------
{
{'header2', [[AI Gunners Control and Status]]},
{'text', [[
The left pilot, left and right door gunners can be set to autonomously engage targets of opportunity. The left pilot engages targets with the M134 miniguns in Flex mode, while the door gunners engage targets using either the M134 door gun or the M60D door gun, depending on the payload profile. Turning on AI gunners requires setting the Rules of Engagement (ROE) mode for the desired gunner. In addition, the firing burst length can be set between Short and Long burst. These and other parameters can be monitored on the CREW STATUS panel.
]]},
{'picture', [[image manual page30.png]]},
{'text', [[
To cycle the ROE setting, press [color=0x6090c0ff]LCTRL + 2[/color], [color=0x6090c0ff]LCTRL+3[/color], [color=0x6090c0ff]LCTRL + 4[/color] for the left pilot, left door gunner, and right door gunner, respectively.
]]}
},
--------------------------------------------------------------
-- PAGE31
--------------------------------------------------------------
{
{'text', [[
The burst setting can be cycled between SHORT and LONG by pressing [color=0x6090c0ff]LSHIFT + 2[/color], [color=0x6090c0ff]LSHIFT + 3[/color], [color=0x6090c0ff]LSHIFT + 4[/color] for the left pilot, left door gunner, and right door gunner, respectively.
]]},
{'header2', [[M130 Flares Dispenser]]},
{'text', [[
The M130 Flare Dispenser M130 will dispense up to 2x30 decoy flares as a countermeasure to infrared seeking missiles. To deploy flares two at a time (one from each side of the fuselage), press [color=0x6090c0ff]LCTRL + C[/color].
]]},
{'picture', [[image manual page31.png]]}
}
}