local res = external_profile("Config/Input/Aircrafts/common_joystick_binding.lua")
local cockpit = folder.."../../../Cockpit/"
dofile(cockpit.."devices.lua")
dofile(cockpit.."command_defs.lua")

join(res.keyCommands,{

    -- Joystick switch abstractions (Example, ON else OFF)
    {down = fcs_commands.Switch_FLAP_SELECT,    up = fcs_commands.Switch_FLAP_SELECT,   cockpit_device_id=devices.VREST,            value_down=1.0, value_up=0.5,   name = _('Flaps CRUISE else AUTO'),				category = _('Joystick Switch Abstractions')},
    {down = fcs_commands.Switch_FLAP_SELECT,    up = fcs_commands.Switch_FLAP_SELECT,   cockpit_device_id=devices.VREST,            value_down=0.0, value_up=0.5,   name = _('Flaps STOL else AUTO'),				category = _('Joystick Switch Abstractions')},    
    {down = fcs_commands.Switch_ANTISKID,       up = fcs_commands.Switch_ANTISKID,      cockpit_device_id=devices.FLIGHTCONTROLS,   value_down=0.0, value_up=0.5,   name = _('Anti-Skid NWS else ON'),				category = _('Joystick Switch Abstractions')},
    {down = fcs_commands.Switch_ANTISKID,       up = fcs_commands.Switch_ANTISKID,      cockpit_device_id=devices.FLIGHTCONTROLS,   value_down=1.0, value_up=0.5,   name = _('Anti-Skid TEST else ON'),				category = _('Joystick Switch Abstractions')},
    {down = smc_commands.Switch_Master_Arm,     up = smc_commands.Switch_Master_Arm,    cockpit_device_id=devices.SMC,              value_down=1.0, value_up=0.0,   name = _('MasterArm ON else OFF'),				category = _('Joystick Switch Abstractions')},
    {down = engine_commands.Switch_H20,         up = engine_commands.Switch_H20,        cockpit_device_id=devices.DECS,             value_down=1.0, value_up=0.5,   name = _('H2O TO else OFF'),					category = _('Joystick Switch Abstractions')},
    {down = engine_commands.Switch_H20,         up = engine_commands.Switch_H20,        cockpit_device_id=devices.DECS,             value_down=0.0, value_up=0.5,   name = _('H2O LN else OFF'),					category = _('Joystick Switch Abstractions')},        
    {down = iCommandPlaneGearUp,                up = iCommandPlaneGearDown,     																					name = _('Landing Gear UP else DOWN'),			category = _('Joystick Switch Abstractions')},
	{down = fcs_commands.Handle_PARKING_BRAKE,  up = fcs_commands.Handle_PARKING_BRAKE, cockpit_device_id=devices.FLIGHTCONTROLS,	value_down=1.0, value_up=0.0,	name = _('Parking Brake Lever OFF else ON'),	category = _('Joystick Switch Abstractions')},
    {down = fcs_commands.Switch_FLAP_PWR,    up = fcs_commands.Switch_FLAP_RESET,   cockpit_device_id=devices.VREST,            value_down=1.0, value_up=0.5,   name = _('Flaps Power RESET else ON'),				category = _('Joystick Switch Abstractions')},
    {down = fcs_commands.Switch_FLAP_PWR,    up = fcs_commands.Switch_FLAP_PWR,   cockpit_device_id=devices.VREST,            value_down=0.0, value_up=0.5,   name = _('Flaps Power OFF else ON'),				category = _('Joystick Switch Abstractions')},  
    {down = ext_light_commands.Switch_LANDING_LT,  up = ext_light_commands.Switch_LANDING_LT,  cockpit_device_id = devices.LTEXT, value_down = 1,0, value_up=0.5, name = _('Landing Light APP else HVR'),                       category = _('Joystick Switch Abstractions')},
    {down = ext_light_commands.Switch_LANDING_LT,  up = ext_light_commands.Switch_LANDING_LT,  cockpit_device_id = devices.LTEXT, value_down = 0,0, value_up=0.5, name = _('Landing Light OFF else HVR'), 	                category = _('Joystick Switch Abstractions')}, 
   
	-- DCS Communications
	{down = iCommandPlaneRefuelingReadyPreContact,	name = _('A/A refueling - "Ready for precontact" radio call'), 		category = _('Communications')},
	
	-- Master Modes
	{down = iCommandHelicopter_PPR_button_K, 		name = _('Master Mode NAV'),										category = _('Master Modes')},
	{down = iCommandHelicopter_PPR_button_H,		name = _('Master Mode VSTOL'),										category = _('Master Modes')},
	{down = iCommandHelicopter_PPR_button_T, 		name = _('Master Mode AG'),											category = _('Master Modes')},
	
	-- HUD Controls
	{down = iCommandPlane_ABRIS_BT_1,									name = _('HUD Reject Mode Down (NORM - REJ1 - REJ2)'),	category = _('HUD Control')},
	{down = iCommandPlane_ABRIS_BT_2,									name = _('HUD Reject Mode Up (REJ2 - REJ1 - NORM)'),	category = _('HUD Control')},
	{down = iCommandPlane_ABRIS_BT_3,									name = _('HUD Display Mode Down DAY - AUTO - NIGHT'),	category = _('HUD Control')},
	{down = iCommandPlane_ABRIS_BT_5,									name = _('HUD Display Mode Up NIGHT - AUTO - DAY'),		category = _('HUD Control')},
	{down = iCommandPlane_ABRIS_BT_4,									name = _('HUD Altitude Selector'),						category = _('HUD Control')},
	{pressed = iCommandHUDBrightnessUp,		up = iCommandHUDTest_up,	name = _('HUD On - Brightness Increase'),				category = _('HUD Control')},
	{pressed = iCommandHUDBrightnessDown,	up = iCommandHUDTest_up,	name = _('HUD Brightness Decrease - Off'),				category = _('HUD Control')},
	{down = hud_commands.RejectSwitch,						cockpit_device_id = devices.HUDCONTROL,	value_down = 0.0,	name = _('HUD Reject Switch NORM'),			category = _('HUD Control')},
	{down = hud_commands.RejectSwitch,						cockpit_device_id = devices.HUDCONTROL,	value_down = 0.5,	name = _('HUD Reject Switch REJ1'),			category = _('HUD Control')},
	{down = hud_commands.RejectSwitch,						cockpit_device_id = devices.HUDCONTROL,	value_down = 1.0,	name = _('HUD Reject Switch REJ2'),			category = _('HUD Control')},
	{down = hud_commands.RejectSwitch_REJ1_TOGGLE,			cockpit_device_id = devices.HUDCONTROL,	value_down = 0.0,	name = _('HUD Reject Switch REJ1/NORM'),	category = _('HUD Control')},
	{down = hud_commands.RejectSwitch_REJ2_TOGGLE,			cockpit_device_id = devices.HUDCONTROL,	value_down = 0.0,	name = _('HUD Reject Switch REJ2/NORM'),	category = _('HUD Control')},
	{down = hud_commands.DisplayModeSwitch,					cockpit_device_id = devices.HUDCONTROL,	value_down = 0.0,	name = _('HUD Display Mode DAY'),			category = _('HUD Control')},
	{down = hud_commands.DisplayModeSwitch,					cockpit_device_id = devices.HUDCONTROL,	value_down = 0.5,	name = _('HUD Display Mode AUTO'),			category = _('HUD Control')},
	{down = hud_commands.DisplayModeSwitch,					cockpit_device_id = devices.HUDCONTROL,	value_down = 1.0,	name = _('HUD Display Mode NIGHT'),			category = _('HUD Control')},
	{down = hud_commands.DisplayModeSwitch_NIGHT_TOGGLE,	cockpit_device_id = devices.HUDCONTROL,	value_down = 0,		name = _('HUD Display Mode NIGHT/AUTO'),	category = _('HUD Control')},
	{down = hud_commands.DisplayModeSwitch_DAY_TOGGLE,		cockpit_device_id = devices.HUDCONTROL,	value_down = 0,		name = _('HUD Display Mode DAY/AUTO'),		category = _('HUD Control')},
	{down = hud_commands.AltitudeSelector,					cockpit_device_id = devices.HUDCONTROL,	value_down = 0,		name = _('HUD Altitude Selector BARO'),		category = _('HUD Control')},
	{down = hud_commands.AltitudeSelector,					cockpit_device_id = devices.HUDCONTROL,	value_down = 1,		name = _('HUD Altitude Selector RDR'),		category = _('HUD Control')}, 
	
	-- VSTOL Controls
	{down = iCommandPlane_ABRIS_Axis_Increase,			name = _('Flaps Mode Up (STOL - AUTO - CRUISE)'),	category = _('VSTOL Controls')},
	{down = iCommandPlane_ABRIS_Axis_Decrease,			name = _('Flaps Mode Down (CRUISE - AUTO - STOL)'),	category = _('VSTOL Controls')},
	{down = iCommandPlaneFlapsOn, 						name = _('Flaps Power Left (OFF - ON - RESET)'),	category = _('VSTOL Controls')},
	{down = iCommandPlaneFlapsOff,						name = _('Flaps Power Right (RESET - ON - OFF)'),	category = _('VSTOL Controls')},
	{down = iCommandPlane_ABRIS_Brightness_Increase,	name = _('Water Mode Up (LDG - OFF - TO)'),			category = _('VSTOL Controls')},
	{down = iCommandPlane_ABRIS_Brightness_Decrease,	name = _('Water Mode Down (TO - OFF - LDG)'),		category = _('VSTOL Controls')},
	----
	{down = fcs_commands.Switch_FLAP_PWR,										cockpit_device_id = devices.VREST,	value_down = 0.0,					name = _('Flaps Power OFF'),		category = _('VSTOL Controls')},
	{down = fcs_commands.Switch_FLAP_PWR,										cockpit_device_id = devices.VREST,	value_down = 0.5,					name = _('Flaps Power ON'),			category = _('VSTOL Controls')},
	{down = fcs_commands.Switch_FLAP_PWR,										cockpit_device_id = devices.VREST,	value_down = 1.0,					name = _('Flaps Power RESET'),		category = _('VSTOL Controls')},
	{down = fcs_commands.Switch_FLAP_PWR_ON_TOGGLE,								cockpit_device_id = devices.VREST,	value_down = 0.0,					name = _('Flaps Power ON/OFF'),		category = _('VSTOL Controls')},
	{down = fcs_commands.Switch_FLAP_PWR_RESET_TOGGLE,							cockpit_device_id = devices.VREST,	value_down = 1.0,					name = _('Flaps Power RESET/OFF'),	category = _('VSTOL Controls')},
	{down = fcs_commands.Switch_FLAP_SELECT,									cockpit_device_id = devices.VREST,	value_down = 0.0,					name = _('Flaps STOL'),				category = _('VSTOL Controls')},
	{down = fcs_commands.Switch_FLAP_SELECT,									cockpit_device_id = devices.VREST,	value_down = 0.5,					name = _('Flaps AUTO, '),			category = _('VSTOL Controls')},
	{down = fcs_commands.Switch_FLAP_SELECT,									cockpit_device_id = devices.VREST,	value_down = 1.0,					name = _('Flaps CRUISE, '),			category = _('VSTOL Controls')},
    {down = fcs_commands.Button_FLAP_BIT,	up = fcs_commands.Button_FLAP_BIT,	cockpit_device_id = devices.VREST,	value_down = 1.0, value_up = 0.0,	name = _('Flaps BIT Button'),		category = _('VSTOL Controls')},
	
	-- Flight Control
	{pressed = iCommandPlaneUpStart,						up = iCommandPlaneUpStop,			name = _('Aircraft Pitch DOWN'),	category = _('Flight Control')},
	{pressed = iCommandPlaneDownStart,						up = iCommandPlaneDownStop,			name = _('Aircraft Pitch UP'),		category = _('Flight Control')},
	{pressed = iCommandPlaneLeftStart,						up = iCommandPlaneLeftStop,			name = _('Aircraft Bank LEFT'),		category = _('Flight Control')},
	{pressed = iCommandPlaneRightStart,						up = iCommandPlaneRightStop,		name = _('Aircraft Bank RIGHT'),	category = _('Flight Control')},
	{pressed = iCommandPlaneLeftRudderStart,				up = iCommandPlaneLeftRudderStop,	name = _('Aircraft Rudder LEFT'),	category = _('Flight Control')},
	{pressed = iCommandPlaneRightRudderStart,				up = iCommandPlaneRightRudderStop,	name = _('Aircraft Rudder RIGHT'),	category = _('Flight Control')},
	{pressed = iCommandThrottleIncrease,					up = iCommandThrottleStop,			name = _('Throttle UP'),			category = _('Flight Control')},
	{pressed = iCommandThrottleDecrease,					up = iCommandThrottleStop,			name = _('Throttle DOWN'),			category = _('Flight Control')},
	{pressed = iCommandPlaneCollectiveIncrease,				up = iCommandPlaneCollectiveStop,	name = _('Nozzle Rotation UP'),		category = _('Flight Control')},
	{pressed = iCommandPlaneCollectiveDecrease,				up = iCommandPlaneCollectiveStop,	name = _('Nozzle Rotation DOWN'),	category = _('Flight Control')},
	{down = iCommandHelicopter_CollectiveStopper_Up,		up = iCommandPlaneCollectiveStop,	name = _('STO STOP UP'),			category = _('Flight Control')},
	{down = iCommandHelicopter_CollectiveStopper_Down,	    up = iCommandPlaneCollectiveStop,	name = _('STO STOP DOWN'),			category = _('Flight Control')},
	{pressed = iCommandPlaneTrimLeftRudder,					up = iCommandPlaneTrimStop,			name = _('Trim RUDDER LEFT'),		category = _('Flight Control')},
	{pressed = iCommandPlaneTrimRightRudder,				up = iCommandPlaneTrimStop,			name = _('Trim RUDDER RIGHT'),		category = _('Flight Control')},
	{down = iCommandADI_Test,																	name = _('Backup ADI Cage Toggle'),			category = _('Flight Control')},	
	{pressed = iCommandADI_ZeroPitchTrimLeft,				up = iCommandADI_Test_up,			name = _('Backup ADI Pitch Adjust Up'),		category = _('Flight Control')},	
	{pressed = iCommandADI_ZeroPitchTrimRight,				up = iCommandADI_Test_up,			name = _('Backup ADI Pitch Adjust Down'),	category = _('Flight Control')},	
	
	-- SAAHS
	{down = iCommandPlaneAutopilot,						name = _('Automatic Flight Control On/Off Toggle'),				category = _('Stability Augmentation & Autopilot')},
	{down = iCommandPlaneSAUHBarometric,				name = _('Altitude Hold On/Off Toggle'),						category = _('Stability Augmentation & Autopilot')},
	{down = iCommandPlaneAUTOnOff,						name = _('Q Feel On/Off Toggle'),								category = _('Stability Augmentation & Autopilot')},
	{down = iCommandPlaneSAUHRadio,						name = _('Stability Augmentation - Pitch'),						category = _('Stability Augmentation & Autopilot')},
	{down = iCommandPlaneSAUAutomatic,					name = _('Stability Augmentation - Yaw'),						category = _('Stability Augmentation & Autopilot')},
	{down = iCommandPlaneSAUHorizon,  					name = _('Stability Augmentation - Roll'),      															category = _('Stability Augmentation & Autopilot')},
    {down = fcs_commands.Switch_RPS_YAW,				cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 0.0, name = _('RPS/YAW Shaker Switch OFF'),		category = _('Stability Augmentation & Autopilot')},
    {down = fcs_commands.Switch_RPS_YAW,				cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 0.5, name = _('RPS/YAW Shaker Switch ON'),			category = _('Stability Augmentation & Autopilot')},
    {down = fcs_commands.Switch_RPS_YAW,				cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 1.0, name = _('RPS/YAW Shaker Switch TEST'),		category = _('Stability Augmentation & Autopilot')},    
    {down = fcs_commands.Switch_RPS_YAW_ON,				cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 0.0, name = _('RPS/YAW Shaker Switch OFF/ON'),  	category = _('Stability Augmentation & Autopilot')},
    {down = fcs_commands.Switch_RPS_YAW_TEST,			cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 0.0, name = _('RPS/YAW Shaker Switch OFF/TEST'),	category = _('Stability Augmentation & Autopilot')},
    
    {down = fcs_commands.Switch_Q_FEEL,		cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 1.0, name = _('Q Feel ON'), 							category = _('Stability Augmentation & Autopilot')},
    {down = fcs_commands.Switch_Q_FEEL,		cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 0.0, name = _('Q Feel OFF'), 							category = _('Stability Augmentation & Autopilot')},
    {down = fcs_commands.Switch_ALT_HOLD,	cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 1.0, name = _('Altitude Hold ON'), 					category = _('Stability Augmentation & Autopilot')},
    {down = fcs_commands.Switch_ALT_HOLD,	cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 0.0, name = _('Altitude Hold OFF'), 					category = _('Stability Augmentation & Autopilot')},
    {down = fcs_commands.Switch_AFC,		cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 1.0, name = _('Automatic Flight Control ON'), 			category = _('Stability Augmentation & Autopilot')},
    {down = fcs_commands.Switch_AFC,		cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 0.5, name = _('Automatic Flight Control OFF'), 		category = _('Stability Augmentation & Autopilot')},
    {down = fcs_commands.Switch_AFC,    	cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 0.0, name = _('Automatic Flight Control Reset'), 		category = _('Stability Augmentation & Autopilot')},
    {down = fcs_commands.Switch_SAS_PITCH,	cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 1.0, name = _('Stability Augmentation - Pitch ON'), 	category = _('Stability Augmentation & Autopilot')},
    {down = fcs_commands.Switch_SAS_PITCH,	cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 0.0, name = _('Stability Augmentation - Pitch OFF'), 	category = _('Stability Augmentation & Autopilot')},
    {down = fcs_commands.Switch_SAS_YAW,	cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 1.0, name = _('Stability Augmentation - Yaw ON'), 		category = _('Stability Augmentation & Autopilot')},
    {down = fcs_commands.Switch_SAS_YAW,	cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 0.0, name = _('Stability Augmentation - Yaw OFF'), 	category = _('Stability Augmentation & Autopilot')},
    {down = fcs_commands.Switch_SAS_ROLL,	cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 1.0, name = _('Stability Augmentation - Roll ON'), 	category = _('Stability Augmentation & Autopilot')},
    {down = fcs_commands.Switch_SAS_ROLL,	cockpit_device_id = devices.FLIGHTCONTROLS, value_down = 0.0, name = _('Stability Augmentation - Roll OFF'), 	category = _('Stability Augmentation & Autopilot')},      
		
	-- Hydraulic & Mechanical
    {down = iCommandPlaneWheelBrakeOn,			up = iCommandPlaneWheelBrakeOff,		name = _('Wheel Brakes'),			category = _('Hydraulic & Mechanical')},
    {down = iCommandPlaneWheelBrakeLeftOn,		up = iCommandPlaneWheelBrakeLeftOff,	name = _('Wheel Brake LEFT'),		category = _('Hydraulic & Mechanical')},
    {down = iCommandPlaneWheelBrakeRightOn,		up = iCommandPlaneWheelBrakeRightOff,	name = _('Wheel Brake RIGHT'),		category = _('Hydraulic & Mechanical')},
    {down = iCommandPlaneGear,															name = _('Landing Gear TOGGLE'),	category = _('Hydraulic & Mechanical')},
    {down = iCommandPlaneGearUp,														name = _('Landing Gear UP'),		category = _('Hydraulic & Mechanical')},
    {down = iCommandPlaneGearDown,														name = _('Landing Gear DOWN'),		category = _('Hydraulic & Mechanical')},
    {down = iCommandPlaneFonar,															name = _('Canopy Open/Close'),		category = _('Hydraulic & Mechanical')},
	{down = misc_commands.canopy_lock_lever,	up = misc_commands.canopy_lock_lever,	cockpit_device_id = devices.FLIGHTCONTROLS,	value_down = 1.0,	value_up = 0,	name = _('Canopy Locking Lever toggle'),				category = _('Hydraulic & Mechanical')},
    {down = fcs_commands.Button_GEAR_DN_LOCK,	up = fcs_commands.Button_GEAR_DN_LOCK,	cockpit_device_id = devices.FLIGHTCONTROLS,	value_down = 1.0,	value_up = 0,	name = _('DN LOCK OVRD Landing Gear Button'),			category = _('Hydraulic & Mechanical')},
    {down = fcs_commands.Handle_GEAR_LEVER_EMERG,										cockpit_device_id = devices.FLIGHTCONTROLS,	value_down = 1.0,					name = _('Emergency Landing Gear Deployment'),			category = _('Hydraulic & Mechanical')},
    {down = fcs_commands.Handle_GEAR_BATT_LIFT,											cockpit_device_id = devices.FLIGHTCONTROLS,	value_down = 1.0,					name = _('Emergency Landing Gear Battery Activate'),	category = _('Hydraulic & Mechanical')},
	{down = fcs_commands.Handle_PARKING_BRAKE,											cockpit_device_id = devices.FLIGHTCONTROLS,	value_down = 0.0,					name = _('Parking Brake ON'),							category = _('Hydraulic & Mechanical')},
    {down = fcs_commands.Handle_PARKING_BRAKE,											cockpit_device_id = devices.FLIGHTCONTROLS,	value_down = 1.0,					name = _('Parking Brake OFF'),							category = _('Hydraulic & Mechanical')},
	{down = fcs_commands.Switch_ANTISKID,												cockpit_device_id = devices.FLIGHTCONTROLS,	value_down = 1.0,					name = _('Anti-skid TEST'),								category = _('Hydraulic & Mechanical')},
	{down = fcs_commands.Switch_ANTISKID,												cockpit_device_id = devices.FLIGHTCONTROLS,	value_down = 0.0,					name = _('Anti-skid NWS'),								category = _('Hydraulic & Mechanical')},
	{down = fcs_commands.Switch_ANTISKID,												cockpit_device_id = devices.FLIGHTCONTROLS,	value_down = 0.5,					name = _('Anti-skid ON'),								category = _('Hydraulic & Mechanical')},
	{down = fcs_commands.Switch_ANTISKID_NWS_TOGGLE,									cockpit_device_id = devices.FLIGHTCONTROLS,	value_down = 0.0,					name = _('Anti-skid NWS/ON Toggle'),					category = _('Hydraulic & Mechanical')},
	
	-- Engine & Fuel
	{down = iCommandPlaneHook,																	name = _('Air Refueling Probe Toggle IN/OUT'),		category = _('Engine & Fuel')},
	{down = iCommandThrottle1Stop,																name = _('Fuel Shutoff Lever lock release'),		category = _('Engine & Fuel')},
	{down = iCommandPlaneRefuelStatusIndLTSIncrease,											name = _('Fuel Quantity Indicator CW'),				category = _('Engine & Fuel')},
	{down = iCommandPlaneRefuelStatusIndLTSDecrease,											name = _('Fuel Quantity Indicator CCW'),			category = _('Engine & Fuel')},
	{down = iCommandPlaneFSRefuelLigtingIncrease,			up = iCommandPlaneFSReceiverLever,	name = _('Bingo Fuel Level Increase'),				category = _('Engine & Fuel')},
	{down = iCommandPlaneFSRefuelLigtingDecrease,			up = iCommandPlaneFSReceiverLever,	name = _('Bingo Fuel Level Decrease'),				category = _('Engine & Fuel')},
	{down = engine_commands.Switch_LIDS,					cockpit_device_id = devices.VREST, value_down = 0,	name = _('LIDS Switch NORM'),						category = _('Engine & Fuel')},
	{down = engine_commands.Switch_LIDS,					cockpit_device_id = devices.VREST, value_down = 1,	name = _('LIDS Switch RETRACT'),					category = _('Engine & Fuel')},
	{down = engine_commands.Switch_LIDS_TOGGLE,				cockpit_device_id = devices.VREST, value_down = 1,	name = _('LIDS Switch TOGGLE'),						category = _('Engine & Fuel')},
	{down = engine_commands.Switch_ENG_RPM,					cockpit_device_id = devices.DECS, value_down = 0,	name = _('ENG RPM Switch LOW'),						category = _('Engine & Fuel')},
	{down = engine_commands.Switch_ENG_RPM,					cockpit_device_id = devices.DECS, value_down = 1,	name = _('ENG RPM Switch HI'),						category = _('Engine & Fuel')},
	{down = engine_commands.Switch_EFC,						cockpit_device_id = devices.DECS, value_down = 0,	name = _('EFC Switch POS 2'),						category = _('Engine & Fuel')},
	{down = engine_commands.Switch_EFC,						cockpit_device_id = devices.DECS, value_down = 1,	name = _('EFC Switch POS 1'),						category = _('Engine & Fuel')},
	{down = engine_commands.Switch_EFC_TOGGLE,				cockpit_device_id = devices.DECS, value_down = 1,	name = _('EFC On/Off TOGGLE'),						category = _('Engine & Fuel')},     
	{down = engine_commands.Switch_H20,						cockpit_device_id = devices.DECS, value_down = 0.5,	name = _('H2O Switch OFF'),							category = _('Engine & Fuel')},
	{down = engine_commands.Switch_H20,						cockpit_device_id = devices.DECS, value_down = 0,	name = _('H2O Switch LDG'),							category = _('Engine & Fuel')},
	{down = engine_commands.Switch_H20,						cockpit_device_id = devices.DECS, value_down = 1,	name = _('H2O Switch TO'),							category = _('Engine & Fuel')},
	{down = engine_commands.Switch_H20_DUMP,				cockpit_device_id = devices.DECS, value_down = 0,	name = _('H2O Dump Switch OFF'),					category = _('Engine & Fuel')},
	{down = engine_commands.Switch_H20_DUMP,				cockpit_device_id = devices.DECS, value_down = 1,	name = _('H2O Dump Switch DUMP'),					category = _('Engine & Fuel')},
	{down = engine_commands.Switch_H20_DUMP_TOGGLE,			cockpit_device_id = devices.DECS, value_down = 0,	name = _('H2O Dump Switch TOGGLE'),					category = _('Engine & Fuel')},
	{down = engine_commands.Switch_JPTL,					cockpit_device_id = devices.DECS, value_down = 1,	name = _('JPTL Switch ON'),							category = _('Engine & Fuel')},
	{down = engine_commands.Switch_JPTL,					cockpit_device_id = devices.DECS, value_down = 0,	name = _('JPTL Switch OFF'),						category = _('Engine & Fuel')},
	{down = engine_commands.Switch_JPTLTOGGLE,				cockpit_device_id = devices.DECS, value_down = 0,	name = _('JPTL Switch TOGGLE'),						category = _('Engine & Fuel')},
	{down = engine_commands.Switch_MAN_FUEL,				cockpit_device_id = devices.DECS, value_down = 0,	name = _('Manual Fuel Switch OFF'),					category = _('Engine & Fuel')},
	{down = engine_commands.Switch_MAN_FUEL,				cockpit_device_id = devices.DECS, value_down = 1,	name = _('Manual Fuel Switch ON'),					category = _('Engine & Fuel')},
	{down = engine_commands.Switch_MAN_FUEL_TOGGLE,			cockpit_device_id = devices.DECS, value_down = 0,	name = _('Manual Fuel Switch TOGGLE'),				category = _('Engine & Fuel')},
	{down = engine_commands.Switch_FUEL_PROP,				cockpit_device_id = devices.DECS, value_down = 0,	name = _('Fuel PROP Switch OFF'),					category = _('Engine & Fuel')},
	{down = engine_commands.Switch_FUEL_PROP,				cockpit_device_id = devices.DECS, value_down = 1,	name = _('Fuel PROP Switch ON'),					category = _('Engine & Fuel')},
	{down = engine_commands.Switch_FUEL_PUMP_L,				cockpit_device_id = devices.DECS, value_down = 0.5,	name = _('Fuel Pump Left Switch OFF'),				category = _('Engine & Fuel')},
	{down = engine_commands.Switch_FUEL_PUMP_L,				cockpit_device_id = devices.DECS, value_down = 1,	name = _('Fuel Pump Left Switch ON'),				category = _('Engine & Fuel')},
	{down = engine_commands.Switch_FUEL_PUMP_L,				cockpit_device_id = devices.DECS, value_down = 0,	name = _('Fuel Pump Left Switch DC OPR'),			category = _('Engine & Fuel')},
	{down = engine_commands.Switch_FUEL_PUMP_L_TOGGLE_ON,	cockpit_device_id = devices.DECS, value_down = 0,	name = _('Fuel Pump Left Switch ON/OFF'),			category = _('Engine & Fuel')},
	{down = engine_commands.Switch_FUEL_PUMP_L_TOGGLE_OPR,	cockpit_device_id = devices.DECS, value_down = 0,	name = _('Fuel Pump Left Switch DC OPR/OFF'),		category = _('Engine & Fuel')},
	{down = engine_commands.Switch_FUEL_PUMP_R,				cockpit_device_id = devices.DECS, value_down = 0.5,	name = _('Fuel Pump Right Switch OFF'),				category = _('Engine & Fuel')},
	{down = engine_commands.Switch_FUEL_PUMP_R,				cockpit_device_id = devices.DECS, value_down = 1,	name = _('Fuel Pump Right Switch ON'),				category = _('Engine & Fuel')},
	{down = engine_commands.Switch_FUEL_PUMP_R,				cockpit_device_id = devices.DECS, value_down = 0,	name = _('Fuel Pump Right Switch DC OPR'),			category = _('Engine & Fuel')},
	{down = engine_commands.Switch_FUEL_PUMP_R_TOGGLE_ON,	cockpit_device_id = devices.DECS, value_down = 0,	name = _('Fuel Pump Right Switch ON/OFF'),			category = _('Engine & Fuel')},
	{down = engine_commands.Switch_FUEL_PUMP_R_TOGGLE_OPR,	cockpit_device_id = devices.DECS, value_down = 0,	name = _('Fuel Pump Right Switch DC OPR/OFF'),		category = _('Engine & Fuel')},
	{down = engine_commands.Switch_FUEL_PRESS,				cockpit_device_id = devices.DECS, value_down = 0,	name = _('Air Refueling Probe Switch IN'),			category = _('Engine & Fuel')},
	{down = engine_commands.Switch_FUEL_PRESS,				cockpit_device_id = devices.DECS, value_down = 0.5,	name = _('Air Refueling Probe Switch OUT'),			category = _('Engine & Fuel')},
	{down = engine_commands.Switch_FUEL_PRESS,				cockpit_device_id = devices.DECS, value_down = 1,	name = _('Air Refueling Probe Switch PRESS'),		category = _('Engine & Fuel')},
	{down = engine_commands.Switch_FUEL_PRESS_TOGGLE,		cockpit_device_id = devices.DECS, value_down = 0,	name = _('Air Refueling Probe Toggle IN/PRESS'),	category = _('Engine & Fuel')},         
	{down = engine_commands.Switch_FUEL_DUMP_L,				cockpit_device_id = devices.DECS, value_down = 0,	name = _('Fuel Dump Left Switch NORM'),				category = _('Engine & Fuel')},
	{down = engine_commands.Switch_FUEL_DUMP_L,				cockpit_device_id = devices.DECS, value_down = 1,	name = _('Fuel Dump Left Switch DUMP'),				category = _('Engine & Fuel')},         
	{down = engine_commands.Switch_FUEL_DUMP_L_TOGGLE,		cockpit_device_id = devices.DECS, value_down = 0,	name = _('Fuel Dump Left Switch TOGGLE'),			category = _('Engine & Fuel')},
	{down = engine_commands.Switch_FUEL_DUMP_R,				cockpit_device_id = devices.DECS, value_down = 0,	name = _('Fuel Dump Right Switch NORM'),			category = _('Engine & Fuel')},
	{down = engine_commands.Switch_FUEL_DUMP_R,				cockpit_device_id = devices.DECS, value_down = 1,	name = _('Fuel Dump Right Switch DUMP'),			category = _('Engine & Fuel')},
	{down = engine_commands.Switch_FUEL_DUMP_R_TOGGLE,		cockpit_device_id = devices.DECS, value_down = 0,	name = _('Fuel Dump Right Switch TOGGLE'),			category = _('Engine & Fuel')},
	{down = engine_commands.Handle_FUEL_SHUT_OFF,			cockpit_device_id = devices.DECS, value_down = 0,	name = _('Fuel Shutoff Lever OFF'),					category = _('Engine & Fuel')},
	{down = engine_commands.Handle_FUEL_SHUT_OFF,			cockpit_device_id = devices.DECS, value_down = 1,	name = _('Fuel Shutoff Lever ON'),					category = _('Engine & Fuel')},
	{down = engine_commands.Switch_DECS,					cockpit_device_id = devices.DECS, value_down = 0,	name = _('DECS Switch OFF'),						category = _('Engine & Fuel')},      
	{down = engine_commands.Switch_DECS,					cockpit_device_id = devices.DECS, value_down = 1,	name = _('DECS Switch ON'),							category = _('Engine & Fuel')},
	{down = engine_commands.Switch_DECS_TOGGLE,				cockpit_device_id = devices.DECS, value_down = 0,	name = _('DECS On/Off TOGGLE'),						category = _('Engine & Fuel')},      
	{down = fqi_commands.FuelSelector,						cockpit_device_id = devices.FQIS, value_down =  0.0,	name = _('FQI: INT'),							category = _('Engine & Fuel')},
	{down = fqi_commands.FuelSelector,						cockpit_device_id = devices.FQIS, value_down =  0.33,	name = _('FQI Mode: TOT'),						category = _('Engine & Fuel')},
	{down = fqi_commands.FuelSelector,						cockpit_device_id = devices.FQIS, value_down =  0.66,	name = _('FQI Mode: FEED'),						category = _('Engine & Fuel')},
	{down = fqi_commands.FuelSelector,						cockpit_device_id = devices.FQIS, value_down =  0.99,	name = _('FQI Mode: BIT'),						category = _('Engine & Fuel')},
	{down = fqi_commands.FuelSelector,						cockpit_device_id = devices.FQIS, value_down = -0.33,	name = _('FQI Mode: WING'),						category = _('Engine & Fuel')},
	{down = fqi_commands.FuelSelector,						cockpit_device_id = devices.FQIS, value_down = -0.66,	name = _('FQI Mode: INBD'),						category = _('Engine & Fuel')},
	{down = fqi_commands.FuelSelector,						cockpit_device_id = devices.FQIS, value_down = -0.99,	name = _('FQI Mode: OUTBD'),					category = _('Engine & Fuel')},
	{down = engine_commands.Switch_FUEL_PROP_TOGGLE,							cockpit_device_id = devices.DECS,	value_down = 0,		value_up = 1, 	name = _('Fuel PROP Switch TOGGLE'),	category = _('Engine & Fuel')},
	{down = engine_commands.Button_CMBT,	up = engine_commands.Button_CMBT,	cockpit_device_id = devices.DECS,	value_down = 1.0,	value_up = 0,	name = _('CMBT Button PRESS'),			category = _('Engine & Fuel')},
	{down = engine_commands.Button_EMS,		up = engine_commands.Button_EMS,	cockpit_device_id = devices.DECS,	value_down = 1.0,	value_up = 0,	name = _('EMS Button PRESS'),			category = _('Engine & Fuel')},
	{down = edp_commands.BIT_Button,		up = edp_commands.BIT_Button,		cockpit_device_id = devices.EDP,	value_down = 1.0,	value_up = 0,	name = _('EDP BIT Button'),				category = _('Engine & Fuel')},
	
    -- ECM Control Panel
	{down = iCommandRWRIntensityIncrease,					name = _('RWR Knob CW'),						category = _('ECM Control panel')},
	{down = iCommandRWRIntensityDecrease,					name = _('RWR Knob CCW'),						category = _('ECM Control panel')},
	{down = iCommandPlaneCMDChangeRippleQuantity,			name = _('EXP Decoy Dispenser Control CW'),		category = _('ECM Control panel')},
	{down = iCommandPlaneCMDChangeRippleQuantityOff,		name = _('EXP Decoy Dispenser Control CCW'),	category = _('ECM Control panel')},
	{down = iCommandActiveJamming,							name = _('Jammer Control Mode CW'),				category = _('ECM Control panel')},
	{down = iCommandActiveIRJamming,						name = _('Jammer Control Mode CCW'),			category = _('ECM Control panel')},
	{down = rwr_commands.Knob_EXP,		cockpit_device_id = devices.EWS,	value_down = 0.00, 	name = _('EXP Decoy Dispenser Control : OFF'),	category = _('ECM Control panel')},
	{down = rwr_commands.Knob_EXP,		cockpit_device_id = devices.EWS,	value_down = 0.25, 	name = _('EXP Decoy Dispenser Control: AUTO'),	category = _('ECM Control panel')},
	{down = rwr_commands.Knob_EXP,		cockpit_device_id = devices.EWS,	value_down = 0.50, 	name = _('EXP Decoy Dispenser Control: UP'),	category = _('ECM Control panel')},
	{down = rwr_commands.Knob_EXP,		cockpit_device_id = devices.EWS,	value_down = 0.75, 	name = _('EXP Decoy Dispenser Control: DOWN'),	category = _('ECM Control panel')},
	{down = rwr_commands.Knob_EXP,		cockpit_device_id = devices.EWS,	value_down = 1.00, 	name = _('EXP Decoy Dispenser Control: RWR'),	category = _('ECM Control panel')},
	{down = rwr_commands.Knob_ECM,		cockpit_device_id = devices.EWS,	value_down = 0.00, 	name = _('Jammer Control Mode: OFF'),			category = _('ECM Control panel')},
	{down = rwr_commands.Knob_ECM,		cockpit_device_id = devices.EWS,	value_down = 0.25, 	name = _('Jammer Control Mode: STBY'),			category = _('ECM Control panel')},
	{down = rwr_commands.Knob_ECM,		cockpit_device_id = devices.EWS,	value_down = 0.50, 	name = _('Jammer Control Mode: BIT'),			category = _('ECM Control panel')},
	{down = rwr_commands.Knob_ECM,		cockpit_device_id = devices.EWS,	value_down = 0.75, 	name = _('Jammer Control Mode: RCV'),			category = _('ECM Control panel')},
	{down = rwr_commands.Knob_ECM,		cockpit_device_id = devices.EWS,	value_down = 1.00, 	name = _('Jammer Control Mode: RPT'),			category = _('ECM Control panel')},
	
    -- ECS
	{down = psp_commands.Switch_OXY,				cockpit_device_id = devices.ECS,	value_down = 0,		name = _('Oxygen Switch OFF'),				category = _('Environmental Control')},   	
	{down = psp_commands.Switch_OXY,				cockpit_device_id = devices.ECS,	value_down = 1,		name = _('Oxygen Switch ON'),				category = _('Environmental Control')},
	{down = psp_commands.Switch_OXY_TOGGLE, 		cockpit_device_id = devices.ECS,	value_down = 0,		name = _('Oxygen Switch TOGGLE'),			category = _('Environmental Control')},     	
	{down = ecs_commands.Switch_FWD_EQUIP,			cockpit_device_id = devices.ECS,	value_down = 0,		name = _('Fwd Equipment Bay NORM'),			category = _('Environmental Control')},         
	{down = ecs_commands.Switch_FWD_EQUIP,			cockpit_device_id = devices.ECS,	value_down = 0.5,	name = _('Fwd Equipment Bay ECS Switch'),	category = _('Environmental Control')},         
	{down = ecs_commands.Switch_FWD_EQUIP,			cockpit_device_id = devices.ECS,	value_down = 1,		name = _('Fwd Equipment Bay RESET'),		category = _('Environmental Control')},  
	{down = ecs_commands.Switch_AFT_EQUIP,			cockpit_device_id = devices.ECS,	value_down = 0,		name = _('AFT Equipment Bay OFF'),			category = _('Environmental Control')},         
	{down = ecs_commands.Switch_AFT_EQUIP,			cockpit_device_id = devices.ECS,	value_down = 0.5,	name = _('AFT Equipment Bay ON'),			category = _('Environmental Control')},         
	{down = ecs_commands.Switch_AFT_EQUIP,			cockpit_device_id = devices.ECS,	value_down = 1,		name = _('AFT Equipment Bay RESET'),		category = _('Environmental Control')},
	{down = ecs_commands.Switch_CABIN,				cockpit_device_id = devices.ECS,	value_down = 1,		name = _('CABIN DEFOG NORM'),				category = _('Environmental Control')},         
	{down = ecs_commands.Switch_CABIN,				cockpit_device_id = devices.ECS,	value_down = 0.5,	name = _('CABIN DEFOG'),					category = _('Environmental Control')},         
	{down = ecs_commands.Switch_CABIN,				cockpit_device_id = devices.ECS,	value_down = 0,		name = _('CABIN DEFOG MAX'),				category = _('Environmental Control')},
	{down = ecs_commands.Switch_PRESS,				cockpit_device_id = devices.ECS,	value_down = 1,		name = _('PRESS NORM'),						category = _('Environmental Control')},         
	{down = ecs_commands.Switch_PRESS,				cockpit_device_id = devices.ECS,	value_down = 0.5,	name = _('PRESS DUMP'),						category = _('Environmental Control')},         
	{down = ecs_commands.Switch_PRESS,				cockpit_device_id = devices.ECS,	value_down = 0,		name = _('PRESS RAM'),						category = _('Environmental Control')},  
	
	-- Electrical Panel
	{down = elec_commands.Switch_BATT, 				cockpit_device_id = devices.ELECTRIC, value_down = 1,	name = _('Battery ON'),					category = _('Electrical Panel')},
	{down = elec_commands.Switch_BATT, 				cockpit_device_id = devices.ELECTRIC, value_down = 0.5,	name = _('Battery OFF'),				category = _('Electrical Panel')},
	{down = elec_commands.Switch_BATT, 				cockpit_device_id = devices.ELECTRIC, value_down = 0,	name = _('Battery Alert'),				category = _('Electrical Panel')},
	{down = elec_commands.Switch_BATT_ON_TOGGLE, 	cockpit_device_id = devices.ELECTRIC, value_down = 0,	name = _('Battery ON/OFF'),				category = _('Electrical Panel')},
	{down = elec_commands.Switch_GEN, 				cockpit_device_id = devices.ELECTRIC, value_down = 1,	name = _('Generator ON'),				category = _('Electrical Panel')},
	{down = elec_commands.Switch_GEN, 				cockpit_device_id = devices.ELECTRIC, value_down = 0.5,	name = _('Generator OFF'),				category = _('Electrical Panel')},
	{down = elec_commands.Switch_GEN, 				cockpit_device_id = devices.ELECTRIC, value_down = 0,	name = _('Generator Test'),				category = _('Electrical Panel')},
	{down = elec_commands.Switch_GEN_ON_TOGGLE, 	cockpit_device_id = devices.ELECTRIC, value_down = 0,	name = _('Generator ON/OFF'),			category = _('Electrical Panel')},
	{down = elec_commands.Switch_ENG_START, 		cockpit_device_id = devices.ELECTRIC, value_down = 1,	name = _('Engine Start ON'),			category = _('Electrical Panel')},
	{down = elec_commands.Switch_ENG_START, 		cockpit_device_id = devices.ELECTRIC, value_down = 0,	name = _('Engine Start OFF'),			category = _('Electrical Panel')},
	{down = elec_commands.Switch_APU_GEN, 			cockpit_device_id = devices.ELECTRIC, value_down = 1,	name = _('APU Generator Switch RESET'),	category = _('Electrical Panel')},
	{down = elec_commands.Switch_APU_GEN, 			cockpit_device_id = devices.ELECTRIC, value_down = 0.5,	name = _('APU Generator Switch ON'),	category = _('Electrical Panel')},
	{down = elec_commands.Switch_APU_GEN, 			cockpit_device_id = devices.ELECTRIC, value_down = 0,	name = _('APU Generator Switch OFF'),	category = _('Electrical Panel')},
	{down = elec_commands.Switch_DC_TEST, 			cockpit_device_id = devices.ELECTRIC, value_down = 1,	name = _('DC Test Switch STBY'),		category = _('Electrical Panel')},
	{down = elec_commands.Switch_DC_TEST, 			cockpit_device_id = devices.ELECTRIC, value_down = 0.5,	name = _('DC Test Switch OFF'),			category = _('Electrical Panel')},
	{down = elec_commands.Switch_DC_TEST, 			cockpit_device_id = devices.ELECTRIC, value_down = 0,	name = _('DC Test Switch MAIN'),		category = _('Electrical Panel')},
	
	-- Pilot & Seat Controls 
	{down = iCommandToggleMirrors,												name = _('Mirrors TOGGLE'),									category = _('Pilot & Seat Controls')},
    {down = iCommandPlaneEject,													name = _('Eject (3 times)'),								category = _('Pilot & Seat Controls')},	
	{down = iCommandCockpitShowPilotOnOff,										name = _('Hide/Show Pilot Body'),							category = _('Pilot & Seat Controls')},
	{down = iCommandPlaneCircuitBreaker_10,										name = _('Hide/Show Stick and Throttle'),					category = _('Pilot & Seat Controls')},	
	{down = iCommandViewNightVisionGogglesOn,									name = _('Helmet Visor/NVG Toggle'),						category = _('Pilot & Seat Controls')},
	{down = iCommandPlaneModeFI0,												name = _('Switch the Helmet Visor for NVG and viceversa'),	category = _('Pilot & Seat Controls')},
	{down = iCommandPlane_Helmet_Brightess_Up,									name = _('NVG Brightness Up'),								category = _('Pilot & Seat Controls')},
	{down = iCommandPlane_Helmet_Brightess_Down,								name = _('NVG Brightness Down'),							category = _('Pilot & Seat Controls')},
	{down =  msc_commands.Seat_SFTY_LVR_TOGGLE,									cockpit_device_id = devices.MSC,	value_down = 0,						name = _("Seat Ground Safety Lever"),						category = _('Pilot & Seat Controls')},
	{down =  msc_commands.Seat_SFTY_LVR,										cockpit_device_id = devices.MSC,	value_down = 0,						name = _("Seat Ground Safety Lever Up"),					category = _('Pilot & Seat Controls')},
	{down =  msc_commands.Seat_SFTY_LVR,										cockpit_device_id = devices.MSC,	value_down = 1,						name = _("Seat Ground Safety Lever Down"),					category = _('Pilot & Seat Controls')},
	{down =  msc_commands.Switch_SEAT_ADJ, up =  msc_commands.Switch_SEAT_ADJ,	cockpit_device_id = devices.MSC,	value_down = 1,		value_up = 0,	name = _("Seat Adjustment Switch Up"),						category = _('Pilot & Seat Controls')},
	{down =  msc_commands.Switch_SEAT_ADJ, up =  msc_commands.Switch_SEAT_ADJ,	cockpit_device_id = devices.MSC,	value_down = -1,	value_up = 0,	name = _("Seat Adjustment Switch Down"),					category = _('Pilot & Seat Controls')},

	-- HOTAS
	-- Stick
	{down = iCommandPlaneFire,         up = iCommandPlaneFireOff,   name = _('Trigger: Fire Gun/Launch Sidewinder, Sidearm'),     		category = _('HOTAS')},
	{down = iCommandPlanePickleOn,     up = iCommandPlanePickleOff, name = _('Bomb Pickle: Release Bombs/Launch Rockets, Mavericks'),	category = _('HOTAS')},
	{down = iCommandPlane_HOTAS_BoatSwitchForward,                  name = _('A/A Mode FWD: Sidewinder (Boresight)'),					category = _('HOTAS')},
	{down = iCommandPlane_HOTAS_BoatSwitchAft,                      name = _('A/A Mode AFT: Sidewinder (SEAM)'),						category = _('HOTAS')},
	{down = iCommandPlane_HOTAS_BoatSwitchCenter,                   name = _('A/A Mode DOWN: Gun'),										category = _('HOTAS')},
	
	{pressed = iCommandPlaneTrimUp,    up = iCommandPlaneTrimStop,  name = _('Trim Pitch DOWN'),						category = _('HOTAS')},
	{pressed = iCommandPlaneTrimDown,  up = iCommandPlaneTrimStop,  name = _('Trim Pitch UP'),							category = _('HOTAS')},
	{pressed = iCommandPlaneTrimLeft,  up = iCommandPlaneTrimStop,  name = _('Trim Bank LEFT'),							category = _('HOTAS')},
	{pressed = iCommandPlaneTrimRight, up = iCommandPlaneTrimStop,  name = _('Trim Bank RIGHT'),						category = _('HOTAS')},
	
	{down = iCommandPlane_HOTAS_PinkySwitchForward,			up = iCommandPlane_HOTAS_PinkySwitchCenter,															name = _('WP Increment'),								category = _('HOTAS')},
	{down = iCommandPlaneAutopilotOverrideOn,				up = iCommandPlaneAutopilotOverrideOff,																name = _('Emergency SAAHS Disconnect'),					category = _('HOTAS')},
	{down = iCommandPlane_HOTAS_NoseWheelSteeringButton,	up = iCommandPlane_HOTAS_NoseWheelSteeringButtonOff,												name = _('AG Target Undesignate / NWS / FOV Toggle'),	category = _('HOTAS')},
	{down = hotas_commands.SSS_FWD,							up = hotas_commands.SSS_FWD,	cockpit_device_id = devices.MSC,	value_down = 1,	value_up = 0,	name = _('Sensor Select FWD: INS, IRMV/EOMV'),  		category = _('HOTAS')},
	{down = hotas_commands.SSS_AFT,							up = hotas_commands.SSS_AFT,	cockpit_device_id = devices.MSC,	value_down = 1,	value_up = 0,	name = _('Sensor Select AFT: DMT: LST/TV'),  			category = _('HOTAS')},
	{down = hotas_commands.SSS_LEFT,						up = hotas_commands.SSS_LEFT,	cockpit_device_id = devices.MSC,	value_down = 1,	value_up = 0,	name = _('Sensor Select LEFT: MAP Center/Decenter'),	category = _('HOTAS')},
	{down = hotas_commands.SSS_RIGHT,						up = hotas_commands.SSS_RIGHT,	cockpit_device_id = devices.MSC,	value_down = 1,	value_up = 0,	name = _('Sensor Select RIGHT: FLIR BH/WH'),			category = _('HOTAS')},
	{down = hotas_commands.SSS_CENTER,						up = hotas_commands.SSS_CENTER,	cockpit_device_id = devices.MSC,	value_down = 1,	value_up = 0,	name = _('Sensor Select DOWN: HUD Scene Reject/TGP'),	category = _('HOTAS')},
	
	-- Throttle
	{down = iCommandPlaneDropChaffOnce,						name = _('ECM Dispense AFT: Chaff'),		category = _('HOTAS')},
	{down = iCommandPlaneDropFlareOnce,						name = _('ECM Dispense FWD: Flares'),		category = _('HOTAS')},
	{down = iCommandPlaneCMDDispenceOff,					name = _('ECM Dispense RIGHT: All'),		category = _('HOTAS')},
	{down = iCommandPlaneCMDDispence,						name = _('ECM Dispense LEFT: Mini Jammer'),	category = _('HOTAS')},
	
	{down = iCommandPlane_ABRIS_Axis_Push,					name = _('Cage/Uncage'),					category = _('HOTAS')},
	
	{down = iCommandPlane_HOTAS_CMS_Up,	up = iCommandPlane_HOTAS_CMS_Left,  name = _('Engine Air Start'),				category = _('HOTAS')},
	{down = iCommandPlane_HOTAS_CMS_Down, up = iCommandPlane_HOTAS_CMS_Off, name = _('Emergency Flap Retraction'),		category = _('HOTAS')},
	
	{down = iCommandPlane_HOTAS_MIC_SwitchUp,				name = _('COMM FWD: Select COMM 1'),		category = _('HOTAS')},
	{down = iCommandPlane_HOTAS_MIC_SwitchDown,				name = _('COMM AFT: Select COMM 2'),		category = _('HOTAS')},
	-- Missing COMM CENTER
	
	{down = iCommandPlaneAirBrake,							                        name = _('Airbrake TOGGLE'),		category = _('HOTAS')},
	{pressed = iCommandPlaneAirBrakeOn, up = iCommandHelicopter_PPR_button_K_up,	name = _('Airbrake OUT'),			category = _('HOTAS')},
	{pressed = iCommandPlaneAirBrakeOff, up = iCommandHelicopter_PPR_button_K_up,	name = _('Airbrake IN'),			category = _('HOTAS')},
	
	{pressed = iCommandPlane_HOTAS_CoolieUp,				up = iCommandPlane_HOTAS_CoolieOff, 		name = _('TDC Forward'),					category = _('HOTAS')},
	{pressed = iCommandPlane_HOTAS_CoolieDown,  			up = iCommandPlane_HOTAS_CoolieOff, 		name = _('TDC Aft'),						category = _('HOTAS')},
	{pressed = iCommandPlane_HOTAS_CoolieLeft,  			up = iCommandPlane_HOTAS_CoolieOff, 		name = _('TDC Left'),						category = _('HOTAS')},
	{pressed = iCommandPlane_HOTAS_CoolieRight, 			up = iCommandPlane_HOTAS_CoolieOff, 		name = _('TDC Right'),						category = _('HOTAS')},
	{down = iCommandPlane_HOTAS_TDC_depress_on,				up = iCommandPlane_HOTAS_TDC_depress_off,	name = _('TDC Down (Action Position)'),		category = _('HOTAS')},
	{down = iCommandPlane_HOTAS_TriggerSecondStage_Off,													name = _('TDC Action/No Action Toggle'),	category = _('HOTAS')},
	
	{down = engine_commands.Handle_THROTTLE_CUTOFF,			up = engine_commands.Handle_THROTTLE_CUTOFF,
	 cockpit_device_id = devices.DECS, value_down = 1, value_up = 0, name = _('Throttle Cutoff'),     category = _('HOTAS')},
	
	-- Left MPCD
	{down = mpcd_l_commands.Button_01 , up = mpcd_l_commands.Button_01,  cockpit_device_id = devices.MPCD_LEFT, value_down = 1, value_up = 0,	name = _('Left MPCD OSB 01'), category = _('Left MPCD')},
	{down = mpcd_l_commands.Button_02 , up = mpcd_l_commands.Button_02,  cockpit_device_id = devices.MPCD_LEFT, value_down = 1, value_up = 0,	name = _('Left MPCD OSB 02'), category = _('Left MPCD')},
	{down = mpcd_l_commands.Button_03 , up = mpcd_l_commands.Button_03,  cockpit_device_id = devices.MPCD_LEFT, value_down = 1, value_up = 0,	name = _('Left MPCD OSB 03'), category = _('Left MPCD')},
	{down = mpcd_l_commands.Button_04 , up = mpcd_l_commands.Button_04,  cockpit_device_id = devices.MPCD_LEFT, value_down = 1, value_up = 0,	name = _('Left MPCD OSB 04'), category = _('Left MPCD')},
	{down = mpcd_l_commands.Button_05 , up = mpcd_l_commands.Button_05,  cockpit_device_id = devices.MPCD_LEFT, value_down = 1, value_up = 0,	name = _('Left MPCD OSB 05'), category = _('Left MPCD')},
	{down = mpcd_l_commands.Button_06 , up = mpcd_l_commands.Button_06,  cockpit_device_id = devices.MPCD_LEFT, value_down = 1, value_up = 0,	name = _('Left MPCD OSB 06'), category = _('Left MPCD')},
	{down = mpcd_l_commands.Button_07 , up = mpcd_l_commands.Button_07,  cockpit_device_id = devices.MPCD_LEFT, value_down = 1, value_up = 0,	name = _('Left MPCD OSB 07'), category = _('Left MPCD')},
	{down = mpcd_l_commands.Button_08 , up = mpcd_l_commands.Button_08,  cockpit_device_id = devices.MPCD_LEFT, value_down = 1, value_up = 0,	name = _('Left MPCD OSB 08'), category = _('Left MPCD')},
	{down = mpcd_l_commands.Button_09 , up = mpcd_l_commands.Button_09,  cockpit_device_id = devices.MPCD_LEFT, value_down = 1, value_up = 0,	name = _('Left MPCD OSB 09'), category = _('Left MPCD')},
	{down = mpcd_l_commands.Button_10 , up = mpcd_l_commands.Button_10,  cockpit_device_id = devices.MPCD_LEFT, value_down = 1, value_up = 0,	name = _('Left MPCD OSB 10'), category = _('Left MPCD')},
	{down = mpcd_l_commands.Button_11 , up = mpcd_l_commands.Button_11,  cockpit_device_id = devices.MPCD_LEFT, value_down = 1, value_up = 0,	name = _('Left MPCD OSB 11'), category = _('Left MPCD')},
	{down = mpcd_l_commands.Button_12 , up = mpcd_l_commands.Button_12,  cockpit_device_id = devices.MPCD_LEFT, value_down = 1, value_up = 0,	name = _('Left MPCD OSB 12'), category = _('Left MPCD')},
	{down = mpcd_l_commands.Button_13 , up = mpcd_l_commands.Button_13,  cockpit_device_id = devices.MPCD_LEFT, value_down = 1, value_up = 0,	name = _('Left MPCD OSB 13'), category = _('Left MPCD')},
	{down = mpcd_l_commands.Button_14 , up = mpcd_l_commands.Button_14,  cockpit_device_id = devices.MPCD_LEFT, value_down = 1, value_up = 0,	name = _('Left MPCD OSB 14'), category = _('Left MPCD')},
	{down = mpcd_l_commands.Button_15 , up = mpcd_l_commands.Button_15,  cockpit_device_id = devices.MPCD_LEFT, value_down = 1, value_up = 0,	name = _('Left MPCD OSB 15'), category = _('Left MPCD')},
	{down = mpcd_l_commands.Button_16 , up = mpcd_l_commands.Button_16,  cockpit_device_id = devices.MPCD_LEFT, value_down = 1, value_up = 0,	name = _('Left MPCD OSB 16'), category = _('Left MPCD')},
	{down = mpcd_l_commands.Button_17 , up = mpcd_l_commands.Button_17,  cockpit_device_id = devices.MPCD_LEFT, value_down = 1, value_up = 0,	name = _('Left MPCD OSB 17'), category = _('Left MPCD')},
	{down = mpcd_l_commands.Button_18 , up = mpcd_l_commands.Button_18,  cockpit_device_id = devices.MPCD_LEFT, value_down = 1, value_up = 0,	name = _('Left MPCD OSB 18'), category = _('Left MPCD')},
	{down = mpcd_l_commands.Button_19 , up = mpcd_l_commands.Button_19,  cockpit_device_id = devices.MPCD_LEFT, value_down = 1, value_up = 0,	name = _('Left MPCD OSB 19'), category = _('Left MPCD')},
	{down = mpcd_l_commands.Button_20 , up = mpcd_l_commands.Button_20,  cockpit_device_id = devices.MPCD_LEFT, value_down = 1, value_up = 0,	name = _('Left MPCD OSB 20'), category = _('Left MPCD')},
	
	{pressed = iCommandPlaneLeftMFD_BRT_Increase,	up = iCommandPlaneLeftMFD_BRT_Stop,		name = _('Left MPCD BRT Increase'),		category = _('Left MPCD')},
	{pressed = iCommandPlaneLeftMFD_BRT_Decrease,	up = iCommandPlaneLeftMFD_BRT_Stop,		name = _('Left MPCD BRT Decrease'),		category = _('Left MPCD')},
	{down = mpcd_l_commands.Switch_NGT_MODE,	up = mpcd_l_commands.Switch_NGT_MODE,	cockpit_device_id = devices.MPCD_LEFT,	value_down =  1,	value_up = 0,	name = _('Left MPCD Night Mode'),		category = _('Left MPCD')},
	{down = mpcd_l_commands.Switch_DAY_MODE,	up = mpcd_l_commands.Switch_DAY_MODE,	cockpit_device_id = devices.MPCD_LEFT,	value_down = -1,	value_up = 0,	name = _('Left MPCD Day Mode'),			category = _('Left MPCD')},
	{down = mpcd_l_commands.Switch_SYM_UP,		up = mpcd_l_commands.Switch_SYM_UP,		cockpit_device_id = devices.MPCD_LEFT,	value_down =  1,	value_up = 0,	name = _('Left MPCD SYM Increase'),		category = _('Left MPCD')},
	{down = mpcd_l_commands.Switch_SYM_DN,		up = mpcd_l_commands.Switch_SYM_DN,		cockpit_device_id = devices.MPCD_LEFT,	value_down = -1,	value_up = 0,	name = _('Left MPCD SYM Decrease'),		category = _('Left MPCD')},
	{down = mpcd_l_commands.Switch_CONT_UP,		up = mpcd_l_commands.Switch_CONT_UP,	cockpit_device_id = devices.MPCD_LEFT,	value_down =  1,	value_up = 0,	name = _('Left MPCD CON Increase'),		category = _('Left MPCD')},
	{down = mpcd_l_commands.Switch_CONT_DN,		up = mpcd_l_commands.Switch_CONT_DN,	cockpit_device_id = devices.MPCD_LEFT,	value_down = -1,	value_up = 0,	name = _('Left MPCD CON Decrease'),		category = _('Left MPCD')},
	{down = mpcd_l_commands.Switch_GAIN_UP,		up = mpcd_l_commands.Switch_GAIN_UP,	cockpit_device_id = devices.MPCD_LEFT,	value_down =  1,	value_up = 0,	name = _('Left MPCD GAIN Increase'),	category = _('Left MPCD')},
	{down = mpcd_l_commands.Switch_GAIN_DN,		up = mpcd_l_commands.Switch_GAIN_DN,	cockpit_device_id = devices.MPCD_LEFT,	value_down = -1,	value_up = 0,	name = _('Left MPCD GAIN Decrease'),	category = _('Left MPCD')},
	
	{down = iCommand_UV26_PowerCover,													name = _('Left MPCD Export View ON/OFF'),	category = _('Left MPCD')},
	
	-- Right MPCD
	{down = mpcd_r_commands.Button_01 , up = mpcd_r_commands.Button_01,  cockpit_device_id = devices.MPCD_RIGHT, value_down = 1, value_up = 0,	name = _('Right MPCD OSB 01'), category = _('Right MPCD')},
	{down = mpcd_r_commands.Button_02 , up = mpcd_r_commands.Button_02,  cockpit_device_id = devices.MPCD_RIGHT, value_down = 1, value_up = 0,	name = _('Right MPCD OSB 02'), category = _('Right MPCD')},
	{down = mpcd_r_commands.Button_03 , up = mpcd_r_commands.Button_03,  cockpit_device_id = devices.MPCD_RIGHT, value_down = 1, value_up = 0,	name = _('Right MPCD OSB 03'), category = _('Right MPCD')},
	{down = mpcd_r_commands.Button_04 , up = mpcd_r_commands.Button_04,  cockpit_device_id = devices.MPCD_RIGHT, value_down = 1, value_up = 0,	name = _('Right MPCD OSB 04'), category = _('Right MPCD')},
	{down = mpcd_r_commands.Button_05 , up = mpcd_r_commands.Button_05,  cockpit_device_id = devices.MPCD_RIGHT, value_down = 1, value_up = 0,	name = _('Right MPCD OSB 05'), category = _('Right MPCD')},
	{down = mpcd_r_commands.Button_06 , up = mpcd_r_commands.Button_06,  cockpit_device_id = devices.MPCD_RIGHT, value_down = 1, value_up = 0,	name = _('Right MPCD OSB 06'), category = _('Right MPCD')},
	{down = mpcd_r_commands.Button_07 , up = mpcd_r_commands.Button_07,  cockpit_device_id = devices.MPCD_RIGHT, value_down = 1, value_up = 0,	name = _('Right MPCD OSB 07'), category = _('Right MPCD')},
	{down = mpcd_r_commands.Button_08 , up = mpcd_r_commands.Button_08,  cockpit_device_id = devices.MPCD_RIGHT, value_down = 1, value_up = 0,	name = _('Right MPCD OSB 08'), category = _('Right MPCD')},
	{down = mpcd_r_commands.Button_09 , up = mpcd_r_commands.Button_09,  cockpit_device_id = devices.MPCD_RIGHT, value_down = 1, value_up = 0,	name = _('Right MPCD OSB 09'), category = _('Right MPCD')},
	{down = mpcd_r_commands.Button_10 , up = mpcd_r_commands.Button_10,  cockpit_device_id = devices.MPCD_RIGHT, value_down = 1, value_up = 0,	name = _('Right MPCD OSB 10'), category = _('Right MPCD')},
	{down = mpcd_r_commands.Button_11 , up = mpcd_r_commands.Button_11,  cockpit_device_id = devices.MPCD_RIGHT, value_down = 1, value_up = 0,	name = _('Right MPCD OSB 11'), category = _('Right MPCD')},
	{down = mpcd_r_commands.Button_12 , up = mpcd_r_commands.Button_12,  cockpit_device_id = devices.MPCD_RIGHT, value_down = 1, value_up = 0,	name = _('Right MPCD OSB 12'), category = _('Right MPCD')},
	{down = mpcd_r_commands.Button_13 , up = mpcd_r_commands.Button_13,  cockpit_device_id = devices.MPCD_RIGHT, value_down = 1, value_up = 0,	name = _('Right MPCD OSB 13'), category = _('Right MPCD')},
	{down = mpcd_r_commands.Button_14 , up = mpcd_r_commands.Button_14,  cockpit_device_id = devices.MPCD_RIGHT, value_down = 1, value_up = 0,	name = _('Right MPCD OSB 14'), category = _('Right MPCD')},
	{down = mpcd_r_commands.Button_15 , up = mpcd_r_commands.Button_15,  cockpit_device_id = devices.MPCD_RIGHT, value_down = 1, value_up = 0,	name = _('Right MPCD OSB 15'), category = _('Right MPCD')},
	{down = mpcd_r_commands.Button_16 , up = mpcd_r_commands.Button_16,  cockpit_device_id = devices.MPCD_RIGHT, value_down = 1, value_up = 0,	name = _('Right MPCD OSB 16'), category = _('Right MPCD')},
	{down = mpcd_r_commands.Button_17 , up = mpcd_r_commands.Button_17,  cockpit_device_id = devices.MPCD_RIGHT, value_down = 1, value_up = 0,	name = _('Right MPCD OSB 17'), category = _('Right MPCD')},
	{down = mpcd_r_commands.Button_18 , up = mpcd_r_commands.Button_18,  cockpit_device_id = devices.MPCD_RIGHT, value_down = 1, value_up = 0,	name = _('Right MPCD OSB 18'), category = _('Right MPCD')},
	{down = mpcd_r_commands.Button_19 , up = mpcd_r_commands.Button_19,  cockpit_device_id = devices.MPCD_RIGHT, value_down = 1, value_up = 0,	name = _('Right MPCD OSB 19'), category = _('Right MPCD')},
	{down = mpcd_r_commands.Button_20 , up = mpcd_r_commands.Button_20,  cockpit_device_id = devices.MPCD_RIGHT, value_down = 1, value_up = 0,	name = _('Right MPCD OSB 20'), category = _('Right MPCD')},
	
	{pressed = iCommandPlaneRightMFD_BRT_Increase,	up = iCommandPlaneRightMFD_BRT_Stop,	name = _('Right MPCD BRT Increase'),	category = _('Right MPCD')},
	{pressed = iCommandPlaneRightMFD_BRT_Decrease,	up = iCommandPlaneRightMFD_BRT_Stop,	name = _('Right MPCD BRT Decrease'),	category = _('Right MPCD')},
	{down = mpcd_r_commands.Switch_NGT_MODE,	up = mpcd_r_commands.Switch_NGT_MODE,	cockpit_device_id = devices.MPCD_RIGHT,	value_down =  1,	value_up = 0,	name = _('Right MPCD Night Mode'),		category = _('Right MPCD')},
	{down = mpcd_r_commands.Switch_DAY_MODE,	up = mpcd_r_commands.Switch_DAY_MODE,	cockpit_device_id = devices.MPCD_RIGHT,	value_down = -1,	value_up = 0,	name = _('Right MPCD Day Mode'),		category = _('Right MPCD')},
	{down = mpcd_r_commands.Switch_SYM_UP,		up = mpcd_r_commands.Switch_SYM_UP,		cockpit_device_id = devices.MPCD_RIGHT, value_down =  1,	value_up = 0,	name = _('Right MPCD SYM Increase'),	category = _('Right MPCD')},
	{down = mpcd_r_commands.Switch_SYM_DN,		up = mpcd_r_commands.Switch_SYM_DN,		cockpit_device_id = devices.MPCD_RIGHT, value_down = -1,	value_up = 0,	name = _('Right MPCD SYM Decrease'),	category = _('Right MPCD')},
	{down = mpcd_r_commands.Switch_CONT_UP,		up = mpcd_r_commands.Switch_CONT_UP,	cockpit_device_id = devices.MPCD_RIGHT, value_down =  1,	value_up = 0,	name = _('Right MPCD CON Increase'),	category = _('Right MPCD')},
	{down = mpcd_r_commands.Switch_CONT_DN,		up = mpcd_r_commands.Switch_CONT_DN,	cockpit_device_id = devices.MPCD_RIGHT, value_down = -1,	value_up = 0,	name = _('Right MPCD CON Decrease'),	category = _('Right MPCD')},
	{down = mpcd_r_commands.Switch_GAIN_UP,		up = mpcd_r_commands.Switch_GAIN_UP,	cockpit_device_id = devices.MPCD_RIGHT, value_down =  1,	value_up = 0,	name = _('Right MPCD GAIN Increase'),	category = _('Right MPCD')},
	{down = mpcd_r_commands.Switch_GAIN_DN,		up = mpcd_r_commands.Switch_GAIN_DN,	cockpit_device_id = devices.MPCD_RIGHT, value_down = -1,	value_up = 0,	name = _('Right MPCD GAIN Decrease'),	category = _('Right MPCD')},
	
	{down = iCommand_UV26_BITCover,															name = _('Right MPCD Export View ON/OFF'),	category = _('Right MPCD')},
	
	-- ARMAMENT CONTROL PANEL
	{down = iCommandSwitchMasterArm,															name = _('Master Arm Switch Toggle'),	category = _('Armament Control')},
	{pressed = iCommandPlaneCMDChangeBurstAmount,	up = iCommandPlaneCMDChangeBurstAmountOff,	name = _('Launch Flare Salvo'),			category = _('Armament Control')},
	
	{down = smc_commands.Switch_ARMT,		up = smc_commands.Switch_ARMT,		cockpit_device_id = devices.SMC,	value_down =  1, 	value_up = 0, 	name = _('Armament Mode Control Up'),				category = _('Armament Control')},
	{down = smc_commands.Switch_ARMT,		up = smc_commands.Switch_ARMT,		cockpit_device_id = devices.SMC,	value_down = -1, 	value_up = 0, 	name = _('Armament Mode Control Down'),				category = _('Armament Control')},
	{down = smc_commands.Switch_FUZE,		up = smc_commands.Switch_FUZE,		cockpit_device_id = devices.SMC,	value_down =  1, 	value_up = 0, 	name = _('Weapons Fuze Control Up'),				category = _('Armament Control')},
	{down = smc_commands.Switch_FUZE,		up = smc_commands.Switch_FUZE,		cockpit_device_id = devices.SMC,	value_down = -1, 	value_up = 0, 	name = _('Weapons Fuze Control Down'),				category = _('Armament Control')},
	{down = smc_commands.Switch_QTY_10,		up = smc_commands.Switch_QTY_10,	cockpit_device_id = devices.SMC,	value_down =  1, 	value_up = 0, 	name = _('Release Quantity (10s) Control Up'),		category = _('Armament Control')},
	{down = smc_commands.Switch_QTY_10,		up = smc_commands.Switch_QTY_10,	cockpit_device_id = devices.SMC,	value_down = -1, 	value_up = 0, 	name = _('Release Quantity (10s) Control Down'),	category = _('Armament Control')},
	{down = smc_commands.Switch_QTY_01,		up = smc_commands.Switch_QTY_01,	cockpit_device_id = devices.SMC,	value_down =  1, 	value_up = 0, 	name = _('Release Quantity (1s) Control Up'),		category = _('Armament Control')},
	{down = smc_commands.Switch_QTY_01,		up = smc_commands.Switch_QTY_01,	cockpit_device_id = devices.SMC,	value_down = -1, 	value_up = 0, 	name = _('Release Quantity (1s) Control Down'),		category = _('Armament Control')},
	{down = smc_commands.Switch_MULT,		up = smc_commands.Switch_MULT,		cockpit_device_id = devices.SMC,	value_down =  1, 	value_up = 0, 	name = _('Multiple Release Control Up'),			category = _('Armament Control')},
	{down = smc_commands.Switch_MULT,		up = smc_commands.Switch_MULT,		cockpit_device_id = devices.SMC,	value_down = -1, 	value_up = 0, 	name = _('Multiple Release Control Down'),			category = _('Armament Control')},
	{down = smc_commands.Switch_INTV_100,	up = smc_commands.Switch_INTV_100,	cockpit_device_id = devices.SMC,	value_down =  1, 	value_up = 0, 	name = _('Release Interval (100s) Control Up'),		category = _('Armament Control')},
	{down = smc_commands.Switch_INTV_100,	up = smc_commands.Switch_INTV_100,	cockpit_device_id = devices.SMC,	value_down = -1, 	value_up = 0, 	name = _('Release Interval (100s) Control Down'),	category = _('Armament Control')},
	{down = smc_commands.Switch_INTV_010,	up = smc_commands.Switch_INTV_010,	cockpit_device_id = devices.SMC,	value_down =  1, 	value_up = 0, 	name = _('Release Interval (10s) Control Up'),		category = _('Armament Control')},
	{down = smc_commands.Switch_INTV_010,	up = smc_commands.Switch_INTV_010,	cockpit_device_id = devices.SMC,	value_down = -1, 	value_up = 0, 	name = _('Release Interval (10s) Control Down'),	category = _('Armament Control')},
	{down = smc_commands.Switch_INTV_001,	up = smc_commands.Switch_INTV_001,	cockpit_device_id = devices.SMC,	value_down =  1, 	value_up = 0, 	name = _('Release Interval (1s) Control Up'),		category = _('Armament Control')},
	{down = smc_commands.Switch_INTV_001,	up = smc_commands.Switch_INTV_001,	cockpit_device_id = devices.SMC,	value_down = -1, 	value_up = 0, 	name = _('Release Interval (1s) Control Down'),		category = _('Armament Control')},
	{down = smc_commands.Button_JETT,		up = smc_commands.Button_JETT,		cockpit_device_id = devices.SMC,	value_down =  1, 	value_up = 0, 	name = _('Jettison Pushbutton'),					category = _('Armament Control')},
	{down = smc_commands.Button_1,			up = smc_commands.Button_1,			cockpit_device_id = devices.SMC,	value_down =  1, 	value_up = 0, 	name = _('Station 1 Pushbutton'),					category = _('Armament Control')},
	{down = smc_commands.Button_2,			up = smc_commands.Button_2,			cockpit_device_id = devices.SMC,	value_down =  1, 	value_up = 0, 	name = _('Station 2 Pushbutton'),					category = _('Armament Control')},
	{down = smc_commands.Button_3,			up = smc_commands.Button_3,			cockpit_device_id = devices.SMC,	value_down =  1, 	value_up = 0, 	name = _('Station 3 Pushbutton'),					category = _('Armament Control')},
	{down = smc_commands.Button_4,			up = smc_commands.Button_4,			cockpit_device_id = devices.SMC,	value_down =  1, 	value_up = 0, 	name = _('Station 4 Pushbutton'),					category = _('Armament Control')},
	{down = smc_commands.Button_5,			up = smc_commands.Button_5,			cockpit_device_id = devices.SMC,	value_down =  1, 	value_up = 0, 	name = _('Station 5 Pushbutton'),					category = _('Armament Control')},
	{down = smc_commands.Button_6,			up = smc_commands.Button_6,			cockpit_device_id = devices.SMC,	value_down =  1, 	value_up = 0, 	name = _('Station 6 Pushbutton'),					category = _('Armament Control')},
	{down = smc_commands.Button_7,			up = smc_commands.Button_7,			cockpit_device_id = devices.SMC,	value_down =  1, 	value_up = 0, 	name = _('Station 7 Pushbutton'),					category = _('Armament Control')},
	{down = smc_commands.Switch_IR_COOL,	up = smc_commands.Switch_IR_COOL,	cockpit_device_id = devices.SMC,	value_down =  1, 	value_up = 0, 	name = _('IR Cooling control'),						category = _('Armament Control')},
	{down = iCommandPlaneCDU_R,						name = _('Manual Release Control CCW'),			category = _('Armament Control')},
	{down = iCommandPlaneCDU_Q,						name = _('Manual Release Control CW'),			category = _('Armament Control')},
	{down = iCommandPlaneCDU_T,						name = _('Selective Jettison Selector CCW'),	category = _('Armament Control')},
	{down = iCommandPlaneCDU_S,						name = _('Selective Jettison Selector CW'),		category = _('Armament Control')},
	
	{down = smc_commands.Switch_IR_COOL,		cockpit_device_id = devices.SMC, value_down = 1,	name = _("Ground IR Cooling ON"),			category = _('Armament Control')},
	{down = smc_commands.Switch_IR_COOL,		cockpit_device_id = devices.SMC, value_down = 0,	name = _("Ground IR Cooling OFF"),			category = _('Armament Control')},
	{down = smc_commands.Switch_IR_COOL_TOGGLE, cockpit_device_id = devices.SMC, value_down = 0,	name = _("Ground IR Cooling Toggle"),		category = _('Armament Control')},
	
	{down = iCommandPlaneJettisonFuelTanks,															name = _('Emergency Jettison Pushbutton'),	category = _('Armament Control')},
	{down = iCommandPlaneWingtipSmokeOnOff,															name = _('Smoke'),							category = _('Armament Control')}, 
	
	{down = smc_commands.Switch_Master_Arm,	cockpit_device_id = devices.SMC,	value_down = 1,		name = _('Master Arm Switch ON'),			category = _('Armament Control')},
	{down = smc_commands.Switch_Master_Arm,	cockpit_device_id = devices.SMC,	value_down = 0,		name = _('Master Arm Switch OFF'),			category = _('Armament Control')},
	{down = smc_commands.Knob_Bomb_Fuze,	cockpit_device_id = devices.SMC,	value_down = 0.0, 	name = _('WPN MAN CONTROL : NORM'),			category = _('Armament Control')},
	{down = smc_commands.Knob_Bomb_Fuze,	cockpit_device_id = devices.SMC,	value_down = 0.33, 	name = _('WPN MAN CONTROL : N/T'),			category = _('Armament Control')},
	{down = smc_commands.Knob_Bomb_Fuze,	cockpit_device_id = devices.SMC,	value_down = 0.66, 	name = _('WPN MAN CONTROL : N'),			category = _('Armament Control')},
	{down = smc_commands.Knob_Bomb_Fuze,	cockpit_device_id = devices.SMC,	value_down = 0.99, 	name = _('WPN MAN CONTROL : T'),			category = _('Armament Control')},
	{down = smc_commands.Knob_JETT,			cockpit_device_id = devices.SMC,	value_down = -1.0, 	name = _('Jettison Mode Selector : STA'),	category = _('Armament Control')},
	{down = smc_commands.Knob_JETT,			cockpit_device_id = devices.SMC,	value_down = -0.5, 	name = _('Jettison Mode Selector : STOR'),	category = _('Armament Control')},
	{down = smc_commands.Knob_JETT,			cockpit_device_id = devices.SMC,	value_down = 0.0, 	name = _('Jettison Mode Selector : SAFE'),	category = _('Armament Control')},
	{down = smc_commands.Knob_JETT,			cockpit_device_id = devices.SMC,	value_down = 0.5, 	name = _('Jettison Mode Selector : CMBT'),	category = _('Armament Control')},
	{down = smc_commands.Knob_JETT,			cockpit_device_id = devices.SMC,	value_down = 1.0, 	name = _('Jettison Mode Selector : FUEL'),	category = _('Armament Control')},
    
	-- UFC
	{down = ufc_commands.Button_1,			up = ufc_commands.Button_1,			cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC 1 Button'),								category = _('Up Front Control')},
	{down = ufc_commands.Button_2,			up = ufc_commands.Button_2,			cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC 2/N Button'),								category = _('Up Front Control')},
	{down = ufc_commands.Button_3,			up = ufc_commands.Button_3,			cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC 3 Button'),								category = _('Up Front Control')},
	{down = ufc_commands.Button_4,			up = ufc_commands.Button_4,			cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC 4/W Button'),								category = _('Up Front Control')},
	{down = ufc_commands.Button_5,			up = ufc_commands.Button_5,			cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC 5 Button'),								category = _('Up Front Control')},
	{down = ufc_commands.Button_6,			up = ufc_commands.Button_6,			cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC 6/E Button'),								category = _('Up Front Control')},
	{down = ufc_commands.Button_7,			up = ufc_commands.Button_7,			cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC 7 Button'),								category = _('Up Front Control')},
	{down = ufc_commands.Button_8,			up = ufc_commands.Button_8,			cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC 8/S Button'),								category = _('Up Front Control')},
	{down = ufc_commands.Button_9,			up = ufc_commands.Button_9,			cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC 9 Button'),								category = _('Up Front Control')},
	{down = ufc_commands.Button_0,			up = ufc_commands.Button_0,			cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC 0 Button'),								category = _('Up Front Control')},
	{down = ufc_commands.Button_Dot,		up = ufc_commands.Button_Dot,		cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC . Button'),								category = _('Up Front Control')},
	{down = ufc_commands.Button_Dash,		up = ufc_commands.Button_Dash,		cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC - Button'),								category = _('Up Front Control')},
	
	{down = ufc_commands.Button_TMR,		up = ufc_commands.Button_TMR,		cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC Timer Function Button'),					category = _('Up Front Control')},
	{down = ufc_commands.Button_TOO,		up = ufc_commands.Button_TOO,		cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC Target-Of-Opportunity Function Button'),	category = _('Up Front Control')},
	{down = ufc_commands.Button_CLR,		up = ufc_commands.Button_CLR,		cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC Clear Button'),							category = _('Up Front Control')},
	{down = ufc_commands.Button_SVE,		up = ufc_commands.Button_SVE,		cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC Save Button'),							category = _('Up Front Control')},
	{down = ufc_commands.Button_ENT,		up = ufc_commands.Button_ENT,		cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC Enter Button'),							category = _('Up Front Control')},
	{down = ufc_commands.Button_ON_OFF,		up = ufc_commands.Button_ON_OFF,	cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC ON/OFF Toggle Button'),					category = _('Up Front Control')},
	{down = ufc_commands.Button_IFF,		up = ufc_commands.Button_IFF,		cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC IFF Function Button'),					category = _('Up Front Control')},
	{down = ufc_commands.Button_TCN,		up = ufc_commands.Button_TCN,		cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC TACAN Function Button'),					category = _('Up Front Control')},
	{down = ufc_commands.Button_AWL,		up = ufc_commands.Button_AWL,		cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC AWLS Function Button'),					category = _('Up Front Control')},
	{down = ufc_commands.Button_WPN,		up = ufc_commands.Button_WPN,		cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC Weapons Function Button'),				category = _('Up Front Control')},
	{down = ufc_commands.Button_WOF,		up = ufc_commands.Button_WOF,		cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC Wpt Over Fly Function Button'),			category = _('Up Front Control')},
	{down = ufc_commands.Button_BCN,		up = ufc_commands.Button_BCN,		cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC RDR Beacon Function Button'),				category = _('Up Front Control')},
	{down = ufc_commands.Button_ALT,		up = ufc_commands.Button_ALT,		cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC Altimeter Function Button'),				category = _('Up Front Control')},
	{down = ufc_commands.Button_EMCON,		up = ufc_commands.Button_EMCON,		cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0, name = _('UFC EMCON Toggle Button'),					category = _('Up Front Control')},
	{down = ufc_commands.Button_IP, 		up = ufc_commands.Button_IP,		cockpit_device_id = devices.UFCCONTROL,	value_down = 1.0,	value_up = 0.0,	name = _('UFC I/P Button'),								category = _('Up Front Control')},
	{pressed = iCommandPlaneUFC_INTEN_INCREASE, 																											name = _('UFC Display Brightness Increase'),			category = _('Up Front Control')},
	{pressed = iCommandPlaneUFC_INTEN_DECREASE, 																											name = _('UFC Display Brightness Decrease'),			category = _('Up Front Control')},
	
	-- ODU
	{down = odu_commands.Button_1,			up = odu_commands.Button_1,			cockpit_device_id = devices.ODUCONTROL,	value_down = 1.0,	value_up = 0.0,	name = _('ODU Option 1'),	category = _('Up Front Control')},
	{down = odu_commands.Button_2,			up = odu_commands.Button_2, 		cockpit_device_id = devices.ODUCONTROL,	value_down = 1.0,	value_up = 0.0,	name = _('ODU Option 2'),	category = _('Up Front Control')},
	{down = odu_commands.Button_3,			up = odu_commands.Button_3, 		cockpit_device_id = devices.ODUCONTROL,	value_down = 1.0,	value_up = 0.0,	name = _('ODU Option 3'),	category = _('Up Front Control')},
	{down = odu_commands.Button_4,			up = odu_commands.Button_4, 		cockpit_device_id = devices.ODUCONTROL,	value_down = 1.0,	value_up = 0.0,	name = _('ODU Option 4'),	category = _('Up Front Control')},
	{down = odu_commands.Button_5,			up = odu_commands.Button_5, 		cockpit_device_id = devices.ODUCONTROL,	value_down = 1.0,	value_up = 0.0,	name = _('ODU Option 5'),	category = _('Up Front Control')},
	
	-- Communications
	{pressed = iCommandPlane_VHF_FM_Volume_Dec, 														name = _('UHF Radio 1 Volume Decrease'),				category = _('Radios Control')},
	{pressed = iCommandPlane_VHF_FM_Volume_Inc, 														name = _('UHF Radio 1 Volume Increase'),				category = _('Radios Control')},
	{down = iCommandPlane_VHF_FM_FreqMode_OFF,															name = _('UHF Radio 1 Selector'),						category = _('Radios Control')},
	{down = iCommandPlane_VHF_FM_Preset_Dec, 															name = _('UHF Radio 1 Preset Channel Decrease'),		category = _('Radios Control')},
	{down = iCommandPlane_VHF_FM_Preset_Inc, 															name = _('UHF Radio 1 Preset Channel Increase'),		category = _('Radios Control')},
	
	{pressed = iCommandPlane_VHF_AM_Volume_Dec, 														name = _('UHF Radio 2 Volume Decrease'),				category = _('Radios Control')},
	{pressed = iCommandPlane_VHF_AM_Volume_Inc, 														name = _('UHF Radio 2 Volume Increase'),				category = _('Radios Control')},
	{down = iCommandPlane_VHF_AM_FreqMode_OFF,															name = _('UHF Radio 2 Selector'),						category = _('Radios Control')},
	{down = iCommandPlane_VHF_AM_Preset_Dec, 															name = _('UHF Radio 2 Preset Channel Decrease'),		category = _('Radios Control')},
	{down = iCommandPlane_VHF_AM_Preset_Inc, 															name = _('UHF Radio 2 Preset Channel Increase'),		category = _('Radios Control')},
	
	{down = iCommandPlaneIntercomHM, 																	name = _('UHF Radio Control Selector (UFC/RCU-8150)'),	category = _('Radios Control')},
	{down = iCommandPlaneIntercomVHF, 																	name = _('UHF RCU-8150 Radio Selector (COM1/COM2)'),	category = _('Radios Control')},

	{down = iCommandPlaneUHFPresetChannelSelectorInc, 													name = _('UHF RCU-8150 Chan/Freq Knob CW'),				category = _('Radios Control')},
	{down = iCommandPlaneUHFPresetChannelSelectorDec, 													name = _('UHF RCU-8150 Chan/Freq Knob CCW'),			category = _('Radios Control')},
	{pressed = iCommandPlaneUHFVolumeInc, 																name = _('UHF RCU-8150 Volume Increase'),				category = _('Radios Control')},
	{pressed = iCommandPlaneUHFVolumeDec, 																name = _('UHF RCU-8150 Volume Decrease'),				category = _('Radios Control')},
	{down = radio_commands.Switch_OP_MODE,		cockpit_device_id = devices.RSC,	value_down = 0.00, 	name = _('UHF RCU-8150 Operational Mode: OFF'),			category = _('Radios Control')},
	{down = radio_commands.Switch_OP_MODE,		cockpit_device_id = devices.RSC,	value_down = 0.20, 	name = _('UHF RCU-8150 Operational Mode: TEST'),		category = _('Radios Control')},
	{down = radio_commands.Switch_OP_MODE,		cockpit_device_id = devices.RSC,	value_down = 0.40, 	name = _('UHF RCU-8150 Operational Mode: TR+G'),		category = _('Radios Control')},
	{down = radio_commands.Switch_OP_MODE,		cockpit_device_id = devices.RSC,	value_down = 0.60, 	name = _('UHF RCU-8150 Operational Mode: TR'),			category = _('Radios Control')},
	{down = radio_commands.Switch_OP_MODE,		cockpit_device_id = devices.RSC,	value_down = 0.80, 	name = _('UHF RCU-8150 Operational Mode: ADF'),			category = _('Radios Control')},
	{down = radio_commands.Switch_OP_MODE,		cockpit_device_id = devices.RSC,	value_down = 1.00, 	name = _('UHF RCU-8150 Operational Mode: CHNG PRST'),	category = _('Radios Control')},
	{down = radio_commands.Switch_FREQ_MODE,	cockpit_device_id = devices.RSC,	value_down = 0.15, 	name = _('UHF RCU-8150 Frequency Mode: AJ'),			category = _('Radios Control')},
	{down = radio_commands.Switch_FREQ_MODE,	cockpit_device_id = devices.RSC,	value_down = 0.30, 	name = _('UHF RCU-8150 Frequency Mode: MAR'),			category = _('Radios Control')},
	{down = radio_commands.Switch_FREQ_MODE,	cockpit_device_id = devices.RSC,	value_down = 0.45, 	name = _('UHF RCU-8150 Frequency Mode: PRST'),			category = _('Radios Control')},
	{down = radio_commands.Switch_FREQ_MODE,	cockpit_device_id = devices.RSC,	value_down = 0.60, 	name = _('UHF RCU-8150 Frequency Mode: MAN'),			category = _('Radios Control')},
	{down = radio_commands.Switch_FREQ_MODE,	cockpit_device_id = devices.RSC,	value_down = 0.75, 	name = _('UHF RCU-8150 Frequency Mode: 243'),			category = _('Radios Control')},
	{down = radio_commands.Switch_FREQ_MODE,	cockpit_device_id = devices.RSC,	value_down = 0.90, 	name = _('UHF RCU-8150 Frequency Mode: AJ/M'),			category = _('Radios Control')},
	{down = radio_commands.Switch_FREQ_MODE,	cockpit_device_id = devices.RSC,	value_down = 0.00, 	name = _('UHF RCU-8150 Frequency Mode: 121'),			category = _('Radios Control')},
	{down = iCommandPlaneUHFFunctionDialMAIN, 															name = _('UHF RCU-8150 Ancillary Mode Pointer'),		category = _('Radios Control')},
	{down = iCommandPlaneUHFFunctionDialBOTH, 															name = _('UHF RCU-8150 Ancillary Mode Switch'),			category = _('Radios Control')},
	{down = iCommandPlaneUHFFreqModeDialMNL, 	up = iCommandPlaneUHFFunctionDialOFF,					name = _('UHF RCU-8150 LOAD/OFST Switch'),				category = _('Radios Control')},
	
	-- MISCELLANEOUS PANEL
	{down = iCommandAltimeterPressureIncrease,	up = iCommandAltimeterPressureStop,	name = _('Barometric Altimeter Pressure Calibration Increase'),	category = _('Miscellaneous Controls')},
	{down = iCommandAltimeterPressureDecrease,	up = iCommandAltimeterPressureStop,	name = _('Barometric Altimeter Pressure Calibration Decrease'),	category = _('Miscellaneous Controls')},
	{down = iCommandPlaneNightTVOnOff,												name = _('DMT On/Off Toggle'),									category = _('Miscellaneous Controls')},
	{down = iCommandPlaneRadarOnOff,												name = _('FLIR Power Switch ON/OFF'),							category = _('Miscellaneous Controls')},
	{down = iCommandPlaneRadarUp,													name = _('Mission Computer Mode Up (OFF - AUTO - OVRD)'),		category = _('Miscellaneous Controls')},
	{down = iCommandPlaneRadarDown,													name = _('Mission Computer Mode Down (OVRD - AUTO  - OFF)'),	category = _('Miscellaneous Controls')},
	{down = iCommandPlaneCMSC_PRI,													name = _('Stopwatch Start/Stop toggle'),						category = _('Miscellaneous Controls')},
	{down = iCommandPlaneCMSC_SEP,													name = _('Stopwatch Lap/Reset toggle'),							category = _('Miscellaneous Controls')},
	{down = misc_commands.Switch_FLIR_Power, 		cockpit_device_id = devices.NAVFLIR,			value_down = 1.0,	name = _('FLIR Power Switch ON'),			category = _('Miscellaneous Controls')},
	{down = misc_commands.Switch_FLIR_Power, 		cockpit_device_id = devices.NAVFLIR,			value_down = 0.0,	name = _('FLIR Power Switch OFF'),			category = _('Miscellaneous Controls')},
	{down = misc_commands.Switch_DMT_Power, 		cockpit_device_id = devices.DMT,				value_down = 1.0,	name = _('DMT Switch ON'),					category = _('Miscellaneous Controls')},
	{down = misc_commands.Switch_DMT_Power, 		cockpit_device_id = devices.DMT,				value_down = 0.0,	name = _('DMT Switch OFF'),					category = _('Miscellaneous Controls')}, 
	{down = misc_commands.Switch_DP_Mode,			cockpit_device_id = devices.MSC,				value_down = 1.0,	name = _('DISPLAY PROCESSOR Mode PRIM'),	category = _('Miscellaneous Controls')},
	{down = misc_commands.Switch_DP_Mode,			cockpit_device_id = devices.MSC,				value_down = 0.5,	name = _('DISPLAY PROCESSOR Mode AUTO'),	category = _('Miscellaneous Controls')},              
	{down = misc_commands.Switch_DP_Mode,			cockpit_device_id = devices.MSC,				value_down = 0.0,	name = _('DISPLAY PROCESSOR Mode ALTER'),	category = _('Miscellaneous Controls')},
	{down = misc_commands.Switch_VRS_Mode,			cockpit_device_id = devices.NAVFLIR,			value_down = 0.0,	name = _('VRS MODE SWITCH AUTO'),			category = _('Miscellaneous Controls')},
	{down = misc_commands.Switch_VRS_Mode,			cockpit_device_id = devices.NAVFLIR,			value_down = 1.0,	name = _('VRS MODE SWITCH RUN'),			category = _('Miscellaneous Controls')},
	{down = misc_commands.Switch_MC_Power,			cockpit_device_id = devices.MSC,				value_down = 1.0,	name = _('Mission Computer Mode OVRD'),		category = _('Miscellaneous Controls')},
	{down = misc_commands.Switch_MC_Power,			cockpit_device_id = devices.MSC,				value_down = 0.5,	name = _('Mission Computer Mode AUTO'), 	category = _('Miscellaneous Controls')},              
	{down = misc_commands.Switch_MC_Power,			cockpit_device_id = devices.MSC,				value_down = 0.0,	name = _('Mission Computer Mode OFF'),		category = _('Miscellaneous Controls')},
	{down = misc_commands.Switch_PR_HT_Mode,		cockpit_device_id = devices.FLIGHTINSTRUMENTS,	value_down = 1.0,	name = _('PRB HEAT HT'),					category = _('Miscellaneous Controls')},
	{down = misc_commands.Switch_PR_HT_Mode,		cockpit_device_id = devices.FLIGHTINSTRUMENTS,	value_down = 0.0,	name = _('PRB HEAT AUTO'),					category = _('Miscellaneous Controls')},
	{down = misc_commands.Switch_VRS_Output,		cockpit_device_id = devices.NAVFLIR,			value_down = 1.0,	name = _('VRS DISPLAY SELECTOR HUD'),		category = _('Miscellaneous Controls')},
	{down = misc_commands.Switch_VRS_Output,		cockpit_device_id = devices.NAVFLIR,			value_down = 0.0,	name = _('VRS DISPLAY SELECTOR MPCD'),		category = _('Miscellaneous Controls')},
	
	-- Navigation Panel	
	{pressed = iCommandHSI_CourseRotaryLeft,	up = iCommandHSI_Test_up,	name = _('COURSE Selector CCW'),	category = _('Navigation Control')},
	{pressed = iCommandHSI_CourseRotaryRight,	up = iCommandHSI_Test_up,	name = _('COURSE Selector CW'),		category = _('Navigation Control')},
	{down = iCommandPlaneNavChangePanelModeLeft,							name = _('INS Mode Selector CCW'),	category = _('Navigation Control')},
	{down = iCommandPlaneNavChangePanelModeRight,							name = _('INS Mode Selector CW'),	category = _('Navigation Control')},
	--
	{down = misc_commands.Knob_INS_Mode,									cockpit_device_id = devices.NAV_INS,	value_down =  0.0, 					name = _('INS Mode: OFF'),			category = _('Navigation Control')},
	{down = misc_commands.Knob_INS_Mode,									cockpit_device_id = devices.NAV_INS,	value_down =  0.1, 					name = _('INS Mode: SEA ALIGN'),	category = _('Navigation Control')},
	{down = misc_commands.Knob_INS_Mode,									cockpit_device_id = devices.NAV_INS,	value_down =  0.2, 					name = _('INS Mode: GND ALIGN'),	category = _('Navigation Control')},
	{down = misc_commands.Knob_INS_Mode,									cockpit_device_id = devices.NAV_INS,	value_down =  0.3, 					name = _('INS Mode: NAV'),			category = _('Navigation Control')},
	{down = misc_commands.Knob_INS_Mode,									cockpit_device_id = devices.NAV_INS,	value_down =  0.4, 					name = _('INS Mode: IFA'),			category = _('Navigation Control')},
	{down = misc_commands.Knob_INS_Mode,									cockpit_device_id = devices.NAV_INS,	value_down =  0.5, 					name = _('INS Mode: GYRO'),			category = _('Navigation Control')},
	
	-- IFF
	{down = acnip_commands.Switch_IFF_CRYPTO,					cockpit_device_id = devices.ACNIP,	value_down = -1.0,	name = _('IFF Crypto Switch: HOLD'),	category = _('IFF')},
	{down = acnip_commands.Switch_IFF_CRYPTO,					cockpit_device_id = devices.ACNIP,	value_down =  0.0,	name = _('IFF Crypto Switch: NORM'),	category = _('IFF')},
	{down = acnip_commands.Switch_IFF_CRYPTO,					cockpit_device_id = devices.ACNIP,	value_down =  1.0,	name = _('IFF Crypto Switch: ZERO'),	category = _('IFF')},
	
	-- INTERNAL LIGHTS
	{down = iCommandPlaneMasterCaution,                                          name = _('Master Warning/Caution Reset'),       category = _('Internal Lights')},
	{down = wc_lights_commands.Switch_Master_Caution,		cockpit_device_id = devices.LTWCA, value_down = 1.0, name = _('Master Caution'),				category = _('Internal Lights')},
	{down = wc_lights_commands.Switch_Master_Warning,   cockpit_device_id = devices.LTWCA, value_down = 1.0, name = _('Master Warning'),       category = _('Internal Lights')},
	{down = int_light_commands.Switch_Compass_Light_Test,		cockpit_device_id = devices.LTINT,	value_down = 0.0,	name = _('Compass Light/Test COMP'),					category = _('Internal Lights')},
	{down = int_light_commands.Switch_Compass_Light_Test,		cockpit_device_id = devices.LTINT,	value_down = 1.0,	name = _('Compass Light/Test TEST'),					category = _('Internal Lights')},
	{down = int_light_commands.Switch_Compass_Light_Test,		cockpit_device_id = devices.LTINT,	value_down = 0.5,	name = _('Compass Light/Test OFF'),						category = _('Internal Lights')},
	{down = int_light_commands.Knob_Instr_Lights,       cockpit_device_id = devices.LTINT, value_down = 0.1, name = _("Instrument Lights Increase"), category = _('Internal Lights')},
  {down = int_light_commands.Knob_Instr_Lights,       cockpit_device_id = devices.LTINT, value_down = -0.1, name = _("Instrument Lights Decrease"), category = _('Internal Lights')},
  {down = int_light_commands.Knob_Console_Lights,     cockpit_device_id = devices.LTINT, value_down = 0.1, name = _("Console Lights Increase"), category = _('Internal Lights')},
  {down = int_light_commands.Knob_Console_Lights,     cockpit_device_id = devices.LTINT, value_down = -0.1, name = _("Console Lights Decrease"), category = _('Internal Lights')},  
  {down = int_light_commands.Knob_Flood_Lights,       cockpit_device_id = devices.LTINT, value_down = 0.1, name = _("Flood Lights Increase"), category = _('Internal Lights')},
  {down = int_light_commands.Knob_Flood_Lights,       cockpit_device_id = devices.LTINT, value_down = -0.1, name = _("Flood Lights Decrease"), category = _('Internal Lights')},
  {down = int_light_commands.Knob_Annunciator_Lights, cockpit_device_id = devices.LTINT, value_down = 0.1, name = _("Annunciator Lights Increase"), category = _('Internal Lights')},
  {down = int_light_commands.Knob_Annunciator_Lights, cockpit_device_id = devices.LTINT, value_down = -0.1, name = _("Annunciator Lights Decrease"), category = _('Internal Lights')},  
	
	--EXTERNAL LIGHTS
	{down = iCommandPlaneLightsOnOff,																					name = _('Exterior Lights ALL Toggle ON/OFF'),			category = _('Exterior Lights')},
	{down = iCommandPlaneNavLights_CodeModeOn,																			name = _('Exterior Lights SW OFF-NVG-NORM'),			category = _('Exterior Lights')},
	{down = iCommandPlaneNavLights_CodeModeOff,																			name = _('Exterior Lights SW NORM-NVG-OFF'),			category = _('Exterior Lights')},
	{pressed = iCommandPlaneFormationLightsIncrease,																	name = _('Formation Lights Knob Brightness Increase'),	category = _('Exterior Lights')},
	{pressed = iCommandPlaneFormationLightsDecrease,																	name = _('Formation Lights Knob Brightness Decrease'),	category = _('Exterior Lights')},
	{down = iCommandPlanePositionLightsSteady,																			name = _('Position Lights SW OFF-DIM-BRT'),				category = _('Exterior Lights')},
	{down = iCommandPlanePositionLightsOff,																				name = _('Position Lights SW BRT-DIM-OFF'),				category = _('Exterior Lights')},
	{down = iCommandPlaneAntiCollisionLights,																			name = _('Anti-Collision Lights SW Toggle ON/OFF'),		category = _('Exterior Lights')},
	{down = iCommandPlaneLGPTaxiLight,																					name = _('Auxiliary (Taxi) Light Toggle'),				category = _('Exterior Lights')},
	{down = iCommandPlaneLGPLandLight,																					name = _('Landing Light SW Up (OFF-HVR-APP)'),			category = _('Exterior Lights')},
	{down = iCommandPlaneLGPLightsOff,																					name = _('Landing Light SW Down (APP-HVR-OFF)'),		category = _('Exterior Lights')},
	{down = iCommandPlaneRotorTipLights,															value_down = 1,		name = _('Air Refueling Probe Light ON'),				category = _('Exterior Lights')},
	{down = iCommandPlaneRotorTipLights,															value_down = 0,		name = _('Air Refueling Probe Light OFF'),				category = _('Exterior Lights')},
	{down = ext_light_commands.AR_PROBE_LT_TOGGLE,				cockpit_device_id = devices.LTEXT,	value_down = 0,		name = _('Air Refueling Probe Light SW TOGGLE'),		category = _('Exterior Lights')},
	{down = ext_light_commands.Switch_ANTI_COLL_LT,				cockpit_device_id = devices.LTEXT,	value_down = 1,		name = _('Anti Collision Lights ON'),					category = _('Exterior Lights')},
	{down = ext_light_commands.Switch_ANTI_COLL_LT,				cockpit_device_id = devices.LTEXT,	value_down = 0,		name = _('Anti Collision Lights OFF'),					category = _('Exterior Lights')},
	{down = ext_light_commands.Switch_AUX_LT,					cockpit_device_id = devices.LTEXT,	value_down = 1,		name = _('Auxiliary (Taxi) Light ON'),					category = _('Exterior Lights')},
	{down = ext_light_commands.Switch_AUX_LT,					cockpit_device_id = devices.LTEXT,	value_down = 0,		name = _('Auxiliary (Taxi) Light OFF'),					category = _('Exterior Lights')},
	{down = ext_light_commands.Switch_EXT_LT_NORM_TOGGLE,		cockpit_device_id = devices.LTEXT,	value_down = 0,		name = _('Exterior Lights SW Toggle NORM/OFF'),			category = _('Exterior Lights')}, 
	{down = ext_light_commands.Switch_EXT_LT_NVG_TOGGLE,		cockpit_device_id = devices.LTEXT,	value_down = 0,		name = _('Exterior Lights SW Toggle NVG/OFF'),			category = _('Exterior Lights')},
	{down = ext_light_commands.Switch_EXT_LT_NORM,				cockpit_device_id = devices.LTEXT,	value_down = 0,		name = _('Exterior Lights NORM Mode'),					category = _('Exterior Lights')}, 
	{down = ext_light_commands.Switch_EXT_LT_NVG,				cockpit_device_id = devices.LTEXT,	value_down = 0,		name = _('Exterior Lights NVG Mode'),					category = _('Exterior Lights')},
	{down = ext_light_commands.Switch_LANDING_LT,				cockpit_device_id = devices.LTEXT,	value_down = 0.5,	name = _('Landing Light HVR'),							category = _('Exterior Lights')},
	{down = ext_light_commands.Switch_LANDING_LT,				cockpit_device_id = devices.LTEXT,	value_down = 1.0,	name = _('Landing Light APP'),							category = _('Exterior Lights')},
	{down = ext_light_commands.Switch_LANDING_LT,				cockpit_device_id = devices.LTEXT,	value_down = 0,		name = _('Landing Light OFF'),							category = _('Exterior Lights')},
	{down = ext_light_commands.Switch_LANDING_LT_APP_TOGGLE,	cockpit_device_id = devices.LTEXT,	value_down = 0,		name = _('Landing Light APP/OFF'),						category = _('Exterior Lights')},
	{down = ext_light_commands.Switch_LANDING_LT_HVR_TOGGLE,	cockpit_device_id = devices.LTEXT,	value_down = 0,		name = _('Landing Light HVR/OFF'),						category = _('Exterior Lights')},
	{down = ext_light_commands.Switch_POS_LT,					cockpit_device_id = devices.LTEXT,	value_down = 0,		name = _('Position Lights OFF'),						category = _('Exterior Lights')},
	{down = ext_light_commands.Switch_POS_LT,					cockpit_device_id = devices.LTEXT,	value_down = 0.5,	name = _('Position Lights DIM'),						category = _('Exterior Lights')},
	{down = ext_light_commands.Switch_POS_LT,					cockpit_device_id = devices.LTEXT,	value_down = 1.0,	name = _('Position Lights BRT'),						category = _('Exterior Lights')},
	{down = ext_light_commands.Switch_EXT_LT_NORM_NVG,			cockpit_device_id = devices.LTEXT,	value_down = 0,		name = _('Exterior Lights SW OFF'),						category = _('Exterior Lights')},
	{down = ext_light_commands.Switch_EXT_LT_NORM_NVG,			cockpit_device_id = devices.LTEXT,	value_down = 0.5,	name = _('Exterior Lights SW NVG'),						category = _('Exterior Lights')},
	{down = ext_light_commands.Switch_EXT_LT_NORM_NVG,			cockpit_device_id = devices.LTEXT,	value_down = 1.0,	name = _('Exterior Lights SW NORM'),					category = _('Exterior Lights')},
	
	-- Ground Adjustment (Kneeboard)
	{down = iCommandPlaneCircuitBreaker_21,		value_down = 1,	name = _('Change Top Front Left ECM Dispenser Load (Chaff/Flares)'),	category = {_('Ground Adjustments')}},
	{down = iCommandPlaneCircuitBreaker_22,		value_down = 1,	name = _('Change Top Front Right ECM Dispenser Load (Chaff/Flares)'),	category = {_('Ground Adjustments')}},
	{down = iCommandPlaneCircuitBreaker_23,		value_down = 1,	name = _('Change Top Rear Left ECM Dispenser Load (Chaff/Flares)'),		category = {_('Ground Adjustments')}},
	{down = iCommandPlaneCircuitBreaker_24,		value_down = 1,	name = _('Change Top Rear Right ECM Dispenser Load (Chaff/Flares)'),	category = {_('Ground Adjustments')}},
	{down = iCommandPlaneCircuitBreaker_25,		value_down = 1,	name = _('Change Bottom Left ECM Dispenser Load (Chaff/Flares)'),		category = {_('Ground Adjustments')}},
	{down = iCommandPlaneCircuitBreaker_26,		value_down = 1,	name = _('Change Bottom Right ECM Dispenser Load (Chaff/Flares)'),		category = {_('Ground Adjustments')}},
	{down = iCommandPlaneCircuitBreaker_29,		value_down = 1,	name = _('AN/AVS-9 NVG Case (Load/Unload)'),							category = {_('Ground Adjustments')}},
	{down = iCommandPlaneCircuitBreaker_30,		value_down = 1,	name = _('Change FF Rocket Fire Mode (Single/Ripple)'),					category = {_('Ground Adjustments')}},
	{down = iCommandPlane_HARS_SyncButton,		value_down = 1,	name = _('Check MAP for Target Locations'),								category = {_('Ground Adjustments')}},
	{down = iCommandPlane_SPU9_radio_change,	value_down = 1,	name = _('Change Mission Route Map Page'),								category = {_('Ground Adjustments')}},
	{down = iCommandPlaneCircuitBreaker_31,		value_down = 1,	name = _('Change APKWS Laser Code X100'),								category = {_('Ground Adjustments')}},
	{down = iCommandPlaneCircuitBreaker_32,		value_down = 1,	name = _('Change APKWS Laser Code X010'),								category = {_('Ground Adjustments')}},
	{down = iCommandPlaneCircuitBreaker_33,		value_down = 1,	name = _('Change APKWS Laser Code X001'),								category = {_('Ground Adjustments')}},
	{down = iCommandPlaneCircuitBreaker_34,		value_down = 1,	name = _('Change GBU-12/16 Laser Code X100'),							category = {_('Ground Adjustments')}},
	{down = iCommandPlaneCircuitBreaker_35,		value_down = 1,	name = _('Change GBU-12/16 Laser Code X010'),							category = {_('Ground Adjustments')}},
	{down = iCommandPlaneCircuitBreaker_36,		value_down = 1,	name = _('Change GBU-12/16 Laser Code X001'),							category = {_('Ground Adjustments')}},
	
	-- Cheat
	{down = iCommandEnginesStart,				name = _('Start Procedure'),		category = _('Keyboard Macros')},
    {down = iCommandEnginesStop,				name = _('Stop Procedure'),			category = _('Keyboard Macros')},
	{pressed = iCommandPlane_AAP_SteerSw_Up,	name = _('TPOD Video Zoom In'),		category = _('Keyboard Macros')},
    {pressed = iCommandPlane_AAP_SteerSw_Down,	name = _('TPOD Video Zoom Out'),	category = _('Keyboard Macros')},
	
	-- DEBUG
	{down = iCommandEasyRadarScaleUp,	up = iCommandRALT_Test_up,	name = _('AOA Indicator Up'),	category = _('DEBUG')},
	{down = iCommandEasyRadarScaleOut,	up = iCommandRALT_Test_up,	name = _('AOA Indicator Down'),	category = _('DEBUG')},
	{down = iCommandPlaneNav_DLK_OnOff,								name = _('Data Parameters'),	category = _('DEBUG')},
	
	}
)

join(res.axisCommands,{

{combos = defaultDeviceAssignmentFor("roll")  ,  action = iCommandPlaneRoll		   , name = _('Roll')},
{combos = defaultDeviceAssignmentFor("pitch") ,  action = iCommandPlanePitch	   , name = _('Pitch')},
{combos = defaultDeviceAssignmentFor("rudder"),  action = iCommandPlaneRudder	   , name = _('Rudder')},
{combos = defaultDeviceAssignmentFor("thrust"),  action = iCommandPlaneThrustCommon, name = _('Thrust')},
{action = iCommandPlaneCollective,  name = _('Nozzle Angle')},
{action = iCommandWheelBrake,		name = _('Wheel Brakes')},
{action = iCommandLeftWheelBrake,	name = _('Wheel Brake Left')},
{action = iCommandRightWheelBrake,	name = _('Wheel Brake Right')},
{action = iCommandPlaneThrustRight,	name = _('Nozzle STO Stop')},
{action = ext_light_commands.Knob_FORM_LT, cockpit_device_id = devices.LTEXT, name = _('Formation Lights Knob Axis')},
{action = hud_commands.DisplayBRTKnob, cockpit_device_id = devices.HUDCONTROL, name = _('HUD BRT CONTROL')},
{action = hud_commands.VideoBRTKnob, cockpit_device_id = devices.HUDCONTROL, name = _('VIDEO BRT CONTROL')},
{action = hud_commands.VideoCONTKnob, cockpit_device_id = devices.HUDCONTROL, name = _('VIDEO CONT CONTROL')},
{action = edp_commands.BRT_Knob, cockpit_device_id = devices.EDP, name = _('EDP BRT CONTROL')},
{action = int_light_commands.Knob_Instr_Lights, cockpit_device_id = devices.LTINT, name = _('INST PANEL LIGHTS BRT')},
{action = int_light_commands.Knob_Console_Lights, cockpit_device_id = devices.LTINT, name = _('CONSOLE LIGHTS BRT')},
{action = int_light_commands.Knob_Flood_Lights, cockpit_device_id = devices.LTINT, name = _('FLOOD LIGHTS BRT CONTROL')},
{action = int_light_commands.Knob_Annunciator_Lights, cockpit_device_id = devices.LTINT, name = _('WARN/CAUT ANNUNC BRT CONTROL')},
{action = rwr_commands.Knob_RWR, cockpit_device_id = devices.RWRCONTROL, name = _('RWR VOL CONTROL')},
{action = acnip_commands.Knob_AUX_VOL, cockpit_device_id = devices.INTERCOM, name = _('ICS Aux Volume Knob')},
{action = ecs_commands.Knob_TEMP, cockpit_device_id = devices.ECS, name = _('ECS TEMP CONTROL')},
{action = ufc_commands.Knob_BRT, cockpit_device_id = devices.UFCCONTROL, name = _('UFC Display Brightness Control')},
{action = ufc_commands.Knob_Comm1_Vol, cockpit_device_id = devices.UFCCONTROL, name = _('Comm 1 Volume Control')},
{action = ufc_commands.Knob_Comm2_Vol, cockpit_device_id = devices.UFCCONTROL, name = _('Comm 2 Volume Control')},

--HOTAS TDC
{action = iCommandPlaneSelecterHorizontalAbs, name = _('TDC Slew Horizontal')},
{action = iCommandPlaneSelecterVerticalAbs	, name = _('TDC Slew Vertical')},

}) 


return res