function add_path(txt, tbl)
	new_tbl = {}
	for k,v in pairs(tbl) do
		new_tbl[#new_tbl + 1] = txt..v
	end
	return new_tbl
end

AISounds = 
{
	path_pref_eng = "Speech/ENG/Mi-24P/",
	path_pref_rus = "Speech/RUS/Mi-24P/",
	path_pilot = "Petrovich_Pilot/",
	path_op = "Petrovich_CPG/",
	extension = ".ogg",
	
	pilot_sounds = 
	{
		"t180",
		"Aligining",
		"Break_Left",
		"Break_Right",
		"Decreasing_Alt",
		"Increase_Alt",
		"Left",
		"Direction",
		"Move_Back",
		"Move_Forward",
		"Right",
		"Slide_Left",
		"Slide_Right",
		"Slow_Down",
		"Speed_Up",
		"Stopping",
		"Coming_Up",
		"Coming_Down",
		"open_menu",
		"close_menu",
	},
	
	cpg_sounds = 
	{
		"c_range_neg",
		"c_range_closer",
		"shturm",
		"ataka",
		"ataka_he",
		"ataka_220",
		"observ_on",
		"observ_off",
		"searching",
		"eng_at_will",
		"eng_hold_fire",
		"target_destroyed",
		"good_effects",
		"firing",
		"wpn_turning_on",
		"wpn_ready",
		"aso_int4",
		"aso_int2",
		"aso_series4",
		"aso_series16",
		"aso_side_left",
		"aso_side_right",
		"aso_side_both",
		"aso_payload_chaff",
		"aso_payload_flares",
		"open_menu",
		"close_menu",
		"in_range",
		"out_of_chaff",
		"out_of_flares",
		"target_acq",
		"inc_gunfire_1",
		"inc_gunfire_2",
		"inc_gunfire_3",
		"inc_gunfire_9",
		"inc_gunfire_10",
		"inc_gunfire_11",
		"inc_gunfire_12",
		"inc_gunfire_right",
		"inc_gunfire_left",
		"inc_missile_1",
		"inc_missile_2",
		"inc_missile_3",
		"inc_missile_9",
		"inc_missile_10",
		"inc_missile_11",
		"inc_missile_12",
		"inc_missile_right",
		"inc_missile_left",
	},
	
	pilot_files_eng =
	{
		t180			= {"Breaking 180", "Breaking 180 2"},
		Aligining		= {"Aligning", "Aligning 2", "Aligning 3"},
		Break_Left		= {"Breaking left", "Breaking left 2"},
		Break_Right		= {"Breaking right", "Breaking right 2"},
		Decreasing_Alt	= {"Copy, decreasing altitude", "Copy, decreasing altitude 2"},
		Increase_Alt	= {"Copy, increasing altitude", "Copy, increasing altitude 2"},
		Left			= {"Turning left", "Turning left 2", "Turning left 3"},
		Direction		= {"Copy, heading to direction", "Copy, heading to direction 2"},
		Move_Back		= {"Moving back", "Moving back 2"},
		Move_Forward	= {"Moving forward", "Moving forward 2"},
		Right			= {"Turning right", "Turning right 2", "Turning right 3"},
		Slide_Left		= {"Sliding left", "Sliding left 2"},
		Slide_Right		= {"Sliding right", "Sliding right 2"},
		Slow_Down		= {"Copy, slowing down", "Copy, slowing down 2"},
		Speed_Up		= {"Copy, speeding up", "Copy, speeding up 2"},
		Stopping		= {"Stopping", "Stopping 2", "Stopping 3"},
		Coming_Up		= {"Copy, coming up", "Copy, coming up 2"},
		Coming_Down		= {"Copy, coming down", "Copy, coming down 2"},
		open_menu		= {"_Start"},
		close_menu		= {"_End"},
	},
	
	cpg_files_eng =
	{
		c_range_neg			= {"Negative, out of range"},
		c_range_closer		= {"Get me closer, out of range"},
		shturm				= {"Shturm"},
		ataka				= {"Ataka"},
		ataka_he			= {"Ataka HE"},
		ataka_220			= {"Ataka 220"},
		observ_on			= {"Observe on, searching", "Observe on, searching...2", "Observe on, searching...3"},
		observ_off			= {"Observe off", "Observe off 2", "Observe off 3"},
		searching			= {"Searching", "Searching 2", "Searching 3"},
		eng_at_will			= {"Engaging at will", "Engaging at will 2", "Engaging at will 3"},
		eng_hold_fire		= {"Roger, Hold fire", "Roger, Hold fire 2", "Roger, Hold fire 3"},
		target_destroyed	= {"Target destroyed", "Target destroyed 2", "Target destroyed 3", "Good effects on target", "Good effects on target 2", "Good effects on target 3"},
		good_effects		= {--[["Good effects on target", "Good effects on target 2", "Good effects on target 3"]]},
		firing				= {"Firing", "Firing 2", "Engaging"},
		wpn_turning_on		= {"Turning on weapons", "Turning on weapons...2"},
		wpn_ready			= {"Weapons ready", "Weapons ready 2"},
		aso_int4			= {"ASO interval 4", "ASO interval 4 2"},
		aso_int2			= {"ASO interval 2", "ASO interval 2 2"},
		aso_series4			= {"ASO series 4", "ASO series 4 2"},
		aso_series16		= {"ASO series 16", "ASO series 16 2"},
		aso_side_left		= {"ASO switched to left side", "ASO switched to left side 2"},
		aso_side_right		= {"ASO switched to right side", "ASO switched to right side 2"},
		aso_side_both		= {"ASO both sides up" ,"ASO both sides up 2"},
		aso_payload_chaff	= {"ASO to Chaff", "ASO to Chaff 2"},
		aso_payload_flares	= {"ASO to Flares", "ASO to Flares 2"},
		open_menu			= {"_Start"},
		close_menu			= {"_End"},
		in_range			= {"In range", "In range 2", "In range 3", "Target in range", "Target in range 2", "Target in range 3"},
		out_of_chaff		= {"Out of Chaff", "Out of Chaff 2", "Out of Chaff 3"},
		out_of_flares		= {"Out of Flares", "Out of Flares 2", "Out of Flares 3"},
		target_acq			= {"Target acquired", "Target acquired 2", "Target acquired 3", "Target in sight", "Target in sight 2", "Target in sight 3", "Tracking target", "Tracking target 2", "Tracking target 3"},
		inc_gunfire_1		= add_path("Incoming/", {"GroundFire_1_oclock", "Hostile_GroundFire_1_oclock", "Incoming_Fire_1_oclock", "GroundFire_Right_1", "GroundFire_Right_2", "Hostile_GroundFire_Right"}),
		inc_gunfire_2		= add_path("Incoming/", {"GroundFire_2_oclock", "Hostile_GroundFire_2_oclock", "Incoming_Fire_2_oclock", "GroundFire_Right_1", "GroundFire_Right_2", "Hostile_GroundFire_Right"}),
		inc_gunfire_3		= add_path("Incoming/", {"GroundFire_3_oclock", "Hostile_GroundFire_3_oclock", "Incoming_Fire_3_oclock", "GroundFire_Right_1", "GroundFire_Right_2", "Hostile_GroundFire_Right"}),
		inc_gunfire_9		= add_path("Incoming/", {"GroundFire_9_oclock", "Hostile_GroundFire_9_oclock", "Incoming_Fire_9_oclock", "GroundFire_Left_1", "GroundFire_Left_2", "Hostile_GroundFire_Left"}),
		inc_gunfire_10		= add_path("Incoming/", {"GroundFire_10_oclock", "Hostile_GroundFire_10_oclock", "Incoming_Fire_10_oclock", "GroundFire_Left_1", "GroundFire_Left_2", "Hostile_GroundFire_Left"}),
		inc_gunfire_11		= add_path("Incoming/", {"GroundFire_11_oclock", "Hostile_GroundFire_11_oclock", "Incoming_Fire_11_oclock", "GroundFire_Left_1", "GroundFire_Left_2", "Hostile_GroundFire_Left"}),
		inc_gunfire_12		= add_path("Incoming/", {"GroundFire_12_oclock", "Hostile_GroundFire_12_oclock", "Incoming_Fire_12_oclock", "Hostile_GroundFire_12_oclock 2", "Hostile_GroundFire_12_oclock 3", "Hostile_GroundFire_12_oclock 4", "Hostile_GroundFire_12_oclock 5"}),
		inc_gunfire_right	= add_path("Incoming/", {"GroundFire_Right_1", "GroundFire_Right_2", "Hostile_GroundFire_Right"}),
		inc_gunfire_left	= add_path("Incoming/", {"GroundFire_Left_1", "GroundFire_Left_2", "Hostile_GroundFire_Left"}),
		inc_missile_1		= add_path("Incoming/", {"Incoming_Missile_1_oclock", "Missile_1_oclock", "Missile_1_oclock 2", "Missile_Launch_1_oclock", "Missile_Launch_1_oclock 2", "Missile_OnUs_1_oclock", "Missile_OnUs_1_oclock 2", "Missile_Right", "Missile_OnUs_Right", "Missile_Launch_Right", "Missile_Launch_Right 2", "Missile_Launch_Right 3"}),
		inc_missile_2		= add_path("Incoming/", {"Incoming_Missile_2_oclock", "Missile_2_oclock", "Missile_2_oclock 2", "Missile_2_oclock 3", "Missile_Launch_2_oclock", "Missile_Launch_2_oclock 2", "Missile_OnUs_2_oclock", "Missile_OnUs_2_oclock 2", "Missile_Right", "Missile_OnUs_Right", "Missile_Launch_Right", "Missile_Launch_Right 2", "Missile_Launch_Right 3"}),
		inc_missile_3		= add_path("Incoming/", {"Incoming_Missile_3_oclock", "Missile_3_oclock", "Missile_3_oclock 2", "Missile_Launch_3_oclock", "Missile_OnUs_3_oclock", "Missile_OnUs_3_oclock 2", "Missile_OnUs_3_oclock 3", "Missile_Right", "Missile_OnUs_Right", "Missile_Launch_Right", "Missile_Launch_Right 2", "Missile_Launch_Right 3"}),
		inc_missile_9		= add_path("Incoming/", {"Missile_9_oclock", "Missile_Launch_9_oclock", "Missile_Launch_9_oclock 2", "Missile_Launch_9_oclock 3", "Missile_OnUs_9_oclock", "Missile_Left", "Missile_OnUs_Left", "Missile_Launch_Left", "Missile_Launch_Left 2", "Missile_Launch_Left 3"}),
		inc_missile_10		= add_path("Incoming/", {"Incoming_Missile_10_oclock", "Missile_10_oclock", "Missile_10_oclock 2", "Missile_Launch_10_oclock", "Missile_Launch_10_oclock 2", "Missile_OnUs_10_oclock", "Missile_OnUs_10_oclock 2", "Missile_Left", "Missile_OnUs_Left", "Missile_Launch_Left", "Missile_Launch_Left 2", "Missile_Launch_Left 3"}),
		inc_missile_11		= add_path("Incoming/", {"Incoming_Missile_11_oclock", "Missile_11_oclock", "Missile_11_oclock 2", "Missile_Launch_11_oclock", "Missile_11_oclock", "Missile_11_oclock 2", "Missile_Launch_11_oclock", "Missile_OnUs_11_oclock", "Missile_OnUs_11_oclock 2", "Missile_OnUs_11_oclock 3", "Missile_Left", "Missile_OnUs_Left", "Missile_Launch_Left", "Missile_Launch_Left 2", "Missile_Launch_Left 3"}),
		inc_missile_12		= add_path("Incoming/", {"Incoming_Missile_12_oclock", "Incoming_Missile_12_oclock 2", "Missile_12_oclock", "Missile_12_oclock 2", "Missile_Launch_12_oclock", "Missile_OnUs_12_oclock", "Missile_OnUs_12_oclock 2", "Missile_OnUs_12_oclock 3"}),
		inc_missile_right	= add_path("Incoming/", {"Missile_Right", "Missile_OnUs_Right", "Missile_Launch_Right", "Missile_Launch_Right 2", "Missile_Launch_Right 3"}),
		inc_missile_left	= add_path("Incoming/", {"Missile_Left", "Missile_OnUs_Left", "Missile_Launch_Left", "Missile_Launch_Left 2", "Missile_Launch_Left 3"}),
	},
	
	pilot_files_rus =
	{
		t180			= {"Breaking 180", "Breaking 180 2"},
		Aligining		= {"Aligning", "Aligning 2"},
		Break_Left		= {"Breaking left", "Breaking left 2"},
		Break_Right		= {"Breaking right", "Breaking right 2"},
		Decreasing_Alt	= {"Copy, decreasing altitude"},
		Increase_Alt	= {"Copy, increasing altitude", "Copy, increasing altitude 2"},
		Left			= {"Turning left"},
		Direction		= {"Copy, heading to direction"},
		Move_Back		= {"Moving back"},
		Move_Forward	= {"Moving forward"},
		Right			= {"Turning right"},
		Slide_Left		= {"Sliding left"},
		Slide_Right		= {"Sliding right"},
		Slow_Down		= {"Copy, slowing down", "Copy, slowing down 2"},
		Speed_Up		= {"Copy, speeding up", "Copy, speeding up 2"},
		Stopping		= {"Stopping", "Stopping 2"},
		Coming_Up		= {"Copy, coming up"},
		Coming_Down		= {"Copy, coming down"},
		open_menu		= {"_Start"},
		close_menu		= {"_End"},
	},
	
	cpg_files_rus =
	{
		c_range_neg			= {"Negative, out of range"},
		c_range_closer		= {"Get me closer, out of range"},
		shturm				= {"Shturm"},
		ataka				= {"Ataka", "Ataka 2", "Ataka 3"},
		ataka_he			= {"Ataka HE"},
		ataka_220			= {"Ataka 220"},
		observ_on			= {"Observe on, searching"},
		observ_off			= {"Observe off"},
		searching			= {"Searching", "Searching 2", "Searching 3"},
		eng_at_will			= {"Engaging at will"},
		eng_hold_fire		= {"Roger, Hold fire"},
		target_destroyed	= {"Target destroyed", "Target destroyed 2", "Good effects on target"},
		good_effects		= {--[["Good effects on target"]]},
		firing				= {"Launch", "Launch 2", "Launch 3"},
		wpn_turning_on		= {"Weapons ready 2"},
		wpn_ready			= {"Weapons ready"},
		aso_int4			= {"ASO interval 4", "ASO interval 4 2", "ASO interval 4 3"},
		aso_int2			= {"ASO interval 2", "ASO interval 2 2", "ASO interval 2 3"},
		aso_series4			= {"ASO series 4", "ASO series 4 2", "ASO series 4 3"},
		aso_series16		= {"ASO series 16", "ASO series 16 2", "ASO series 16 3"},
		aso_side_left		= {"ASO launch from left side", "ASO launch from left side 2"},
		aso_side_right		= {"ASO launch from right side", "ASO launch from right side 2", "ASO launch from right side 3"},
		aso_side_both		= {"ASO launch from both sides", "ASO launch from both sides 2", "ASO launch from both sides 3"},
		aso_payload_chaff	= {"ASO to Chaff", "ASO to Chaff 2", "ASO to Chaff 3"},
		aso_payload_flares	= {"ASO to Flares", "ASO to Flares 2", "ASO to Flares 3"},
		open_menu			= {"_Start"},
		close_menu			= {"_End"},
		in_range			= {"In range", "In range 2", "Target in range", "Target in range 2"},
		out_of_chaff		= {"Out of Chaff", "Out of Chaff 2", "Out of Chaff 3", "Out of Chaff 4"},
		out_of_flares		= {"Out of Flares", "Out of Flares 2"},
		target_acq			= {"Target acquired", "Target acquired 2", "Target in sight", "Tracking target", "Tracking target 2"},
		inc_gunfire_1		= add_path("Incoming/", {"GroundFire_1_oclock", "GroundFire_Right"}),
		inc_gunfire_2		= add_path("Incoming/", {"GroundFire_2_oclock", "GroundFire_Right"}),
		inc_gunfire_3		= add_path("Incoming/", {"GroundFire_3_oclock", "GroundFire_3_oclock 2", "GroundFire_Right"}),
		inc_gunfire_9		= add_path("Incoming/", {"GroundFire_9_oclock", "GroundFire_Left"}),
		inc_gunfire_10		= add_path("Incoming/", {"GroundFire_10_oclock", "GroundFire_Left"}),
		inc_gunfire_11		= add_path("Incoming/", {"GroundFire_11_oclock", "GroundFire_11_oclock 2", "GroundFire_11_oclock 3", "GroundFire_Left"}),
		inc_gunfire_12		= add_path("Incoming/", {"GroundFire_12_oclock", "GroundFire_12_oclock 2", "GroundFire_12_oclock 3", "GroundFire_12_oclock 4"}),
		inc_gunfire_right	= add_path("Incoming/", {"GroundFire_Right"}),
		inc_gunfire_left	= add_path("Incoming/", {"GroundFire_Left"}),
		inc_missile_1		= add_path("Incoming/", {"Missile_1_oclock", "Missile_1_oclock 2", "Missile_Right", "Missile_Right 2", "Missile_Launch_Right", "Missile_Launch_Right 2", "Missile_Launch_Right 3"}),
		inc_missile_2		= add_path("Incoming/", {"Missile_2_oclock", "Missile_2_oclock 2", "Missile_Right", "Missile_Right 2", "Missile_Launch_Right", "Missile_Launch_Right 2", "Missile_Launch_Right 3"}),
		inc_missile_3		= add_path("Incoming/", {"Missile_3_oclock", "Missile_3_oclock 2", "Missile_Right", "Missile_Right 2", "Missile_Launch_Right", "Missile_Launch_Right 2", "Missile_Launch_Right 3"}),
		inc_missile_9		= add_path("Incoming/", {"Missile_9_oclock", "Missile_9_oclock 2", "Missile_Left", "Missile_Left 2", "Missile_Launch_Left", "Missile_Launch_Left 2", "Missile_Launch_Left 3"}),
		inc_missile_10		= add_path("Incoming/", {"Missile_10_oclock", "Missile_10_oclock 2", "Missile_Left", "Missile_Left 2", "Missile_Launch_Left", "Missile_Launch_Left 2", "Missile_Launch_Left 3"}),
		inc_missile_11		= add_path("Incoming/", {"Missile_11_oclock", "Missile_Left", "Missile_Left 2", "Missile_Launch_Left", "Missile_Launch_Left 2", "Missile_Launch_Left 3"}),
		inc_missile_11		= add_path("Incoming/", {"Missile_11_oclock", "Missile_Left", "Missile_Left 2", "Missile_Launch_Left", "Missile_Launch_Left 2", "Missile_Launch_Left 3"}),
		inc_missile_12		= add_path("Incoming/", {"Missile_12_oclock"}),
		inc_missile_right	= add_path("Incoming/", {"Missile_Right", "Missile_Right 2", "Missile_Launch_Right", "Missile_Launch_Right 2", "Missile_Launch_Right 3"}),
		inc_missile_left	= add_path("Incoming/", {"Missile_Left", "Missile_Left 2", "Missile_Launch_Left", "Missile_Launch_Left 2", "Missile_Launch_Left 3"}),
	},
	
}