--Auto generated file
AISounds =
{
	path_pref_eng = "Speech/ENG/Mi-24P/",
	path_pref_rus = "Speech/RUS/Mi-24P/",
	path_pilot = "Petrovich_Pilot/",
	path_op = "Petrovich_CPG/",
	extension = "",

	pilot_sounds = 
	{
		"t180",
		"Aligning",
		"Break_Left",
		"Break_Right",
		"Decreasing_Alt",
		"Increase_Alt",
		"Left",
		"Direction",
		"Move_Back",
		"Move_Forward",
		"Right",
		"Slide_Left",
		"Slide_Right",
		"Slow_Down",
		"Speed_Up",
		"Stopping",
		"Coming_Up",
		"Coming_Down",
		"open_menu",
		"close_menu",
	},

	cpg_sounds = 
	{
		"c_range_neg",
		"c_range_closer",
		"shturm",
		"ataka",
		"ataka_he",
		"ataka_220",
		"observ_on",
		"observ_off",
		"searching",
		"eng_at_will",
		"eng_hold_fire",
		"target_destroyed",
		"good_effects",
		"firing",
		"wpn_turning_on",
		"wpn_ready",
		"aso_int4",
		"aso_int2",
		"aso_series4",
		"aso_series16",
		"aso_side_left",
		"aso_side_right",
		"aso_side_both",
		"aso_payload_chaff",
		"aso_payload_flares",
		"open_menu",
		"close_menu",
		"in_range",
		"out_of_chaff",
		"out_of_flares",
		"target_acq",
		"inc_gunfire_1",
		"inc_gunfire_2",
		"inc_gunfire_3",
		"inc_gunfire_9",
		"inc_gunfire_10",
		"inc_gunfire_11",
		"inc_gunfire_12",
		"inc_gunfire_right",
		"inc_gunfire_left",
		"inc_missile_1",
		"inc_missile_2",
		"inc_missile_3",
		"inc_missile_9",
		"inc_missile_10",
		"inc_missile_11",
		"inc_missile_12",
		"inc_missile_right",
		"inc_missile_left",
		"shift_left",
		"shift_right",
		"no_missiles",
		"target_lost",
	},

	pilot_files_eng = 
	{
		t180 = {"t180/Breaking 180 2.ogg", "t180/Breaking 180.ogg", },
		Aligning = {"Aligning/Aligning 2.ogg", "Aligning/Aligning 3.ogg", "Aligning/Aligning.ogg", },
		Break_Left = {"Break_Left/Breaking left 2.ogg", "Break_Left/Breaking left.ogg", },
		Break_Right = {"Break_Right/Breaking right 2.ogg", "Break_Right/Breaking right.ogg", },
		Decreasing_Alt = {"Decreasing_Alt/Copy, decreasing altitude 2.ogg", "Decreasing_Alt/Copy, decreasing altitude.ogg", },
		Increase_Alt = {"Increase_Alt/Copy, increasing altitude 2.ogg", "Increase_Alt/Copy, increasing altitude.ogg", },
		Left = {"Left/Turning left 2.ogg", "Left/Turning left 3.ogg", "Left/Turning left.ogg", },
		Direction = {"Direction/Copy, heading to direction 2.ogg", "Direction/Copy, heading to direction.ogg", },
		Move_Back = {"Move_Back/Moving back 2.ogg", "Move_Back/Moving back.ogg", },
		Move_Forward = {"Move_Forward/Moving forward 2.ogg", "Move_Forward/Moving forward.ogg", },
		Right = {"Right/Turning right 2.ogg", "Right/Turning right 3.ogg", "Right/Turning right.ogg", },
		Slide_Left = {"Slide_Left/Sliding left 2.ogg", "Slide_Left/Sliding left.ogg", },
		Slide_Right = {"Slide_Right/Sliding right 2.ogg", "Slide_Right/Sliding right.ogg", },
		Slow_Down = {"Slow_Down/Copy, slowing down 2.ogg", "Slow_Down/Copy, slowing down.ogg", },
		Speed_Up = {"Speed_Up/Copy, speeding up 2.ogg", "Speed_Up/Copy, speeding up.ogg", },
		Stopping = {"Stopping/Stopping 2.ogg", "Stopping/Stopping 3.ogg", "Stopping/Stopping.ogg", },
		Coming_Up = {"Coming_Up/Copy, coming up 2.ogg", "Coming_Up/Copy, coming up.ogg", },
		Coming_Down = {"Coming_Down/Copy, coming down 2.ogg", "Coming_Down/Copy, coming down.ogg", },
		open_menu = {"open_menu/_Start.ogg", },
		close_menu = {"close_menu/_End.ogg", },
	},

	cpg_files_eng = 
	{
		c_range_neg = {"c_range_neg/Negative, out of range.ogg", },
		c_range_closer = {"c_range_closer/Get me closer, out of range.ogg", },
		shturm = {"shturm/Shturm.ogg", },
		ataka = {"ataka/Ataka.ogg", },
		ataka_he = {"ataka_he/Ataka HE.ogg", },
		ataka_220 = {"ataka_220/Ataka 220.ogg", },
		observ_on = {"observ_on/Observe on, searching...2.ogg", "observ_on/Observe on, searching...3.ogg", "observ_on/Observe on, searching.ogg", "observ_on/Observe_Activated.ogg", },
		observ_off = {"observ_off/Observe off 2.ogg", "observ_off/Observe off 3.ogg", "observ_off/Observe off.ogg", },
		searching = {"searching/Searching 2.ogg", "searching/Searching 3.ogg", "searching/Searching.ogg", "searching/Target_Search 2.ogg", "searching/Target_Search.ogg", },
		eng_at_will = {"eng_at_will/Engaging at will 2.ogg", "eng_at_will/Engaging at will 3.ogg", "eng_at_will/Engaging at will.ogg", },
		eng_hold_fire = {"eng_hold_fire/Roger, Hold fire 2.ogg", "eng_hold_fire/Roger, Hold fire 3.ogg", "eng_hold_fire/Roger, Hold fire.ogg", },
		target_destroyed = {"target_destroyed/Good effects on target 2.ogg", "target_destroyed/Good effects on target 3.ogg", "target_destroyed/Good effects on target.ogg", "target_destroyed/Target destroyed 2.ogg", "target_destroyed/Target destroyed 3.ogg", "target_destroyed/Target destroyed.ogg", },
		good_effects = {},
		firing = {"firing/Engaging.ogg", "firing/Firing 2.ogg", "firing/Firing.ogg", "firing/Launch 2.ogg", "firing/Launch 3.ogg", "firing/Launch.ogg", },
		wpn_turning_on = {"wpn_turning_on/Turning on weapons...2.ogg", "wpn_turning_on/Turning on weapons.ogg", },
		wpn_ready = {"wpn_ready/Weapons ready 2.ogg", "wpn_ready/Weapons ready.ogg", },
		aso_int4 = {"aso_int4/ASO interval 4 2.ogg", "aso_int4/ASO interval 4.ogg", },
		aso_int2 = {"aso_int2/ASO interval 2 2.ogg", "aso_int2/ASO interval 2.ogg", },
		aso_series4 = {"aso_series4/ASO series 4 2.ogg", "aso_series4/ASO series 4.ogg", },
		aso_series16 = {"aso_series16/ASO series 16 2.ogg", "aso_series16/ASO series 16.ogg", },
		aso_side_left = {"aso_side_left/ASO switched to left side 2.ogg", "aso_side_left/ASO switched to left side.ogg", },
		aso_side_right = {"aso_side_right/ASO switched to right side 2.ogg", "aso_side_right/ASO switched to right side.ogg", },
		aso_side_both = {"aso_side_both/ASO both sides up 2.ogg", "aso_side_both/ASO both sides up.ogg", },
		aso_payload_chaff = {"aso_payload_chaff/ASO to Chaff 2.ogg", "aso_payload_chaff/ASO to Chaff.ogg", },
		aso_payload_flares = {"aso_payload_flares/ASO to Flares 2.ogg", "aso_payload_flares/ASO to Flares 3.ogg", "aso_payload_flares/ASO to Flares 4.ogg", "aso_payload_flares/ASO to Flares.ogg", },
		open_menu = {"open_menu/_Start.ogg", },
		close_menu = {"close_menu/_End.ogg", },
		in_range = {"in_range/In range 2.ogg", "in_range/In range 3.ogg", "in_range/In range.ogg", "in_range/Ready_To_Fire 2.ogg", "in_range/Ready_To_Fire 3.ogg", "in_range/Ready_To_Fire.ogg", "in_range/Target_In_Range 2.ogg", "in_range/Target_In_Range 3.ogg", "in_range/Target_In_Range.ogg", },
		out_of_chaff = {"out_of_chaff/Out of Chaff 2.ogg", "out_of_chaff/Out of Chaff 3.ogg", "out_of_chaff/Out of Chaff.ogg", },
		out_of_flares = {"out_of_flares/Out of Flares 2.ogg", "out_of_flares/Out of Flares 3.ogg", "out_of_flares/Out of Flares.ogg", },
		target_acq = {"target_acq/Target acquired 2.ogg", "target_acq/Target acquired 3.ogg", "target_acq/Target acquired.ogg", "target_acq/Target in sight 2.ogg", "target_acq/Target in sight 3.ogg", "target_acq/Target in sight.ogg", "target_acq/Tracking target 2.ogg", "target_acq/Tracking target 3.ogg", "target_acq/Tracking target.ogg", },
		inc_gunfire_1 = {"inc_gunfire_1/GroundFire_1_oclock.ogg", "inc_gunfire_1/Hostile_GroundFire_1_oclock.ogg", "inc_gunfire_1/Incoming_Fire_1_oclock.ogg", },
		inc_gunfire_2 = {"inc_gunfire_2/GroundFire_2_oclock.ogg", "inc_gunfire_2/Hostile_GroundFire_2_oclock.ogg", "inc_gunfire_2/Incoming_Fire_2_oclock.ogg", },
		inc_gunfire_3 = {"inc_gunfire_3/GroundFire_3_oclock.ogg", "inc_gunfire_3/Hostile_GroundFire_3_oclock.ogg", "inc_gunfire_3/Incoming_Fire_3_oclock.ogg", },
		inc_gunfire_9 = {"inc_gunfire_9/GroundFire_9_oclock.ogg", "inc_gunfire_9/Hostile_GroundFire_9_oclock.ogg", "inc_gunfire_9/Incoming_Fire_9_oclock.ogg", },
		inc_gunfire_10 = {"inc_gunfire_10/GroundFire_10_oclock.ogg", "inc_gunfire_10/Hostile_GroundFire_10_oclock.ogg", "inc_gunfire_10/Incoming_Fire_10_oclock.ogg", },
		inc_gunfire_11 = {"inc_gunfire_11/GroundFire_11_oclock.ogg", "inc_gunfire_11/Hostile_GroundFire_11_oclock.ogg", "inc_gunfire_11/Incoming_Fire_11_oclock.ogg", },
		inc_gunfire_12 = {"inc_gunfire_12/GroundFire_12_oclock.ogg", "inc_gunfire_12/Hostile_GroundFire_12_oclock 2.ogg", "inc_gunfire_12/Hostile_GroundFire_12_oclock 3.ogg", "inc_gunfire_12/Hostile_GroundFire_12_oclock 4.ogg", "inc_gunfire_12/Hostile_GroundFire_12_oclock 5.ogg", "inc_gunfire_12/Hostile_GroundFire_12_oclock.ogg", "inc_gunfire_12/Incoming_Fire_12_oclock.ogg", },
		inc_gunfire_right = {"inc_gunfire_right/GroundFire_Right_1.ogg", "inc_gunfire_right/GroundFire_Right_2.ogg", "inc_gunfire_right/Hostile_GroundFire_Right.ogg", },
		inc_gunfire_left = {"inc_gunfire_left/GroundFire_Left_1.ogg", "inc_gunfire_left/GroundFire_Left_2.ogg", "inc_gunfire_left/Hostile_GroundFire_Left.ogg", },
		inc_missile_1 = {"inc_missile_1/Incoming_Missile_1_oclock.ogg", "inc_missile_1/Missile_1_oclock 2.ogg", "inc_missile_1/Missile_1_oclock.ogg", "inc_missile_1/Missile_Launch_1_oclock 2.ogg", "inc_missile_1/Missile_Launch_1_oclock.ogg", "inc_missile_1/Missile_OnUs_1_oclock 2.ogg", "inc_missile_1/Missile_OnUs_1_oclock.ogg", },
		inc_missile_2 = {"inc_missile_2/Incoming_Missile_2_oclock.ogg", "inc_missile_2/Missile_2_oclock 2.ogg", "inc_missile_2/Missile_2_oclock 3.ogg", "inc_missile_2/Missile_2_oclock.ogg", "inc_missile_2/Missile_Launch_2_oclock 2.ogg", "inc_missile_2/Missile_Launch_2_oclock.ogg", "inc_missile_2/Missile_OnUs_2_oclock 2.ogg", "inc_missile_2/Missile_OnUs_2_oclock.ogg", },
		inc_missile_3 = {"inc_missile_3/Incoming_Missile_3_oclock.ogg", "inc_missile_3/Missile_3_oclock 2.ogg", "inc_missile_3/Missile_3_oclock.ogg", "inc_missile_3/Missile_Launch_3_oclock.ogg", "inc_missile_3/Missile_OnUs_3_oclock 2.ogg", "inc_missile_3/Missile_OnUs_3_oclock 3.ogg", "inc_missile_3/Missile_OnUs_3_oclock.ogg", },
		inc_missile_9 = {"inc_missile_9/Incoming_Missile_9_oclock.ogg", "inc_missile_9/Missile_9_oclock.ogg", "inc_missile_9/Missile_Launch_9_oclock 2.ogg", "inc_missile_9/Missile_Launch_9_oclock 3.ogg", "inc_missile_9/Missile_Launch_9_oclock.ogg", "inc_missile_9/Missile_OnUs_9_oclock.ogg", },
		inc_missile_10 = {"inc_missile_10/Incoming_Missile_10_oclock.ogg", "inc_missile_10/Missile_10_oclock 2.ogg", "inc_missile_10/Missile_10_oclock.ogg", "inc_missile_10/Missile_Launch_10_oclock 2.ogg", "inc_missile_10/Missile_Launch_10_oclock.ogg", "inc_missile_10/Missile_OnUs_10_oclock 2.ogg", "inc_missile_10/Missile_OnUs_10_oclock.ogg", "inc_missile_10/Missile_OnUs_11_oclock 2.ogg", "inc_missile_10/Missile_OnUs_11_oclock 3.ogg", "inc_missile_10/Missile_OnUs_11_oclock.ogg", },
		inc_missile_11 = {"inc_missile_11/Incoming_Missile_11_oclock.ogg", "inc_missile_11/Missile_11_oclock 2.ogg", "inc_missile_11/Missile_11_oclock.ogg", "inc_missile_11/Missile_Launch_11_oclock.ogg", },
		inc_missile_12 = {"inc_missile_12/Incoming_Missile_12_oclock 2.ogg", "inc_missile_12/Incoming_Missile_12_oclock.ogg", "inc_missile_12/Missile_12_oclock 2.ogg", "inc_missile_12/Missile_12_oclock.ogg", "inc_missile_12/Missile_Launch_12_oclock.ogg", "inc_missile_12/Missile_OnUs_12_oclock 2.ogg", "inc_missile_12/Missile_OnUs_12_oclock 3.ogg", "inc_missile_12/Missile_OnUs_12_oclock.ogg", },
		inc_missile_right = {"inc_missile_right/Incoming_Missile_Right 2.ogg", "inc_missile_right/Incoming_Missile_Right.ogg", "inc_missile_right/Missile_Launch_Right 2.ogg", "inc_missile_right/Missile_Launch_Right 3.ogg", "inc_missile_right/Missile_Launch_Right.ogg", "inc_missile_right/Missile_OnUs_Right.ogg", "inc_missile_right/Missile_Right.ogg", },
		inc_missile_left = {"inc_missile_left/Incoming_Missile_Left 2.ogg", "inc_missile_left/Incoming_Missile_Left.ogg", "inc_missile_left/Missile_Launch_Left 2.ogg", "inc_missile_left/Missile_Launch_Left 3.ogg", "inc_missile_left/Missile_Launch_Left.ogg", "inc_missile_left/Missile_Left.ogg", "inc_missile_left/Missile_OnUs_Left.ogg", },
		shift_left = {"shift_left/Shift_Left 2.ogg", "shift_left/Shift_Left 3.ogg", "shift_left/Shift_Left.ogg", },
		shift_right = {"shift_right/Shift_Right 2.ogg", "shift_right/Shift_Right 3.ogg", "shift_right/Shift_Right.ogg", },
		no_missiles = {"no_missiles/No_Missiles 2.ogg", "no_missiles/No_Missiles.ogg", },
		target_lost = {"target_lost/Target_Lost 2.ogg", "target_lost/Target_Lost.ogg", },
	},

	pilot_files_rus = 
	{
		t180 = {"t180/Breaking 180 2.ogg", "t180/Breaking 180.ogg", },
		Aligning = {"Aligning/Aligning 2.ogg", "Aligning/Aligning.ogg", },
		Break_Left = {"Break_Left/Breaking left 2.ogg", "Break_Left/Breaking left.ogg", },
		Break_Right = {"Break_Right/Breaking right 2.ogg", "Break_Right/Breaking right.ogg", },
		Decreasing_Alt = {"Decreasing_Alt/Copy, decreasing altitude.ogg", },
		Increase_Alt = {"Increase_Alt/Copy, increasing altitude 2.ogg", "Increase_Alt/Copy, increasing altitude.ogg", },
		Left = {"Left/Turning left.ogg", },
		Direction = {"Direction/Copy, heading to direction.ogg", },
		Move_Back = {"Move_Back/Moving back.ogg", },
		Move_Forward = {"Move_Forward/Moving forward.ogg", },
		Right = {"Right/Turning right.ogg", },
		Slide_Left = {"Slide_Left/Sliding left.ogg", },
		Slide_Right = {"Slide_Right/Sliding right.ogg", },
		Slow_Down = {"Slow_Down/Copy, slowing down 2.ogg", "Slow_Down/Copy, slowing down.ogg", },
		Speed_Up = {"Speed_Up/Copy, speeding up 2.ogg", "Speed_Up/Copy, speeding up.ogg", },
		Stopping = {"Stopping/Stopping 2.ogg", "Stopping/Stopping.ogg", },
		Coming_Up = {"Coming_Up/Copy, coming up.ogg", },
		Coming_Down = {"Coming_Down/Copy, coming down.ogg", },
		open_menu = {"open_menu/_Start.ogg", },
		close_menu = {"close_menu/_End.ogg", },
	},

	cpg_files_rus = 
	{
		c_range_neg = {"c_range_neg/Negative, out of range.ogg", },
		c_range_closer = {"c_range_closer/Get me closer, out of range.ogg", },
		shturm = {"shturm/Shturm.ogg", },
		ataka = {"ataka/Ataka 2.ogg", "ataka/Ataka 3.ogg", "ataka/Ataka.ogg", },
		ataka_he = {"ataka_he/Ataka HE.ogg", },
		ataka_220 = {"ataka_220/Ataka 220.ogg", },
		observ_on = {"observ_on/Observe on, searching.ogg", "observ_on/Observe_Activated 2.ogg", "observ_on/Observe_Activated.ogg", },
		observ_off = {"observ_off/Observe off.ogg", },
		searching = {"searching/Searching 2.ogg", "searching/Searching 3.ogg", "searching/Searching.ogg", },
		eng_at_will = {"eng_at_will/Engaging at will.ogg", },
		eng_hold_fire = {"eng_hold_fire/Roger, Hold fire.ogg", },
		target_destroyed = {"target_destroyed/Target destroyed 2.ogg", "target_destroyed/Target destroyed.ogg", "target_destroyed/Target_Hit 2.ogg", "target_destroyed/Target_Hit.ogg", },
		good_effects = {},
		firing = {"firing/Launch 2.ogg", "firing/Launch 3.ogg", "firing/Launch.ogg", },
		wpn_turning_on = {"wpn_turning_on/Weapons ready 2.ogg", },
		wpn_ready = {"wpn_ready/Weapons ready.ogg", },
		aso_int4 = {"aso_int4/ASO interval 4 2.ogg", "aso_int4/ASO interval 4 3.ogg", "aso_int4/ASO interval 4.ogg", },
		aso_int2 = {"aso_int2/ASO interval 2 2.ogg", "aso_int2/ASO interval 2 3.ogg", "aso_int2/ASO interval 2.ogg", },
		aso_series4 = {"aso_series4/ASO series 4 2.ogg", "aso_series4/ASO series 4 3.ogg", "aso_series4/ASO series 4.ogg", },
		aso_series16 = {"aso_series16/ASO series 16 2.ogg", "aso_series16/ASO series 16 3.ogg", "aso_series16/ASO series 16.ogg", },
		aso_side_left = {"aso_side_left/ASO launch from left side 2.ogg", "aso_side_left/ASO launch from left side.ogg", },
		aso_side_right = {"aso_side_right/ASO launch from right side 2.ogg", "aso_side_right/ASO launch from right side 3.ogg", "aso_side_right/ASO launch from right side.ogg", },
		aso_side_both = {"aso_side_both/ASO launch from both sides 2.ogg", "aso_side_both/ASO launch from both sides 3.ogg", "aso_side_both/ASO launch from both sides.ogg", },
		aso_payload_chaff = {"aso_payload_chaff/ASO to Chaff 2.ogg", "aso_payload_chaff/ASO to Chaff 3.ogg", "aso_payload_chaff/ASO to Chaff.ogg", },
		aso_payload_flares = {"aso_payload_flares/ASO to Flares 2.ogg", "aso_payload_flares/ASO to Flares 3.ogg", "aso_payload_flares/ASO to Flares 4.ogg", "aso_payload_flares/ASO to Flares.ogg", },
		open_menu = {"open_menu/_Start.ogg", },
		close_menu = {"close_menu/_End.ogg", },
		in_range = {"in_range/In range 2.ogg", "in_range/In range.ogg", "in_range/Target in range 2.ogg", "in_range/Target in range.ogg", },
		out_of_chaff = {"out_of_chaff/Out of Chaff 2.ogg", "out_of_chaff/Out of Chaff 3.ogg", "out_of_chaff/Out of Chaff 4.ogg", "out_of_chaff/Out of Chaff.ogg", },
		out_of_flares = {"out_of_flares/Out of Flares 2.ogg", "out_of_flares/Out of Flares.ogg", },
		target_acq = {"target_acq/Target acquired 2.ogg", "target_acq/Target acquired.ogg", "target_acq/Target in sight.ogg", "target_acq/Tracking target 2.ogg", "target_acq/Tracking target.ogg", "target_acq/Tracking_Target 2.ogg", "target_acq/Tracking_Target 3.ogg", "target_acq/Tracking_Target 4.ogg", "target_acq/Tracking_Target.ogg", },
		inc_gunfire_1 = {"inc_gunfire_1/GroundFire_1_oclock.ogg", },
		inc_gunfire_2 = {"inc_gunfire_2/GroundFire_2_oclock.ogg", },
		inc_gunfire_3 = {"inc_gunfire_3/GroundFire_3_oclock 2.ogg", "inc_gunfire_3/GroundFire_3_oclock.ogg", },
		inc_gunfire_9 = {"inc_gunfire_9/GroundFire_9_oclock.ogg", },
		inc_gunfire_10 = {"inc_gunfire_10/GroundFire_10_oclock.ogg", },
		inc_gunfire_11 = {"inc_gunfire_11/GroundFire_11_oclock 2.ogg", "inc_gunfire_11/GroundFire_11_oclock 3.ogg", "inc_gunfire_11/GroundFire_11_oclock.ogg", },
		inc_gunfire_12 = {"inc_gunfire_12/GroundFire_12_oclock 2.ogg", "inc_gunfire_12/GroundFire_12_oclock 3.ogg", "inc_gunfire_12/GroundFire_Front 2.ogg", "inc_gunfire_12/GroundFire_Front 3.ogg", "inc_gunfire_12/GroundFire_Front 4.ogg", "inc_gunfire_12/GroundFire_Front 5.ogg", "inc_gunfire_12/GroundFire_Front 6.ogg", "inc_gunfire_12/GroundFire_Front.ogg", },
		inc_gunfire_right = {"inc_gunfire_right/GroundFire_Right.ogg", },
		inc_gunfire_left = {"inc_gunfire_left/GroundFire_Left.ogg", },
		inc_missile_1 = {"inc_missile_1/Missile_1_oclock 2.ogg", "inc_missile_1/Missile_1_oclock.ogg", },
		inc_missile_2 = {"inc_missile_2/Missile_2_oclock 2.ogg", "inc_missile_2/Missile_2_oclock.ogg", },
		inc_missile_3 = {"inc_missile_3/Missile_3_oclock 2.ogg", "inc_missile_3/Missile_3_oclock.ogg", },
		inc_missile_9 = {"inc_missile_9/Missile_9_oclock 2.ogg", "inc_missile_9/Missile_9_oclock.ogg", },
		inc_missile_10 = {"inc_missile_10/Missile_10_oclock 2.ogg", "inc_missile_10/Missile_10_oclock.ogg", },
		inc_missile_11 = {"inc_missile_11/Missile_11_oclock.ogg", },
		inc_missile_12 = {"inc_missile_12/Missile_12_oclock.ogg", },
		inc_missile_right = {"inc_missile_right/Missile_Launch_Right 2.ogg", "inc_missile_right/Missile_Launch_Right 3.ogg", "inc_missile_right/Missile_Launch_Right.ogg", "inc_missile_right/Missile_Right 2.ogg", "inc_missile_right/Missile_Right.ogg", },
		inc_missile_left = {"inc_missile_left/Missile_Launch_Left 2.ogg", "inc_missile_left/Missile_Launch_Left 3.ogg", "inc_missile_left/Missile_Launch_Left.ogg", "inc_missile_left/Missile_Left 2.ogg", "inc_missile_left/Missile_Left.ogg", },
		shift_left = {"shift_left/Shift_Left 2.ogg", "shift_left/Shift_Left.ogg", },
		shift_right = {"shift_right/Shift_Right 2.ogg", "shift_right/Shift_Right 3.ogg", "shift_right/Shift_Right.ogg", },
		no_missiles = {"no_missiles/No_Missiles 2.ogg", "no_missiles/No_Missiles 3.ogg", "no_missiles/No_Missiles.ogg", },
		target_lost = {"target_lost/Target_Lost 2.ogg", "target_lost/Target_Lost.ogg", },
	},

}
