dofile(LockOn_Options.script_path.."CDU/indicator/CDU_definitions.lua")

AddStaticText("PageNameSTRINFO",    2, 1, LFT, "STRINFO")

AddText		 ("STRNumberIncDec",    1, 3, LFT, {{"STRNumberIncDec"}}, INC_DEC)
AddText		 ("STRNumber",		    2, 3, LFT, {{"ATTRIB_SCS", 0}, {"CurrSteerPointNumber", 0}}, "****")
AddText		 ("STRNumber1",		    2, 3, LFT, {{"ATTRIB_SCS", 0}, {"CurrSteerPointNumber", 1}})
AddText		 ("STRNumber2",		    2, 3, LFT, {{"ATTRIB_SCS", 1}}, "S")
AddText		 ("STRNumber3",		    3, 3, LFT, {{"ATTRIB_SCS", 1}, {"ATTRIB_CourseValue"}})

AddStaticText("STRDMH",			    2, 4, LFT, "DMH")
AddText		 ("STRDMH1",			   10, 4, RGHT, {{"ATTRIB_SCS", 0}, {"STRInfoPresent", 0}}, "***")
AddText		 ("STRDMH2",			   10, 4, RGHT, {{"ATTRIB_SCS", 0}, {"STRInfoPresent", 1}, {"STRDMH"}})
AddText		 ("STRDMH3",			   10, 4, RGHT, {{"ATTRIB_SCS", 1}, {"SCSMagneticHeading"}})

AddStaticText("STRDIS",			    2, 5, LFT, "DIS")
AddText		 ("STRDIS1",			   10, 5, RGHT, {{"ATTRIB_SCS", 0}, {"STRInfoPresent", 0}}, "*****")
AddText		 ("STRDIS2",			   10, 5, RGHT, {{"ATTRIB_SCS", 0}, {"STRInfoPresent", 1}, {"STRDIS"}})
AddText		 ("STRDIS3",			   10, 5, RGHT, {{"ATTRIB_SCS", 1}, {"SCSDistance"}})

AddStaticText("STREL",			    2, 6, LFT, "EL")
AddText		 ("STREL1",			   10, 6, RGHT, {{"ATTRIB_SCS", 0}, {"STRInfoPresent", 0}, {"STRELPresent", 0}}, "*****")
AddText		 ("STREL2",			   10, 6, RGHT, {{"ATTRIB_SCS", 0}, {"STRInfoPresent", 1}, {"STRELPresent", 0}}, "*****")
AddText		 ("STREL3",			   10, 6, RGHT, {{"ATTRIB_SCS", 0}, {"STRInfoPresent", 1}, {"STRELPresent", 1}, {"STREL"}})
AddText		 ("STREL4",			   10, 6, RGHT, {{"ATTRIB_SCS", 1}, {"SCSElevation"}})

AddStaticText("STRBRGRADRotary",    1, 7, LFT, ROTARY)
AddText		 ("STRBRGRADMode",	    2, 7, LFT, {{"STRBRGRADMode", 0}}, "BRG")
AddText		 ("STRBRGRADMode1",	    2, 7, LFT, {{"STRBRGRADMode", 1}}, "RAD")
AddText		 ("STRBRGRAD",		    8, 7, RGHT, {{"ATTRIB_SCS", 0}, {"STRInfoPresent", 0}}, "***")
AddText		 ("STRBRGRAD1",		    8, 7, RGHT, {{"ATTRIB_SCS", 0}, {"STRInfoPresent", 1}, {"STRBRGRADMode", 0}, {"STRBRG"}})
AddText		 ("STRBRGRAD2",		    8, 7, RGHT, {{"ATTRIB_SCS", 0}, {"STRInfoPresent", 1}, {"STRBRGRADMode", 1}, {"STRRAD"}})
AddText		 ("STRBRGRAD3",		    8, 7, RGHT, {{"ATTRIB_SCS", 1}, {"STRBRGRADMode", 0}, {"SCSBRG"}})
AddText		 ("STRBRGRAD4",		    8, 7, RGHT, {{"ATTRIB_SCS", 1}, {"STRBRGRADMode", 1}, {"SCSRAD"}})

AddStaticText("WAYPOINT",		    1, 9, LFT, BRANCH_L .. "WAYPOINT")

AddText		 ("STRIdentEntry",	   24, 3, RGHT, {{"ATTRIB_SCS", 0}, {"STRIdentEntry"}}, DATA_ENTRY)
AddText		 ("STRIdent",		   23, 3, RGHT, {{"ATTRIB_SCS", 0}, {"STRIdent", 0}}, "************")
AddText		 ("STRIdent1",		   23, 3, RGHT, {{"ATTRIB_SCS", 0}, {"STRIdent", 1}})
AddText		 ("STRIdent2",		   23, 3, RGHT, {{"ATTRIB_SCS", 1}}, "************")

AddStaticText("STRTTG",			   12, 5, LFT, "TTG")
AddText		 ("STRTTG1",			   16, 5, LFT, {{"ATTRIB_SCS", 0}, {"STRInfoPresent", 0}}, "********")
AddText		 ("STRTTG2",			   16, 5, LFT, {{"ATTRIB_SCS", 0}, {"STRInfoPresent", 1}, {"NotMoving", 0, 3}}, "********")
AddText		 ("STRTTG3",			   16, 5, LFT, {{"ATTRIB_SCS", 0}, {"STRInfoPresent", 1}, {"NotMoving", 1, 3}, {"STRTTG"}})
AddText		 ("STRTTG4",			   16, 5, LFT, {{"ATTRIB_SCS", 1}, {"NotMoving", 0, 3}}, "********")
AddText		 ("STRTTG5",			   16, 5, LFT, {{"ATTRIB_SCS", 1}, {"NotMoving", 1, 3}, {"SCSTTG"}})

AddStaticText("TOT",			   12, 6, LFT, "TOT")
AddText		 ("STRTOT",			   16, 6, LFT, {{"ATTRIB_SCS", 0}, {"STRInfoPresent", 0}}, "********")
AddText		 ("STRTOT1",			   16, 6, LFT, {{"ATTRIB_SCS", 0}, {"STRInfoPresent", 1}, {"NotMoving", 0, 3}}, "********")
AddText		 ("STRTOT2",			   16, 6, LFT, {{"ATTRIB_SCS", 0}, {"STRInfoPresent", 1}, {"NotMoving", 1, 3}, {"STRTOT"}})
AddText		 ("STRTOT3",			   16, 6, LFT, {{"ATTRIB_SCS", 1}, {"NotMoving", 0, 3}}, "********")
AddText		 ("STRTOT4",			   16, 6, LFT, {{"ATTRIB_SCS", 1}, {"NotMoving", 1, 3}, {"SCSTOT"}})

AddStaticText("WND",			   13, 8, LFT, "WND    /")
AddText		 ("STRWindDirection1", 17, 8, LFT, {{"WindParamsValid", 0}}, "***")
AddText		 ("STRWindDirection2", 17, 8, LFT, {{"WindParamsValid", 1}, {"WAYPTWindDirection"}})
AddText		 ("STRWindSpeed1",     21, 8, LFT, {{"WindParamsValid", 0}}, "***")
AddText		 ("STRWindSpeed2",     21, 8, LFT, {{"WindParamsValid", 1}, {"WAYPTWindSpeed"}})

AddText		 ("STRReqSpeedMode",	   19, 7, RGHT, {{"ATTRIB_SCS", 0}, {"EGINavMode", 1}, {"ReqSpeedIsAvail", 1}, {"STRSpeedMode", 0}}, "RIAS")
AddText		 ("STRReqSpeedMode1",	   19, 7, RGHT, {{"ATTRIB_SCS", 0}, {"EGINavMode", 1}, {"ReqSpeedIsAvail", 1}, {"STRSpeedMode", 1}}, "RTAS")
AddText		 ("STRReqSpeedMode2",	   19, 7, RGHT, {{"ATTRIB_SCS", 0}, {"EGINavMode", 1}, {"ReqSpeedIsAvail", 1}, {"STRSpeedMode", 2}}, "RGS")
AddText		 ("STRReqIAS",			   23, 7, RGHT, {{"ATTRIB_SCS", 0}, {"EGINavMode", 1}, {"ReqSpeedIsAvail", 1}, {"STRSpeedMode", 0}, {"STRReqIAS"}})
AddText		 ("STRReqTAS",			   23, 7, RGHT, {{"ATTRIB_SCS", 0}, {"EGINavMode", 1}, {"ReqSpeedIsAvail", 1}, {"STRSpeedMode", 1}, {"STRReqTAS"}})
AddText		 ("STRReqGroundSpeed",	   23, 7, RGHT, {{"ATTRIB_SCS", 0}, {"EGINavMode", 1}, {"ReqSpeedIsAvail", 1}, {"STRSpeedMode", 2}, {"STRReqGroundSpeed"}})
AddText		 ("STRReqSpeedRotary",	   24, 7, LFT, {{"ATTRIB_SCS", 0}, {"EGINavMode", 1}, {"ReqSpeedIsAvail", 1}}, ROTARY)

AddText		 ("STRSpeedMode3",	17, 9, LFT, {{"EGINavMode", 0}}, "*******")
AddText		 ("STRSpeedMode4",	19, 9, RGHT, {{"EGINavMode", 1}, {"PPOSSpeedMode", 0}}, "IAS")
AddText		 ("STRSpeedMode5",	19, 9, RGHT, {{"EGINavMode", 1}, {"PPOSSpeedMode", 1}}, "TAS")
AddText		 ("STRSpeedMode6",	19, 9, RGHT, {{"EGINavMode", 1}, {"PPOSSpeedMode", 2}}, "GS")
AddText		 ("STRIAS1",		23, 9, RGHT, {{"EGINavMode", 1}, {"PPOSSpeedMode", 0}, {"IAS"}})
AddText		 ("STRTAS1",		23, 9, RGHT, {{"EGINavMode", 1}, {"PPOSSpeedMode", 1}, {"TAS"}})
AddText		 ("STRGroundSpeed1", 23, 9, RGHT, {{"EGINavMode", 1}, {"PPOSSpeedMode", 2}, {"GroundSpeed"}})
AddStaticText("STRSpeedRotary1", 24, 9, LFT, ROTARY) 

add_static_hint_CDU("L1", _("Enter desired steerpoint number/letter from scratchpad or use +- rocker to scroll up/down"))
add_static_hint_CDU("L3", _("Rotary between BRG and RAD display"))
add_static_hint_CDU("L4", _("Branch to the WAYPT Page for current steerpoint"))
add_static_hint_CDU("R1", _("Enter desired steerpoint identifier from scratchpad"))
add_hint_controllers_CDU("R3", _("Rotary between RIAS/RTAS/RGS"), {{"ReqSpeedIsAvail", 1}})
add_static_hint_CDU("R4", _("Rotary between IAS/TAS/GS"))
