local count = -1
local function counter()
	count = count + 1
	return count
end

PRFL_SYMB_CROSSHAIR				= counter()
PRFL_SYMB_OWN_SPI				= counter()
 PRFL_SYMB_SPI_INDICATOR		= counter()
PRFL_SYMB_HORIZON_LINE			= counter()
PRFL_SYMB_HDC					= counter()
PRFL_SYMB_HOOKSHIP				= counter()
PRFL_SYMB_TGP_DIAMOND			= counter()
 PRFL_SYMB_TGP_FOV				= counter()
PRFL_SYMB_FLIGHT_MEMBERS		= counter()
 PRFL_SYMB_FLIGHT_MEMBER_SPI	= counter()
PRFL_SYMB_DONOR_AIR_PPLI		= counter()
 PRFL_SYMB_DONOR_SPI			= counter()
PRFL_SYMB_CURRENT_MA			= counter()
PRFL_SYMB_AIR_ENVIR				= counter()
 PRFL_SYMB_AIR_VMF_FRIEND		= counter()
 PRFL_SYMB_AIR_PPLI_NON_DONR	= counter()
 PRFL_SYMB_AIR_TRK_FRIEND		= counter()
 PRFL_SYMB_AIR_NEUTRAL			= counter()
 PRFL_SYMB_AIR_SUSPECT			= counter()
 PRFL_SYMB_AIR_HOSTILE			= counter()
 PRFL_SYMB_AIR_OTHER			= counter()
PRFL_SYMB_GND_ENVIR				= counter()
 PRFL_SYMB_GND_VMF_FRIEND		= counter()
 PRFL_SYMB_GND_PPLI				= counter()
 PRFL_SYMB_GND_TRK_FRIEND		= counter()
 PRFL_SYMB_GND_NEUTRAL			= counter()
 PRFL_SYMB_GND_SUSPECT			= counter()
 PRFL_SYMB_GND_HOSTILE			= counter()
 PRFL_SYMB_GND_OTHER			= counter()
PRFL_SYMB_EMER_POINT			= counter()
PRFL_SYMB_STEERPOINT			= counter()
PRFL_SYMB_MSN_MARKPOINTS		= counter()
 PRFL_SYMB_MSN_MARK_LABELS		= counter()
PRFL_SYMB_AIRSPEED				= counter()
PRFL_SYMB_RADAR_ALTITUDE		= counter()
PRFL_SYMB_BARO_ALTITUDE			= counter()
PRFL_SYMB_A_C_HEADING			= counter()
PRFL_SYMB_HELMET_HEADING		= counter()
PRFL_SYMB_HMD_ELEV_LINES		= counter()
