local count = 0
local function counter()
	count = count + 1
	return count
end
-------DEVICE ID-------
devices = {}
devices["ELEC_INTERFACE"]			= counter()--1
devices["MFCD_LEFT"]				= counter()--2
devices["MFCD_RIGHT"]				= counter()--3
devices["CMSP"]						= counter()--4
devices["CMSC"]						= counter()--5
devices["JAMMERS_INTERFACE"]		= counter()--6
devices["AHCP"]						= counter()--7
devices["UFC"]						= counter()--8
devices["CDU"]						= counter()--9
devices["MAVERICK_INTERFACE"]		= counter()--10
devices["LITENING_INTERFACE"]		= counter()--11
devices["IFFCC"]					= counter()--12
devices["DSMS_INTERFACE"]			= counter()--13
devices["DATA_TRANSFER_SYSTEM"]		= counter()--14
devices["DIGITAL_CLOCK"]			= counter()--15
devices["DBG"]						= counter()--16
devices["HOTAS"]					= counter()--17
devices["EGI"]						= counter()--18
devices["HUD"]						= counter()--19
devices["DTSAS"]					= counter()--20
devices["NAVIGATION_COMPUTER"]		= counter()--21
devices["AAP"]						= counter()--22
devices["CADC"]						= counter()--23
devices["SYS_CONTROLLER"]			= counter()--24
devices["PULSE_TIMER"]				= counter()--25
devices["TAD"]						= counter()--26
devices["VMU"]						= counter()--27
devices["TONE_GENERATOR"]			= counter()--28
devices["AN_ALR69V"]				= counter()--29  -- Radar Warning Receiver (RWR)
devices["AN_ALE40V"]				= counter()--30      -- Chaff and Flare Dispenser
devices["SIDEWINDER_INTERFACE"]		= counter()--31
devices["SADL"]						= counter()--32
devices["IAM_INTERFACE"]			= counter()--33
devices["HELMET_DEVICE"]			= counter()--34
devices["FM_PROXY"]					= counter()--35
devices["FUEL_SYSTEM"]				= counter()--36
devices["ENGINE_SYSTEM"]			= counter()--37
devices["AUTOPILOT"]				= counter()--38
devices["CPT_MECH"]					= counter()--39 
devices["OXYGEN_SYSTEM"]			= counter()--40
devices["ENVIRONMENT_SYSTEM"]		= counter()--41
devices["HYDRAULIC_SYSTEM"]			= counter()--42
devices["IFF"]						= counter()--43
devices["HARS"]						= counter()--44
devices["HSI"]						= counter()--45
devices["NMSP"]                     = counter()--46
devices["ADI"]                    	= counter()--47
devices["SAI"]                    	= counter()--48
devices["LIGHT_SYSTEM"]				= counter()--49
devices["FIRE_SYSTEM"]				= counter()--50
devices["TACAN"]					= counter()--51
devices["STALL"]					= counter()--52
devices["ILS"]						= counter()--53
devices["UHF_RADIO"]				= counter()--54
devices["VHF_AM_RADIO"]				= counter()--55
devices["VHF_FM_RADIO"]				= counter()--56
devices["TISL"]						= counter()--57
devices["INTERCOM"]					= counter()--58
devices["AAR47"]                    = counter()--59  -- Missile Launch Warning System (MLWS)
devices["RT1720"]                   = counter()--60  	 -- DataLink radio communicator
devices["AIRSPEED_INDICATOR"]       = counter()--61  
devices["AAU34"]      				= counter()--62  
devices["CICU"]      				= counter()--63  
devices["STANDBY_COMPASS"] 			= counter()--64  	-- compass
devices["ARCADE"]					= counter()--65
devices["PADLOCK"]					= counter()--66
devices["AN_APN_194"]               = counter()--67  	-- Radar Altimeter
devices["REMOTE_COMPASS"]           = counter()--68  	-- Remote Compass Transmitter
devices["KY_58"]               		= counter()--69  	-- Secure Voice Control Panel
devices["MACROS"]          			= counter()--70 	-- start stop macros
devices["AVIONICS_PROXY"]          	= counter()--71 	-- provides access from weaponscommon to the real avionics data
devices["ACCELEROMETER"]          	= counter()--72 	-- accelerometer
devices["DVADR"]          			= counter()--73 	-- DVADR
devices["TACAN_CTRL_PANEL"]			= counter()--74		-- TACAN AN/ARN-118 Control Panel
devices["SCORPION_HMCS"]			= counter()--75		-- Scorpion Helmet Mounted Cueing System