-- китайский шрифт simsun идет в поставке с Windows
return {
	["DejaVuLGCSans-Bold.ttf"					] = "DroidSansFallback-Bold.ttf"		,
	["DejaVuLGCSans-BoldOblique.ttf"			] = "DroidSansFallback-BoldOblique.ttf"	,
	["DejaVuLGCSans-ExtraLight.ttf"				] = "DroidSansFallback.ttf"				,
	["DejaVuLGCSans-Oblique.ttf"				] = "DroidSansFallback-Oblique.ttf"		,
	["DejaVuLGCSans.ttf"						] = "DroidSansFallback.ttf"				,
	["DejaVuLGCSansCondensed-Bold.ttf"			] = "DroidSansFallback-Bold.ttf"		,
	["DejaVuLGCSansCondensed-BoldOblique.ttf"	] = "DroidSansFallback-BoldOblique.ttf"	,
	["DejaVuLGCSansCondensed-Oblique.ttf"		] = "DroidSansFallback-Oblique.ttf"		,
	["DejaVuLGCSansCondensed.ttf"				] = "DroidSansFallback.ttf"				,
	["DejaVuLGCSansMono-Bold.ttf"				] = "DroidSansFallback-Bold.ttf"		,
	["DejaVuLGCSansMono-BoldOblique.ttf"		] = "DroidSansFallback-BoldOblique.ttf"	,
	["DejaVuLGCSansMono-Oblique.ttf"			] = "DroidSansFallback-Oblique.ttf"		,
	["DejaVuLGCSansMono.ttf"					] = "DroidSansFallback.ttf"				,
	["DejaVuLGCSerif-Bold.ttf"					] = "DroidSansFallback-Bold.ttf"		,
	["DejaVuLGCSerif-BoldItalic.ttf"			] = "DroidSansFallback-BoldOblique.ttf"	,
	["DejaVuLGCSerif-Italic.ttf"				] = "DroidSansFallback-Oblique.ttf"		,
	["DejaVuLGCSerif.ttf"						] = "DroidSansFallback.ttf"				,
	["DejaVuLGCSerifCondensed-Bold.ttf"			] = "DroidSansFallback-Bold.ttf"		,
	["DejaVuLGCSerifCondensed-BoldItalic.ttf"	] = "DroidSansFallback-BoldOblique.ttf"	,
	["DejaVuLGCSerifCondensed-Italic.ttf"		] = "DroidSansFallback-Oblique.ttf"		,
	["PTM55F.ttf"								] = "DroidSansFallback.ttf"				,
	["PTM75F.ttf"								] = "DroidSansFallback-Bold.ttf"		,
	["Roboto-Black.ttf"							] = "DroidSansFallback-Bold.ttf"		,
	["Roboto-BlackItalic.ttf"					] = "DroidSansFallback-BoldOblique.ttf"	,
	["Roboto-Bold.ttf"							] = "DroidSansFallback-Bold.ttf"		,
	["Roboto-BoldItalic.ttf"					] = "DroidSansFallback-BoldOblique.ttf"	,
	["Roboto-Italic.ttf"						] = "DroidSansFallback-Oblique.ttf"		,
	["Roboto-Light.ttf"							] = "DroidSansFallback.ttf"				,
	["Roboto-LightItalic.ttf"					] = "DroidSansFallback-Oblique.ttf"		,
	["Roboto-Medium.ttf"						] = "DroidSansFallback.ttf"				,
	["Roboto-MediumItalic.ttf"					] = "DroidSansFallback-Oblique.ttf"		,
	["Roboto-Regular.ttf"						] = "DroidSansFallback.ttf"				,
	["Roboto-Thin.ttf"							] = "DroidSansFallback.ttf"				,
	["Roboto-ThinItalic.ttf"					] = "DroidSansFallback-Oblique.ttf"		,
	["arial.ttf"								] = "DroidSansFallback.ttf"				,
	["ariali.ttf"								] = "DroidSansFallback-Oblique.ttf"		,
	["arialbd.ttf"								] = "DroidSansFallback-Bold.ttf"		,
	["arialbi.ttf"								] = "DroidSansFallback-BoldOblique.ttf"	,
	["ariblk.ttf"								] = "DroidSansFallback-Bold.ttf"		,
}

