dofile(LockOn_Options.script_path.."CDU/indicator/CDU_definitions.lua")

AddStaticText("PageNameDIVERT",  2, 1, LFT, "DIVERT")

AddText		 ("DIVERTSteerNOT",  1,  3, LFT, {{"DIVERTSteerNOT", 0}}, SYS_ACTION)
AddText		 ("DIVERTNumber",    2,  3, LFT, {{"DIVERTNumber", 0}})
AddText		 ("DIVERTName",      7,  3, LFT, {{"DIVERTName", 0}})
AddText		 ("DIVERTSteer",    23,  3, RGHT, {{"DIVERTSteer", 0}}, "(SP)")
AddText		 ("DIVERTMH",        2,  4, LFT, {{"DIVERTMH", 0}})
AddText      ("DIVERTDIV",	     5,  4, LFT, {{"DIVERTPresent", 0}}, "/")
AddText		 ("DIVERTDistance",  6,  4, LFT, {{"DIVERTDistance", 0}})
AddText      ("DIVERTTTGText",  12,  4, LFT, {{"DIVERTPresent", 0}}, "TTG:")
AddText		 ("DIVERTTTG",      17,  4, LFT, {{"DIVERTPresent", 0}, {"NotMoving", 0, 3}}, "********")
AddText		 ("DIVERTTTG1",      17,  4, LFT, {{"NotMoving", 1, 3}, {"DIVERTTTG", 0}})

AddText		 ("DIVERTSteerNOT1",  1,  5, LFT, {{"DIVERTSteerNOT", 1}}, SYS_ACTION)
AddText		 ("DIVERTNumber1",    2,  5, LFT, {{"DIVERTNumber", 1}})
AddText		 ("DIVERTName1",      7,  5, LFT, {{"DIVERTName", 1}})
AddText		 ("DIVERTSteer1",    23,  5, RGHT, {{"DIVERTSteer", 1}}, "(SP)")
AddText		 ("DIVERTMH1",        2,  6, LFT, {{"DIVERTMH", 1}})
AddText      ("DIVERTDIV1",	     5,  6, LFT, {{"DIVERTPresent", 1}}, "/")
AddText		 ("DIVERTDistance1",  6,  6, LFT, {{"DIVERTDistance", 1}})
AddText      ("DIVERTTTGText1",  12,  6, LFT, {{"DIVERTPresent", 1}}, "TTG:")
AddText		 ("DIVERTTTG2",      17,  6, LFT, {{"DIVERTPresent", 1}, {"NotMoving", 0, 3}}, "********")
AddText		 ("DIVERTTTG3",      17,  6, LFT, {{"NotMoving", 1, 3}, {"DIVERTTTG", 1}})

AddText		 ("DIVERTSteerNOT2",  1,  7, LFT, {{"DIVERTSteerNOT", 2}}, SYS_ACTION)
AddText		 ("DIVERTNumber2",    2,  7, LFT, {{"DIVERTNumber", 2}})
AddText		 ("DIVERTName2",      7,  7, LFT, {{"DIVERTName", 2}})
AddText		 ("DIVERTSteer2",    23,  7, RGHT, {{"DIVERTSteer", 2}}, "(SP)")
AddText		 ("DIVERTMH2",        2,  8, LFT, {{"DIVERTMH", 2}})
AddText      ("DIVERTDIV2",	     5,  8, LFT, {{"DIVERTPresent", 2}}, "/")
AddText		 ("DIVERTDistance2",  6,  8, LFT, {{"DIVERTDistance", 2}})
AddText      ("DIVERTTTGText2",  12,  8, LFT, {{"DIVERTPresent", 2}}, "TTG:")
AddText		 ("DIVERTTTG4",      17,  8, LFT, {{"DIVERTPresent", 2}, {"NotMoving", 0, 3}}, "********")
AddText		 ("DIVERTTTG5",      17,  8, LFT, {{"NotMoving", 1, 3}, {"DIVERTTTG", 2}})

AddText		 ("DIVERTSteerNOT3",  1,  9, LFT, {{"DIVERTSteerNOT", 3}}, SYS_ACTION)
AddText		 ("DIVERTNumber3",    2,  9, LFT, {{"DIVERTNumber", 3}})
AddText		 ("DIVERTName3",      7,  9, LFT, {{"DIVERTName", 3}})
AddText		 ("DIVERTSteer3",    23,  9, RGHT, {{"DIVERTSteer", 3}}, "(SP)")
AddText		 ("DIVERTMH3",        2, 10, LFT, {{"DIVERTMH", 3}})
AddText      ("DIVERTDIV3",	     5, 10, LFT, {{"DIVERTPresent", 3}}, "/")
AddText		 ("DIVERTDistance3",  6, 10, LFT, {{"DIVERTDistance", 3}})
AddText      ("DIVERTTTGText3",  12, 10, LFT, {{"DIVERTPresent", 3}}, "TTG:")
AddText		 ("DIVERTTTG6",      17, 10, LFT, {{"DIVERTPresent", 3}, {"NotMoving", 0, 3}}, "********")
AddText		 ("DIVERTTTG7",      17, 10, LFT, {{"NotMoving", 1, 3}, {"DIVERTTTG", 3}})

add_static_hint_CDU("L1", _("Make displayed diversion waypoint the steerpoint (regardless of AAP setting)"))
add_static_hint_CDU("L2", _("Make displayed diversion waypoint the steerpoint (regardless of AAP setting)"))
add_static_hint_CDU("L3", _("Make displayed diversion waypoint the steerpoint (regardless of AAP setting)"))
add_static_hint_CDU("L4", _("Make displayed diversion waypoint the steerpoint (regardless of AAP setting)"))
