dofile(LockOn_Options.script_path.."CDU/indicator/CDU_definitions.lua")

AddStaticText("PageNameFLDINFO",    2, 1, LFT, "FLDINFO")
AddStaticText("ELEVATION", 		   16, 4, LFT, "ELEV:")
AddStaticText("RWY",                2, 6, LFT, "RWY:")
AddStaticText("RWY_L_FEET",        24, 6, RGHT, "(     )")
AddStaticText("ILS",                2, 7, LFT, "ILS:")
AddStaticText("TAC",                2, 8, LFT, "TAC:")
AddStaticText("APP",                2, 9, LFT, "APP:")
AddStaticText("SLASH1",            14, 9, LFT, "/")
AddStaticText("ILS1",                2, 10, LFT,"TWR:")
AddStaticText("SLASH2",            14, 10, LFT, "/")

AddText("FLDINFO_ID",               2, 3, LFT, {{"FLDINFOIdentifier"}})
AddText("FLDINFO_NUM",             16, 3, LFT, {{"FLDINFONumber"}})
AddText("FLDINFO_Name",             2, 4, LFT, {{"FLDINFOName"}})
AddText("FLDINFO_ELEV",            21, 4, LFT, {{"FLDINFOElevation"}})
AddText("FLDINFO_RWY_LNG",         19, 6, LFT, {{"FLDINFORunwayLength"}})
AddText("FLDINFO_RWY_HD",           7, 6, LFT, {{"FLDINFORunwayHead", 1}})
AddText("FLDINFO_RWY_HD2",         15, 6, LFT, {{"FLDINFORunwayHead", 0}})
AddText("FLDINFO_ILS1",             7, 7, LFT, {{"FLDINFOFrequencyILS", 0}})
AddText("FLDINFO_ILS2",            15, 7, LFT, {{"FLDINFOFrequencyILS", 1}})
AddText("FLDINFO_TAC_CHAN",         7, 8, LFT, {{"FLDINFOChannelTacan"}})
AddText("FLDINFO_TAC_OFF",         11, 8, LFT, {{"FLDINFOTacanPresent"}}, "OFF FIELD")
AddText("FLDINFO_APP_UHF",          7, 9, LFT, {{"FLDINFOApproachUHF"}})
AddText("FLDINFO_APP_VHF",         15, 9, LFT, {{"FLDINFOApproachVHF"}})
AddText("FLDINFO_TWR_UHF",          7,10, LFT, {{"FLDINFOTowerUHF"}})
AddText("FLDINFO_TWR_VHF",         15,10, LFT, {{"FLDINFOTowerVHF"}})
