
declare_weapon({
    category       = CAT_SHELLS,
    name           = "ZTZ_125_AP",
    user_name      = _("125mm AP"),
    model_name     = "kinetic_type1",
    v0             = 1680.0,
    Dv0            = 0.0010,
    Da0            = 0.00025,
    Da1            = 0.0000,
    mass           = 5.35,
    explosive      = 0,
    life_time      = 100,
    caliber        = 125.0,
    AP_cap_caliber = 31.0,
    subcalibre     = true,
    s              = 0.0,
    j              = 0.0,
    l              = 0.0,
    charTime       = 0,
    cx             = {1.0,1.40,0.81,0.172,1.59},
    k1             = 2.2e-10,
    tracer_off     = 100,
    scale_tracer   = 0,
    rotation_freq  = 0,
    cartridge = 0,

})

declare_weapon({

    category       = CAT_SHELLS,
    name           = "ZTZ_125_HE",
    user_name      = _("125mm HE"),
    model_name     = "pula",
    v0             = 800.0,
    Dv0            = 0.0020,
    Da0            = 0.00025,
    Da1            = 0.0002,
    mass           = 23,
    explosive      = 23, -- 3.4 kg in real
    life_time      = 100,
    caliber        = 125.0,
    s              = 0.0,
    j              = 0.0,
    l              = 0.0,
    charTime       = 0,
    cx             = {1.0,0.62,0.65,0.3,1.45},
    k1             = 1.3e-09,
    tracer_off     = 100,
    scale_tracer   = 0,
    rotation_freq  = 0,
    cartridge      = 0,
    aiming_table   = {
        [1] = {
            init_vel = 800,
            aiming_data = {
                {
                    distance    = 0,
                    elevation   = 0,
                    angle_hit   = 0,
                    fly_time    = 0,
                    MO          = 0,
                    cwindY      = 0,
                    cwindX      = 0,
                    celevation  = 0,
                    alt_to_dist_correction = 0,
                },
                {
                    distance    = 1350,
                    elevation   = 0.5,
                    angle_hit   = 0.6,
                    fly_time    = 1.1,
                    MO          = 7,
                    cwindY      = 0.1,
                    cwindX      = -0.08,
                    celevation  = 0,
                    alt_to_dist_correction = 7.0,
                },
                {
                    distance    = 2350,
                    elevation   = 1.03,
                    angle_hit   = 1.11,
                    fly_time    = 2.37,
                    MO          = 7,
                    cwindY      = 0.22,
                    cwindX      = -0.19,
                    celevation  = 0,
                    alt_to_dist_correction = 14.6,
                },
                {
                    distance    = 3350.0,
                    elevation   = 1.615,
                    angle_hit   = 2.02,
                    fly_time    = 4.76,
                    MO          = 28.0,
                    cwindY      = 0.54,
                    cwindX      = -0.44,
                    celevation  = 0,
                    alt_to_dist_correction = 38.2,
                },
                {
                    distance    = 4050.0,
                    elevation   = 2.07,
                    angle_hit   = 4.05,
                    fly_time    = 5.62,
                    MO          = 43.8,
                    cwindY      = 1.23,
                    cwindX      = -0.61,
                    celevation  = 0,
                    alt_to_dist_correction = 102,
                },
                {
                    distance    = 4780.0,
                    elevation   = 2.644,
                    angle_hit   = 7.23,
                    fly_time    = 7.5,
                    MO          = 66,
                    cwindY      = 1.69,
                    cwindX      = -1.39,
                    celevation  = 0,
                    alt_to_dist_correction = 209.8,
                },
                {
                    distance    = 5200.0,
                    elevation   = 3.05,
                    angle_hit   = 11.29,
                    fly_time    = 8.34,
                    MO          = 87,
                    cwindY      = 3.8,
                    cwindX      = -3.5,
                    celevation  = 0,
                    alt_to_dist_correction = 312.4,
                },
                {
                    distance    = 6410.0,
                    elevation   = 4.25,
                    angle_hit   = 15.55,
                    fly_time    = 11.57,
                    MO          = 140.0,
                    cwindY      = 5.51,
                    cwindX      = -6.2,
                    celevation  = 0,
                    alt_to_dist_correction = 388.1,
                },
                {
                    distance    = 7080.0,
                    elevation   = 5.0,
                    angle_hit   = 19.91,
                    fly_time    = 13.0,
                    MO          = 211.2,
                    cwindY      = 8.59,
                    cwindX      = -9.52,
                    celevation  = 0,
                    alt_to_dist_correction = 446.4,
                },
                {
                    distance    = 9488.8,
                    elevation   = 13.73,
                    angle_hit   = 24.25,
                    fly_time    = 24.96,
                    MO          = 829.1,
                    cwindY      = 10.74,
                    cwindX      = -13.16,
                    celevation  = 0,
                    alt_to_dist_correction = 494.7,
                },
            },
        },
    }
})

declare_weapon({

    category      = CAT_SHELLS,
    name          = "ZTZ_7_62",
    user_name     = _("7.62mm"),
    model_name    = "tracer_bullet_red",
    v0            = 900.0,
    Dv0           = 0.0082,
    Da0           = 0.0004,
    Da1           = 0.0,
    mass          = 0.0096,
    explosive     = 0.0000,
    life_time     = 7,
    caliber       = 7.62,
    s             = 0.0,
    j             = 0.0,
    l             = 0.0,
    charTime      = 0,
    cx            = {1.0,0.62,0.65,0.175,1.8},
    k1            = 2.9e-08,
    tracer_off    = 4,
    scale_tracer  = 1,
    cartridge     = 0,
})

declare_weapon({

    category      = CAT_SHELLS,
    name          = "ZTZ_14_5",
    user_name     = _("14.5mm"),
    model_name    = "tracer_bullet_green",
    v0            = 800.0,
    Dv0           = 0.0050,
    Da0           = 0.0008,
    Da1           = 0.0,
    mass          = 0.064,
    explosive     = 0.0000,
    life_time     = 11,
    caliber       = 14.5,
    s             = 0.0,
    j             = 0.0,
    l             = 0.0,
    charTime      = 0,
    cx            = {0,0.68,0.75,0.27,2.0},
    k1            = 9.7e-09,
    tracer_off    = 4,
    scale_tracer  = 1,
    cartridge = 0,
})


-- 155mm for PLZ-05
declare_weapon({
    category       = CAT_SHELLS,
    name           = "PLZ_155_HE",
    user_name      = _("155mm HE"),
    model_name     = "pula",
    v0             = 562.0,
    Dv0            = 0.0030,
    Da0            = 0.0010,
    Da1            = 0.00044,
    mass           = 42.9,
    explosive      = 42.9, -- 6.800 kg in real
    life_time      = 100,
    caliber        = 155.0,
    s              = 0.0,
    j              = 0.0,
    l              = 0.0,
    charTime       = 0,
    cx             = {1.0,0.59,0.89,0.172,1.69},
    k1             = 2.5e-09,
    tracer_off     = 100,
    scale_tracer   = 0,
    rotation_freq  = 0,
    cartridge      = 0,
    aiming_table   = {
        --precalculateAimingTable = true,
        [1] = {
            init_vel = 200,
            aiming_data = {
                {
                    distance    = 0,
                    elevation   = 0,
                    angle_hit   = 0,
                    fly_time    = 0,
                    MO          = 0,
                    cwindY      = 0,
                    cwindX      = 0,
                    celevation  = 0,
                    alt_to_dist_correction = 0,
                },
                {
                    distance    = 141.8,
                    elevation   = 1,
                    angle_hit   = 1.03,
                    fly_time    = 0.69,
                    MO          = 0.6,
                    cwindY      = 0,
                    cwindX      = -0.01,
                    celevation  = 0,
                    alt_to_dist_correction = 0.1,
                },
                {
                    distance    = 238.5,
                    elevation   = 1.69,
                    angle_hit   = 1.7,
                    fly_time    = 1.16,
                    MO          = 1.8,
                    cwindY      = 0.01,
                    cwindX      = -0.02,
                    celevation  = 0,
                    alt_to_dist_correction = 0.2,
                },
                {
                    distance    = 413.4,
                    elevation   = 2.94,
                    angle_hit   = 3.01,
                    fly_time    = 2.07,
                    MO          = 5.4,
                    cwindY      = 0.02,
                    cwindX      = -0.05,
                    celevation  = 0,
                    alt_to_dist_correction = 0.5,
                },
                {
                    distance    = 635.9,
                    elevation   = 4.57,
                    angle_hit   = 4.67,
                    fly_time    = 3.2,
                    MO          = 12.8,
                    cwindY      = 0.05,
                    cwindX      = -0.11,
                    celevation  = 0,
                    alt_to_dist_correction = 1.1,
                },
                {
                    distance    = 892.9,
                    elevation   = 6.5,
                    angle_hit   = 6.72,
                    fly_time    = 4.57,
                    MO          = 25.8,
                    cwindY      = 0.09,
                    cwindX      = -0.22,
                    celevation  = 0,
                    alt_to_dist_correction = 2.2,
                },
                {
                    distance    = 1174.7,
                    elevation   = 8.69,
                    angle_hit   = 9.04,
                    fly_time    = 6.09,
                    MO          = 45.7,
                    cwindY      = 0.16,
                    cwindX      = -0.38,
                    celevation  = 0,
                    alt_to_dist_correction = 3.8,
                },
                {
                    distance    = 1473,
                    elevation   = 11.1,
                    angle_hit   = 11.64,
                    fly_time    = 7.75,
                    MO          = 73.9,
                    cwindY      = 0.26,
                    cwindX      = -0.59,
                    celevation  = 0,
                    alt_to_dist_correction = 6,
                },
                {
                    distance    = 1779.7,
                    elevation   = 13.73,
                    angle_hit   = 14.51,
                    fly_time    = 9.53,
                    MO          = 111.8,
                    cwindY      = 0.39,
                    cwindX      = -0.87,
                    celevation  = 0,
                    alt_to_dist_correction = 8.8,
                },
                {
                    distance    = 2086.9,
                    elevation   = 16.56,
                    angle_hit   = 17.61,
                    fly_time    = 11.41,
                    MO          = 160.2,
                    cwindY      = 0.55,
                    cwindX      = -1.21,
                    celevation  = 0.139743,
                    alt_to_dist_correction = 12,
                },
                {
                    distance    = 2386.6,
                    elevation   = 19.56,
                    angle_hit   = 20.94,
                    fly_time    = 13.36,
                    MO          = 220,
                    cwindY      = 0.73,
                    cwindX      = -1.6,
                    celevation  = 0.174679,
                    alt_to_dist_correction = 15.8,
                },
                {
                    distance    = 2670.7,
                    elevation   = 22.74,
                    angle_hit   = 24.51,
                    fly_time    = 15.42,
                    MO          = 291.6,
                    cwindY      = 0.95,
                    cwindX      = -2.04,
                    celevation  = 0.218349,
                    alt_to_dist_correction = 19.8,
                },
                {
                    distance    = 2931,
                    elevation   = 26.08,
                    angle_hit   = 28.19,
                    fly_time    = 17.46,
                    MO          = 375.2,
                    cwindY      = 1.18,
                    cwindX      = -2.51,
                    celevation  = 0.384294,
                    alt_to_dist_correction = 24,
                },
                {
                    distance    = 3159.1,
                    elevation   = 29.58,
                    angle_hit   = 32.05,
                    fly_time    = 19.57,
                    MO          = 470.6,
                    cwindY      = 1.43,
                    cwindX      = -2.99,
                    celevation  = 0.593897,
                    alt_to_dist_correction = 28.2,
                },
                {
                    distance    = 3346.8,
                    elevation   = 33.22,
                    angle_hit   = 36,
                    fly_time    = 21.66,
                    MO          = 577.1,
                    cwindY      = 1.69,
                    cwindX      = -3.46,
                    celevation  = 1.082989,
                    alt_to_dist_correction = 32,
                },
                {
                    distance    = 3486.2,
                    elevation   = 37.01,
                    angle_hit   = 40.07,
                    fly_time    = 23.77,
                    MO          = 693.5,
                    cwindY      = 1.96,
                    cwindX      = -3.91,
                    celevation  = 0,
                    alt_to_dist_correction = 35.4,
                },
                {
                    distance    = 3569.5,
                    elevation   = 40.94,
                    angle_hit   = 44.13,
                    fly_time    = 25.8,
                    MO          = 818.4,
                    cwindY      = 2.21,
                    cwindX      = -4.3,
                    celevation  = 0,
                    alt_to_dist_correction = 37.9,
                },
                {
                    distance    = 3589.5,
                    elevation   = 45,
                    angle_hit   = 48.26,
                    fly_time    = 27.81,
                    MO          = 949.6,
                    cwindY      = 2.45,
                    cwindX      = -4.63,
                    celevation  = 0,
                    alt_to_dist_correction = 39.5,
                },
            },
        },
        [2] = {
            init_vel = 316,
            aiming_data = {
                {
                    distance    = 0,
                    elevation   = 0,
                    angle_hit   = 0,
                    fly_time    = 0,
                    MO          = 0,
                    cwindY      = 0,
                    cwindX      = 0,
                    celevation  = 0,
                    alt_to_dist_correction = 0,
                },
                {
                    distance    = 351.6,
                    elevation   = 1,
                    angle_hit   = 1.04,
                    fly_time    = 1.12,
                    MO          = 1.5,
                    cwindY      = 0.01,
                    cwindX      = -0.03,
                    celevation  = 0,
                    alt_to_dist_correction = 0.3,
                },
                {
                    distance    = 588.8,
                    elevation   = 1.69,
                    angle_hit   = 1.74,
                    fly_time    = 1.87,
                    MO          = 4.4,
                    cwindY      = 0.03,
                    cwindX      = -0.08,
                    celevation  = 0,
                    alt_to_dist_correction = 0.9,
                },
                {
                    distance    = 1012.6,
                    elevation   = 2.94,
                    angle_hit   = 3.06,
                    fly_time    = 3.27,
                    MO          = 13.2,
                    cwindY      = 0.08,
                    cwindX      = -0.24,
                    celevation  = 0,
                    alt_to_dist_correction = 2.7,
                },
                {
                    distance    = 1542.5,
                    elevation   = 4.57,
                    angle_hit   = 4.8,
                    fly_time    = 5.04,
                    MO          = 31.6,
                    cwindY      = 0.18,
                    cwindX      = -0.52,
                    celevation  = 0,
                    alt_to_dist_correction = 6.2,
                },
                {
                    distance    = 2142.2,
                    elevation   = 6.5,
                    angle_hit   = 6.95,
                    fly_time    = 7.15,
                    MO          = 63.1,
                    cwindY      = 0.35,
                    cwindX      = -0.95,
                    celevation  = 0,
                    alt_to_dist_correction = 12,
                },
                {
                    distance    = 2785.5,
                    elevation   = 8.69,
                    angle_hit   = 9.45,
                    fly_time    = 9.48,
                    MO          = 111,
                    cwindY      = 0.6,
                    cwindX      = -1.55,
                    celevation  = 0,
                    alt_to_dist_correction = 20.3,
                },
                {
                    distance    = 3451.2,
                    elevation   = 11.1,
                    angle_hit   = 12.33,
                    fly_time    = 12.05,
                    MO          = 178.5,
                    cwindY      = 0.94,
                    cwindX      = -2.3,
                    celevation  = 0,
                    alt_to_dist_correction = 31.2,
                },
                {
                    distance    = 4120.7,
                    elevation   = 13.73,
                    angle_hit   = 15.52,
                    fly_time    = 14.78,
                    MO          = 268,
                    cwindY      = 1.36,
                    cwindX      = -3.21,
                    celevation  = 0,
                    alt_to_dist_correction = 44.4,
                },
                {
                    distance    = 4776.9,
                    elevation   = 16.56,
                    angle_hit   = 18.96,
                    fly_time    = 17.6,
                    MO          = 381.6,
                    cwindY      = 1.87,
                    cwindX      = -4.26,
                    celevation  = 0.078605,
                    alt_to_dist_correction = 59.7,
                },
                {
                    distance    = 5404.2,
                    elevation   = 19.56,
                    angle_hit   = 22.69,
                    fly_time    = 20.56,
                    MO          = 520.7,
                    cwindY      = 2.45,
                    cwindX      = -5.42,
                    celevation  = 0.174679,
                    alt_to_dist_correction = 76.3,
                },
                {
                    distance    = 5987.7,
                    elevation   = 22.74,
                    angle_hit   = 26.66,
                    fly_time    = 23.64,
                    MO          = 686,
                    cwindY      = 3.1,
                    cwindX      = -6.66,
                    celevation  = 0.218349,
                    alt_to_dist_correction = 93.7,
                },
                {
                    distance    = 6513,
                    elevation   = 26.08,
                    angle_hit   = 30.71,
                    fly_time    = 26.7,
                    MO          = 877.6,
                    cwindY      = 3.79,
                    cwindX      = -7.92,
                    celevation  = 0.384294,
                    alt_to_dist_correction = 111.1,
                },
                {
                    distance    = 6966,
                    elevation   = 29.58,
                    angle_hit   = 34.87,
                    fly_time    = 29.82,
                    MO          = 1094.7,
                    cwindY      = 4.51,
                    cwindX      = -9.18,
                    celevation  = 0.593897,
                    alt_to_dist_correction = 127.7,
                },
                {
                    distance    = 7332.6,
                    elevation   = 33.22,
                    angle_hit   = 39.1,
                    fly_time    = 32.98,
                    MO          = 1335.9,
                    cwindY      = 5.24,
                    cwindX      = -10.38,
                    celevation  = 1.152859,
                    alt_to_dist_correction = 143,
                },
                {
                    distance    = 7599,
                    elevation   = 37.01,
                    angle_hit   = 43.28,
                    fly_time    = 36.08,
                    MO          = 1598.6,
                    cwindY      = 5.96,
                    cwindX      = -11.48,
                    celevation  = 0,
                    alt_to_dist_correction = 155.9,
                },
                {
                    distance    = 7751.2,
                    elevation   = 40.94,
                    angle_hit   = 47.4,
                    fly_time    = 39.12,
                    MO          = 1879.5,
                    cwindY      = 6.65,
                    cwindX      = -12.42,
                    celevation  = 0,
                    alt_to_dist_correction = 165.3,
                },
                {
                    distance    = 7775.4,
                    elevation   = 45,
                    angle_hit   = 51.45,
                    fly_time    = 42.08,
                    MO          = 2174.1,
                    cwindY      = 7.29,
                    cwindX      = -13.15,
                    celevation  = 0,
                    alt_to_dist_correction = 170.9,
                },
            },
        },
        [3] = {
            init_vel = 562,
            aiming_data = {
                {
                    distance    = 0,
                    elevation   = 0,
                    angle_hit   = 0,
                    fly_time    = 0,
                    MO          = 0,
                    cwindY      = 0,
                    cwindX      = 0,
                    celevation  = 0,
                    alt_to_dist_correction = 0,
                },
                {
                    distance    = 1032.3,
                    elevation   = 1,
                    angle_hit   = 1.09,
                    fly_time    = 1.92,
                    MO          = 4.7,
                    cwindY      = 0.12,
                    cwindX      = -0.23,
                    celevation  = 0,
                    alt_to_dist_correction = 8,
                },
                {
                    distance    = 1653.6,
                    elevation   = 1.69,
                    angle_hit   = 1.93,
                    fly_time    = 3.23,
                    MO          = 13,
                    cwindY      = 0.31,
                    cwindX      = -0.69,
                    celevation  = 0,
                    alt_to_dist_correction = 18.8,
                },
                {
                    distance    = 2657.6,
                    elevation   = 2.94,
                    angle_hit   = 3.57,
                    fly_time    = 5.51,
                    MO          = 37.8,
                    cwindY      = 0.8,
                    cwindX      = -2.01,
                    celevation  = 0,
                    alt_to_dist_correction = 42,
                },
                {
                    distance    = 3783.1,
                    elevation   = 4.57,
                    angle_hit   = 5.83,
                    fly_time    = 8.31,
                    MO          = 86.2,
                    cwindY      = 1.58,
                    cwindX      = -4.22,
                    celevation  = 0,
                    alt_to_dist_correction = 72.1,
                },
                {
                    distance    = 4946.6,
                    elevation   = 6.5,
                    angle_hit   = 8.6,
                    fly_time    = 11.45,
                    MO          = 164.7,
                    cwindY      = 2.62,
                    cwindX      = -7.14,
                    celevation  = 0,
                    alt_to_dist_correction = 105.3,
                },
                {
                    distance    = 6113.3,
                    elevation   = 8.69,
                    angle_hit   = 11.8,
                    fly_time    = 14.85,
                    MO          = 278.4,
                    cwindY      = 3.87,
                    cwindX      = -10.55,
                    celevation  = 0,
                    alt_to_dist_correction = 139.8,
                },
                {
                    distance    = 7264.9,
                    elevation   = 11.1,
                    angle_hit   = 15.36,
                    fly_time    = 18.45,
                    MO          = 431.3,
                    cwindY      = 5.3,
                    cwindX      = -14.3,
                    celevation  = 0,
                    alt_to_dist_correction = 175.1,
                },
                {
                    distance    = 8387.9,
                    elevation   = 13.73,
                    angle_hit   = 19.19,
                    fly_time    = 22.2,
                    MO          = 626.8,
                    cwindY      = 6.87,
                    cwindX      = -18.24,
                    celevation  = 0,
                    alt_to_dist_correction = 211.4,
                },
                {
                    distance    = 9469.5,
                    elevation   = 16.56,
                    angle_hit   = 23.27,
                    fly_time    = 26.13,
                    MO          = 867.7,
                    cwindY      = 8.57,
                    cwindX      = -22.26,
                    celevation  = 0.04367,
                    alt_to_dist_correction = 249.1,
                },
                {
                    distance    = 10497.1,
                    elevation   = 19.56,
                    angle_hit   = 27.5,
                    fly_time    = 30.18,
                    MO          = 1156.2,
                    cwindY      = 10.36,
                    cwindX      = -26.27,
                    celevation  = 0.139743,
                    alt_to_dist_correction = 289.2,
                },
                {
                    distance    = 11455.7,
                    elevation   = 22.74,
                    angle_hit   = 31.78,
                    fly_time    = 34.28,
                    MO          = 1493.5,
                    cwindY      = 12.22,
                    cwindX      = -30.15,
                    celevation  = 0.174679,
                    alt_to_dist_correction = 332.7,
                },
                {
                    distance    = 12329,
                    elevation   = 26.08,
                    angle_hit   = 36.12,
                    fly_time    = 38.54,
                    MO          = 1880.2,
                    cwindY      = 14.12,
                    cwindX      = -33.8,
                    celevation  = 0.279486,
                    alt_to_dist_correction = 377.9,
                },
                {
                    distance    = 13097,
                    elevation   = 29.58,
                    angle_hit   = 40.37,
                    fly_time    = 42.81,
                    MO          = 2316.1,
                    cwindY      = 16.03,
                    cwindX      = -37.11,
                    celevation  = 0.419222,
                    alt_to_dist_correction = 424.5,
                },
                {
                    distance    = 13737.4,
                    elevation   = 33.22,
                    angle_hit   = 44.49,
                    fly_time    = 47.1,
                    MO          = 2799.3,
                    cwindY      = 17.92,
                    cwindX      = -40.02,
                    celevation  = 0.768573,
                    alt_to_dist_correction = 469.6,
                },
                {
                    distance    = 14225.8,
                    elevation   = 37.01,
                    angle_hit   = 48.49,
                    fly_time    = 51.43,
                    MO          = 3326.6,
                    cwindY      = 19.75,
                    cwindX      = -42.41,
                    celevation  = 0,
                    alt_to_dist_correction = 509.8,
                },
                {
                    distance    = 14533.3,
                    elevation   = 40.94,
                    angle_hit   = 52.31,
                    fly_time    = 55.71,
                    MO          = 3892.6,
                    cwindY      = 21.49,
                    cwindX      = -44.23,
                    celevation  = 0,
                    alt_to_dist_correction = 542.7,
                },
                {
                    distance    = 14629.1,
                    elevation   = 45,
                    angle_hit   = 55.96,
                    fly_time    = 59.92,
                    MO          = 4489.9,
                    cwindY      = 23.11,
                    cwindX      = -45.33,
                    celevation  = 0,
                    alt_to_dist_correction = 565.9,
                },
            },
        },
        [4] = {
            init_vel = 865,
            aiming_data = {
                {
                    distance    = 0,
                    elevation   = 0,
                    angle_hit   = 0,
                    fly_time    = 0,
                    MO          = 0,
                    cwindY      = 0,
                    cwindX      = 0,
                    celevation  = 0,
                    alt_to_dist_correction = 0,
                },
                {
                    distance    = 2370,
                    elevation   = 1,
                    angle_hit   = 1.13,
                    fly_time    = 2.97,
                    MO          = 11,
                    cwindY      = 0.25,
                    cwindX      = -0.19,
                    celevation  = 0,
                    alt_to_dist_correction = 27.7,
                },
                {
                    distance    = 3707,
                    elevation   = 1.69,
                    angle_hit   = 2.07,
                    fly_time    = 4.92,
                    MO          = 30,
                    cwindY      = 0.67,
                    cwindX      = -0.5,
                    celevation  = 0,
                    alt_to_dist_correction = 70.6,
                },
                {
                    distance    = 5673,
                    elevation   = 2.94,
                    angle_hit   = 4.19,
                    fly_time    = 8.37,
                    MO          = 85.6,
                    cwindY      = 1.82,
                    cwindX      = -1.33,
                    celevation  = 0,
                    alt_to_dist_correction = 178.8,
                },
                {
                    distance    = 7564.7,
                    elevation   = 4.57,
                    angle_hit   = 7.51,
                    fly_time    = 12.48,
                    MO          = 190.8,
                    cwindY      = 3.71,
                    cwindX      = -3.19,
                    celevation  = 0,
                    alt_to_dist_correction = 328,
                },
                {
                    distance    = 9280.5,
                    elevation   = 6.5,
                    angle_hit   = 11.57,
                    fly_time    = 16.79,
                    MO          = 353.9,
                    cwindY      = 6.01,
                    cwindX      = -6.19,
                    celevation  = 0,
                    alt_to_dist_correction = 462.1,
                },
                {
                    distance    = 10868,
                    elevation   = 8.69,
                    angle_hit   = 16.01,
                    fly_time    = 21.23,
                    MO          = 579.1,
                    cwindY      = 8.54,
                    cwindX      = -9.9,
                    celevation  = 0,
                    alt_to_dist_correction = 574,
                },
                {
                    distance    = 12362,
                    elevation   = 11.1,
                    angle_hit   = 20.68,
                    fly_time    = 25.76,
                    MO          = 868,
                    cwindY      = 11.23,
                    cwindX      = -14,
                    celevation  = 0,
                    alt_to_dist_correction = 673,
                },
                {
                    distance    = 13782,
                    elevation   = 13.73,
                    angle_hit   = 25.45,
                    fly_time    = 30.43,
                    MO          = 1223,
                    cwindY      = 14.05,
                    cwindX      = -18.35,
                    celevation  = 0,
                    alt_to_dist_correction = 766,
                },
                {
                    distance    = 15135,
                    elevation   = 16.56,
                    angle_hit   = 30.18,
                    fly_time    = 35.19,
                    MO          = 1647.8,
                    cwindY      = 16.95,
                    cwindX      = -22.87,
                    celevation  = 0.035,
                    alt_to_dist_correction = 858,
                },
                {
                    distance    = 16425,
                    elevation   = 19.56,
                    angle_hit   = 34.81,
                    fly_time    = 40.08,
                    MO          = 2142,
                    cwindY      = 19.93,
                    cwindX      = -27.48,
                    celevation  = 0.0087,
                    alt_to_dist_correction = 947.6,
                },
                {
                    distance    = 17644,
                    elevation   = 22.74,
                    angle_hit   = 39.22,
                    fly_time    = 45.05,
                    MO          = 2709,
                    cwindY      = 22.95,
                    cwindX      = -36.72,
                    celevation  = 0.06987,
                    alt_to_dist_correction = 1039,
                },
                {
                    distance    = 18784,
                    elevation   = 26.08,
                    angle_hit   = 43.4,
                    fly_time    = 50.16,
                    MO          = 3351,
                    cwindY      = 26,
                    cwindX      = -36.72,
                    celevation  = 0.1048,
                    alt_to_dist_correction = 1132,
                },
                {
                    distance    = 19827,
                    elevation   = 29.58,
                    angle_hit   = 47.31,
                    fly_time    = 55.36,
                    MO          = 4067,
                    cwindY      = 29,
                    cwindX      = -41.24,
                    celevation  = 0.209,
                    alt_to_dist_correction = 1227,
                },
                {
                    distance    = 20747,
                    elevation   = 33.22,
                    angle_hit   = 51,
                    fly_time    = 60.62,
                    MO          = 4858,
                    cwindY      = 32,
                    cwindX      = -45.53,
                    celevation  = 0.349,
                    alt_to_dist_correction = 1326.5,
                },
                {
                    distance    = 21513,
                    elevation   = 37.01,
                    angle_hit   = 54.35,
                    fly_time    = 66,
                    MO          = 5720,
                    cwindY      = 35,
                    cwindX      = -50,
                    celevation  = 0.768,
                    alt_to_dist_correction = 1426,
                },
                {
                    distance    = 22076,
                    elevation   = 40.94,
                    angle_hit   = 57.54,
                    fly_time    = 71.42,
                    MO          = 6651,
                    cwindY      = 37.67,
                    cwindX      = -52.93,
                    celevation  = 0,
                    alt_to_dist_correction = 1526,
                },
                {
                    distance    = 22377,
                    elevation   = 45,
                    angle_hit   = 61,
                    fly_time    = 77,
                    MO          = 7641,
                    cwindY      = 40.31,
                    cwindX      = -55.66,
                    celevation  = 0,
                    alt_to_dist_correction = 1624,
                },
            },
        },
    }
})
