JESTER_DEFAULT_LEVEL = 5
JESTER_NOCLIP_LEVEL = JESTER_DEFAULT_LEVEL - 1

HUD_DEFAULT_LEVEL = 9
HUD_NOCLIP_LEVEL  = HUD_DEFAULT_LEVEL - 1

DDD_DEFAULT_LEVEL = 15
DDD_NOCLIP_LEVEL  = DDD_DEFAULT_LEVEL

HSD_DEFAULT_LEVEL = 20
HSD_NOCLIP_LEVEL  = HSD_DEFAULT_LEVEL

TID_DEFAULT_LEVEL = 25
TID_NOCLIP_LEVEL = TID_DEFAULT_LEVEL - 1

VDI_DEFAULT_LEVEL = 30
VDI_NOCLIP_LEVEL  = VDI_DEFAULT_LEVEL - 1

RWR_DEFAULT_LEVEL = 35
RWR_NOCLIP_LEVEL = RWR_DEFAULT_LEVEL - 1

RADIO_DEFAULT_LEVEL = 40
RADIO_NOCLIP_LEVEL = RADIO_DEFAULT_LEVEL - 1

VIDEO_EXPORT_DEFAULT_LEVEL = 45
VIDEO_EXPORT_NOCLIP_LEVEL = VIDEO_EXPORT_DEFAULT_LEVEL - 1

EGIT_DEFAULT_LEVEL = 50
EGIT_NOCLIP_LEVEL = EGIT_DEFAULT_LEVEL - 1