-- Commands
-- the section is not intended for end-user editing
dofile(LockOn_Options.script_path.."command_defs.lua")

KeyCommands = {{command = Keys.PlaneSalvoOnOff},
			   {command = Keys.PlaneIncreaseBase_Distance,arg = 608, arg_increment = 1   , direct_set = true, arg_lim = {0, 1}},
			   {command = Keys.PlaneDecreaseBase_Distance,arg = 608, arg_increment =-1   , direct_set = true, arg_lim = {-1, 0}},
			   {command = Keys.PlaneStopBase_Distance    ,arg = 608, arg_increment = 0   , direct_set = true, arg_lim = {-1, 1}},
			   {command = Keys.iCommandPlane_I251_Brightness_Up},
			   {command = Keys.iCommandPlane_I251_Brightness_Down},
			   {command = Keys.iCommandPlane_I251_Contrast_Up},
			   {command = Keys.iCommandPlane_I251_Contrast_Down},   
			   {command = Keys.iCommandPlane_I251_Background_WhiteBlack},
			   {command = Keys.PlaneZoomIn	 , arg = 559          , arg_increment = 1.0, direct_set = true, arg_lim = {0, 1}},   
			   {command = Keys.PlaneZoomOut  , arg = 559          , arg_increment = 0  , direct_set = true, arg_lim = {0, 1}},
			   {command = Keys.iCommandPlaneChangeLock},
			   {command = Keys.PlaneRadarHorizontal},
			   {command = Keys.PlaneRadarVertical},
			   {command = Keys.PlaneRadarHorizontalAbs},
			   {command = Keys.PlaneRadarVerticalAbs},
			   {command = Keys.PlaneSelecterHorizontal},
			   {command = Keys.PlaneSelecterVertical},
			   {command = Keys.PlaneSelecterHorizontalAbs},
			   {command = Keys.PlaneSelecterVerticalAbs},
			   {command = Keys.iCommandPlaneRadarLeft},
			   {command = Keys.iCommandPlaneRadarRight},
			   {command = Keys.iCommandPlaneRadarUp},
			   {command = Keys.iCommandPlaneRadarDown},
			   {command = Keys.iCommandPlaneRadarCenter},
			   {command = Keys.iCommandPlaneRadarStop},
			   {command = Keys.iCommandRefusalTWS},
			   {command = Keys.PlaneChangeWaypoint},
			   {command = Keys.iCommandDecreaseRadarScanArea},
			   {command = Keys.iCommandIncreaseRadarScanArea},
			   {command = Keys.iCommandPlaneRadarChangeMode},
			   {command = Keys.iCommand_SHKVAL_scan_vel_up},
			   {command = Keys.iCommand_SHKVAL_scan_vel_down},
			   {command = Keys.iCommand_SHKVAL_windscreen_wiper},
              }
