troops = {
    troop('15.POLK VOJASKEGA LETALSTVA', _('15.POLK VOJASKEGA LETALSTVA'), 'SLOAF.png'),
    troop('15.POLK VOJASKEGA LETALSTVA POVELJSTVO', _('15.POLK VOJASKEGA LETALSTVA POVELJSTVO'), '15POLK.png'),
    troop('151.HELIKOPTERSKA ESKADRILJA', _('151.HELIKOPTERSKA ESKADRILJA'), '151HEESK.png'),
    troop('152.LETALSKA ESKADRILJA', _('152.LETALSKA ESKADRILJA'), '152LETESK.png'),
    troop('153.LETALSKA TEHNICNA ESKADRILJA', _('153.LETALSKA TEHNICNA ESKADRILJA'), '153LETEHESK.png'),
    troop('107.LETALSKA BAZA', _('107.LETALSKA BAZA'), '107LETB.png'),
    troop('LETALSKA SOLA', _('LETALSKA SOLA'), 'LETSO.png'),
    troop('16.CENTER ZA NADZOR IN KONTROLO ZRACNEGA PROSTORA', _('16.CENTER ZA NADZOR IN KONTROLO ZRACNEGA PROSTORA'), '16CNKZP.png'),
};
