dofile(LockOn_Options.script_path.."CDU/indicator/CDU_definitions.lua")


AddStaticText("WIND_ALT_TEMP",   2, 4, LFT, "WIND      ALT     TEMP")

AddStaticText("WIND",			24, 3, RGHT, "WIND" .. BRANCH_R)

AddText		 ("WINDDATA_ENTRY",  1, 5, LFT, {{"WINDPresent", 0}}, DATA_ENTRY)
AddText		 ("WINDDirSpeed",    2, 5, LFT, {{"WINDPresent", 0}, {"WINDDir", 0, 0}}, "***")
AddText		 ("WINDDirSpeed1",    2, 5, LFT, {{"WINDPresent", 0}, {"WINDDir", 0, 1}})
AddText		 ("WINDDIV",         5, 5, LFT, {{"WINDPresent", 0}}, "/")
AddText		 ("WINDSpeed",	     6, 5, LFT, {{"WINDPresent", 0}, {"WINDSpeed", 0, 0}}, "**")
AddText		 ("WINDSpeed1",	     6, 5, LFT, {{"WINDPresent", 0}, {"WINDSpeed", 0, 1}})
AddText		 ("WINDALT",        12, 5, LFT, {{"WINDPresent", 0}, {"WINDALT", 0}})
AddText		 ("WINDTemp",	    23, 5, RGHT, {{"WINDPresent", 0}, {"WINDTempC", 0, 0}}, "***")
AddText		 ("WINDTemp1",	    23, 5, RGHT, {{"WINDPresent", 0}, {"TempMode", 0}, {"WINDTempC", 0, 1}})
AddText		 ("WINDTemp2",	    23, 5, RGHT, {{"WINDPresent", 0}, {"TempMode", 1}, {"WINDTempF", 0, 1}})
AddText		 ("WINDDATA_ENTRY1", 24, 5, RGHT, {{"WINDPresent", 0}}, DATA_ENTRY)

AddText		 ("WINDDATA_ENTRY2",  1, 7, LFT, {{"WINDPresent", 1}}, DATA_ENTRY)
AddText		 ("WINDDirSpeed2",    2, 7, LFT, {{"WINDPresent", 1}, {"WINDDir", 1, 0}}, "***")
AddText		 ("WINDDirSpeed3",    2, 7, LFT, {{"WINDPresent", 1}, {"WINDDir", 1, 1}})
AddText		 ("WINDDIV1",         5, 7, LFT, {{"WINDPresent", 1}}, "/")
AddText		 ("WINDSpeed2",	     6, 7, LFT, {{"WINDPresent", 1}, {"WINDSpeed", 1, 0}}, "**")
AddText		 ("WINDSpeed3",	     6, 7, LFT, {{"WINDPresent", 1}, {"WINDSpeed", 1, 1}})
AddText		 ("WINDALT1",        12, 7, LFT, {{"WINDPresent", 1}, {"WINDALT", 1}})
AddText		 ("WINDTemp3",	    23, 7, RGHT, {{"WINDPresent", 1}, {"WINDTempC", 1, 0}}, "***")
AddText		 ("WINDTemp4",	    23, 7, RGHT, {{"WINDPresent", 1}, {"TempMode", 0}, {"WINDTempC", 1, 1}})
AddText		 ("WINDTemp5",	    23, 7, RGHT, {{"WINDPresent", 1}, {"TempMode", 1}, {"WINDTempF", 1, 1}})
AddText		 ("WINDDATA_ENTRY3", 24, 7, RGHT, {{"WINDPresent", 1}}, DATA_ENTRY)

AddText		 ("WINDDATA_ENTRY4",  1, 9, LFT, {{"WINDPresent", 2}}, DATA_ENTRY)
AddText		 ("WINDDirSpeed4",    2, 9, LFT, {{"WINDPresent", 2}, {"WINDDir", 2, 0}}, "***")
AddText		 ("WINDDirSpeed5",    2, 9, LFT, {{"WINDPresent", 2}, {"WINDDir", 2, 1}})
AddText		 ("WINDDIV2",         5, 9, LFT, {{"WINDPresent", 2}}, "/")
AddText		 ("WINDSpeed4",	     6, 9, LFT, {{"WINDPresent", 2}, {"WINDSpeed", 2, 0}}, "**")
AddText		 ("WINDSpeed5",	     6, 9, LFT, {{"WINDPresent", 2}, {"WINDSpeed", 2, 1}})
AddText		 ("WINDALT2",        12, 9, LFT, {{"WINDPresent", 2}, {"WINDALT", 2}})
AddText		 ("WINDTemp6",	    23, 9, RGHT, {{"WINDPresent", 2}, {"WINDTempC", 2, 0}}, "***")
AddText		 ("WINDTemp7",	    23, 9, RGHT, {{"WINDPresent", 2}, {"TempMode", 0}, {"WINDTempC", 2, 1}})
AddText		 ("WINDTemp8",	    23, 9, RGHT, {{"WINDPresent", 2}, {"TempMode", 1}, {"WINDTempF", 2, 1}})
AddText		 ("WINDDATA_ENTRY5", 24, 9, RGHT, {{"WINDPresent", 2}}, DATA_ENTRY)

AddStaticText("PAGE_NUM", 20 + PageNumNorOffset, 10, LFT, "1")

add_hint_controllers_CDU("L2", _("Enter wind direction and speed at the corresponding altitude in degrees/knots"), {{"WINDPresent", 0}})
add_hint_controllers_CDU("L3", _("Enter wind direction and speed at the corresponding altitude in degrees/knots"), {{"WINDPresent", 1}})
add_hint_controllers_CDU("L4", _("Enter wind direction and speed at the corresponding altitude in degrees/knots"), {{"WINDPresent", 2}})
add_static_hint_CDU("R1", _("Return to WIND Page"))
add_hint_controllers_CDU("R2", _("Enter Temperature at corresponding altitude in degrees C"), {{"WINDPresent", 0}})
add_hint_controllers_CDU("R3", _("Enter Temperature at corresponding altitude in degrees C"), {{"WINDPresent", 1}})
add_hint_controllers_CDU("R4", _("Enter Temperature at corresponding altitude in degrees C"), {{"WINDPresent", 2}})
