dofile(LockOn_Options.script_path.."CDU/indicator/CDU_definitions.lua")

AddStaticText("ALT_WIND_TEMP",  2, 4, LFT, "ALT  WIND  TEMP")

AddText		 ("WINDALT",        3, 5, LFT, {{"WINDPresent", 0}, {"WINDALT", 0}})
AddText		 ("WINDDir",	    6, 5, LFT, {{"WINDPresent", 0}, {"WINDDir", 0, 0}}, "***")
AddText		 ("WINDDir1",		6, 5, LFT, {{"WINDPresent", 0}, {"WINDDir", 0, 1}})
AddText		 ("WINDDIV",        9, 5, LFT, {{"WINDPresent", 0}}, "/")
AddText		 ("WINDSpeed",	   10, 5, LFT, {{"WINDPresent", 0}, {"WINDSpeed", 0, 0}}, "**")
AddText		 ("WINDSpeed1",	   10, 5, LFT, {{"WINDPresent", 0}, {"WINDSpeed", 0, 1}})
AddText		 ("WINDTemp",	   13, 5, LFT, {{"WINDPresent", 0}, {"WINDTempC", 0, 0}}, "***")
AddText		 ("WINDTemp1",	   13, 5, LFT, {{"WINDPresent", 0}, {"TempMode", 0}, {"WINDTempC", 0, 1}})
AddText		 ("WINDTemp2",	   13, 5, LFT, {{"WINDPresent", 0}, {"TempMode", 1}, {"WINDTempF", 0, 1}})

AddText		 ("WINDALT1",        3, 7, LFT, {{"WINDPresent", 1}, {"WINDALT", 1}})
AddText		 ("WINDDirSpeed",   6, 7, LFT, {{"WINDPresent", 1}, {"WINDDir", 1, 0}}, "***")
AddText		 ("WINDDirSpeed1",   6, 7, LFT, {{"WINDPresent", 1}, {"WINDDir", 1, 1}})
AddText		 ("WINDDIV1",        9, 7, LFT, {{"WINDPresent", 1}}, "/")
AddText		 ("WINDSpeed2",	   10, 7, LFT, {{"WINDPresent", 1}, {"WINDSpeed", 1, 0}}, "**")
AddText		 ("WINDSpeed3",	   10, 7, LFT, {{"WINDPresent", 1}, {"WINDSpeed", 1, 1}})
AddText		 ("WINDTemp3",	   13, 7, LFT, {{"WINDPresent", 1}, {"WINDTempC", 1, 0}}, "***")
AddText		 ("WINDTemp4",	   13, 7, LFT, {{"WINDPresent", 1}, {"TempMode", 0}, {"WINDTempC", 1, 1}})
AddText		 ("WINDTemp5",	   13, 7, LFT, {{"WINDPresent", 1}, {"TempMode", 1}, {"WINDTempF", 1, 1}})

AddText		 ("WINDALT2",        3, 9, LFT, {{"WINDPresent", 2}, {"WINDALT", 2}})
AddText		 ("WINDDirSpeed2",   6, 9, LFT, {{"WINDPresent", 2}, {"WINDDir", 2, 0}}, "***")
AddText		 ("WINDDirSpeed3",   6, 9, LFT, {{"WINDPresent", 2}, {"WINDDir", 2, 1}})
AddText		 ("WINDDIV2",        9, 9, LFT, {{"WINDPresent", 2}}, "/")
AddText		 ("WINDSpeed4",	   10, 9, LFT, {{"WINDPresent", 2}, {"WINDSpeed", 2, 0}}, "**")
AddText		 ("WINDSpeed5",	   10, 9, LFT, {{"WINDPresent", 2}, {"WINDSpeed", 2, 1}})
AddText		 ("WINDTemp6",	   13, 9, LFT, {{"WINDPresent", 2}, {"WINDTempC", 2, 0}}, "***")
AddText		 ("WINDTemp7",	   13, 9, LFT, {{"WINDPresent", 2}, {"TempMode", 0}, {"WINDTempC", 2, 1}})
AddText		 ("WINDTemp8",	   13, 9, LFT, {{"WINDPresent", 2}, {"TempMode", 1}, {"WINDTempF", 2, 1}})

AddStaticText("PAGE_NUM", 20 + PageNumNorOffset, 10, LFT, "1")
