dofile(LockOn_Options.script_path.."CDU/indicator/CDU_definitions.lua")

AddStaticText("BRACKETS_ITEM1", 1, 3, LFT, DATA_ENTRY)

AddText		 ("WINDALT",        3, 3, LFT, {{"WINDPresent", 3}, {"WINDALT", 3}})
AddText		 ("WINDDirSpeed",   6, 3, LFT, {{"WINDPresent", 3}, {"WINDDir", 3, 0}}, "***")
AddText		 ("WINDDirSpeed1",   6, 3, LFT, {{"WINDPresent", 3}, {"WINDDir", 3, 1}})
AddText		 ("WINDDIV",        9, 3, LFT, {{"WINDPresent", 3}}, "/")
AddText		 ("WINDSpeed",	   10, 3, LFT, {{"WINDPresent", 3}, {"WINDSpeed", 3, 0}}, "**")
AddText		 ("WINDSpeed1",	   10, 3, LFT, {{"WINDPresent", 3}, {"WINDSpeed", 3, 1}})
AddText		 ("WINDTemp",	   13, 3, LFT, {{"WINDPresent", 3}, {"WINDTempC", 3, 0}}, "***")
AddText		 ("WINDTemp1",	   13, 3, LFT, {{"WINDPresent", 3}, {"TempMode", 0}, {"WINDTempC", 3, 1}})
AddText		 ("WINDTemp2",	   13, 3, LFT, {{"WINDPresent", 3}, {"TempMode", 1}, {"WINDTempF", 3, 1}})

AddText		 ("WINDALT1",        3, 5, LFT, {{"WINDPresent", 4}, {"WINDALT", 4}})
AddText		 ("WINDDirSpeed2",   6, 5, LFT, {{"WINDPresent", 4}, {"WINDDir", 4, 0}}, "***")
AddText		 ("WINDDirSpeed3",   6, 5, LFT, {{"WINDPresent", 4}, {"WINDDir", 4, 1}})
AddText		 ("WINDDIV1",        9, 5, LFT, {{"WINDPresent", 4}}, "/")
AddText		 ("WINDSpeed2",	   10, 5, LFT, {{"WINDPresent", 4}, {"WINDSpeed", 4, 0}}, "**")
AddText		 ("WINDSpeed3",	   10, 5, LFT, {{"WINDPresent", 4}, {"WINDSpeed", 4, 1}})
AddText		 ("WINDTemp3",	   13, 5, LFT, {{"WINDPresent", 4}, {"WINDTempC", 4, 0}}, "***")
AddText		 ("WINDTemp4",	   13, 5, LFT, {{"WINDPresent", 4}, {"TempMode", 0}, {"WINDTempC", 4, 1}})
AddText		 ("WINDTemp5",	   13, 5, LFT, {{"WINDPresent", 4}, {"TempMode", 1}, {"WINDTempF", 4, 1}})

AddText		 ("WINDALT2",        3, 7, LFT, {{"WINDPresent", 5}, {"WINDALT", 5}})
AddText		 ("WINDDirSpeed4",   6, 7, LFT, {{"WINDPresent", 5}, {"WINDDir", 5, 0}}, "***")
AddText		 ("WINDDirSpeed5",   6, 7, LFT, {{"WINDPresent", 5}, {"WINDDir", 5, 1}})
AddText		 ("WINDDIV2",        9, 7, LFT, {{"WINDPresent", 5}}, "/")
AddText		 ("WINDSpeed4",	   10, 7, LFT, {{"WINDPresent", 5}, {"WINDSpeed", 5, 0}}, "**")
AddText		 ("WINDSpeed5",	   10, 7, LFT, {{"WINDPresent", 5}, {"WINDSpeed", 5, 1}})
AddText		 ("WINDTemp6",	   13, 7, LFT, {{"WINDPresent", 5}, {"WINDTempC", 5, 0}}, "***")
AddText		 ("WINDTemp7",	   13, 7, LFT, {{"WINDPresent", 5}, {"TempMode", 0}, {"WINDTempC", 5, 1}})
AddText		 ("WINDTemp8",	   13, 7, LFT, {{"WINDPresent", 5}, {"TempMode", 1}, {"WINDTempF", 5, 1}})

AddText		 ("WINDALT3",        3, 9, LFT, {{"WINDPresent", 6}, {"WINDALT", 6}})
AddText		 ("WINDDirSpeed6",   6, 9, LFT, {{"WINDPresent", 6}, {"WINDDir", 6, 0}}, "***")
AddText		 ("WINDDirSpeed7",   6, 9, LFT, {{"WINDPresent", 6}, {"WINDDir", 6, 1}})
AddText		 ("WINDDIV3",        9, 9, LFT, {{"WINDPresent", 6}}, "/")
AddText		 ("WINDSpeed6",	   10, 9, LFT, {{"WINDPresent", 6}, {"WINDSpeed", 6, 0}}, "**")
AddText		 ("WINDSpeed7",	   10, 9, LFT, {{"WINDPresent", 6}, {"WINDSpeed", 6, 1}})
AddText		 ("WINDTemp9",	   13, 9, LFT, {{"WINDPresent", 6}, {"WINDTempC", 6, 0}}, "***")
AddText		 ("WINDTemp10",	   13, 9, LFT, {{"WINDPresent", 6}, {"TempMode", 0}, {"WINDTempC", 6, 1}})
AddText		 ("WINDTemp11",	   13, 9, LFT, {{"WINDPresent", 6}, {"TempMode", 1}, {"WINDTempF", 6, 1}})

AddStaticText("PAGE_NUM", 20 + PageNumNorOffset, 10, LFT, "2")

add_static_hint_CDU("L1", _("Enter Wind Data"))
