cdata =
{
    modName				= _('M-2000C'),
    CPLocalList			= _('Cockpit language'),
	UNI_NODRIFT 		= _('Disable Gyro Drift'),
	FUEL_DETOT_AUTO		= _('Automatic fuel detot'),
	REFUEL_HACK			= _('External tank refuel fix'),
	RADAR_MAPOBJECTS	= _('Radar senses map objects'),
	RADAR_CLUTTERQMC	= _('Radar high quality QMC clutter'),
	--RADAR_FULLASYNC 	= _('Radar full asynchronous update (beta)'),
	RADIO_PTTMENU		= _('Radio PTT short press toggles menu'),
	REAL_FREQ_REP		= _('Realistic frequency repeater'),
	VTB_ENLARGE			= _('Enlarge small VTB items (%)'),
	VTB_FOV_ENABLE		= _('Realistic VTB cone of vision'),
	VTB_FOV_SIZE		= _('VTB cone of vision size'),
	VTB_FOV_HEIGHT		= _('VTB cone of vision height'),
	PCN_DIGIT_MSG		= _('Show PCN hidden digit entry message'),
	THROTTLE_CO_DETENT	= _('Throttle cutoff detent'),
	THROTTLE_AB_DETENT	= _('Throttle afterburner detent'),
	PITCH_ELASTIC_LIMIT	= _('Elastic limit axis position'),
	PITCH_LIMIT_MODE	= _('Elastic limit bind'),
	MW_KNOBS_SPEED		= _('Adjust speed of mouse wheel knobs'),
	EZ_LAUNCH_ALERT		= _('More distinctive RWR launch alert tone'),
	RAND_RDR_CHANNEL	= _('Randomize radar channel at spawn'),
	ENGINE_LOG			= _('Log engine physical data'),
    default				= _('Default_liv'),
    english				= _('English_liv'),
}
