
-------PAGE IDs-------
PAGE_OFF			= 0
PAGE_NAV			= 1
PAGE_NAV_AWLS		= 2	-- NAV + AWLS
PAGE_NAV_3			= 3	-- NAV + FLIR
PAGE_VTOL			= 4
PAGE_VTOL_AWLS		= 5	-- VTOL + AWLS
PAGE_VTOL_3			= 6	-- VTOL + FLIR
PAGE_AA_GUNS		= 7
PAGE_AA_AIM9		= 8
PAGE_AG_GUNS		= 9
PAGE_AG_RKTS		= 10
PAGE_AG_BOMBS		= 11
PAGE_AG_JDAMS		= 12
PAGE_AG_AGMS		= 13
PAGE_AG_NOWPN		= 14
PAGE_NAV_FAIL_INS	= 15
PAGE_NAV_FAIL_MSC	= 16
PAGE_VTOL_FAIL_INS	= 17
PAGE_VTOL_FAIL_MSC	= 18
PAGE_AA_STANDBY		= 19
PAGE_AG_STANDBY		= 20
PAGE_STANDBY		= 50

--Source files for page subsets
SRC_HUD_GLASS			= 0
SRC_HUD_BASE			= 1
SRC_HUD_NAV				= 2
SRC_HUD_NAV_AWLS		= 3
SRC_HUD_VTOL			= 4
SRC_HUD_VTOL_AWLS		= 5
SRC_HUD_AA_GUNS 		= 7
SRC_HUD_AA_AIM9 		= 8
SRC_HUD_AG_GUNS 		= 9
SRC_HUD_AG_RKTS 		= 10
SRC_HUD_AG_BOMBS		= 11
SRC_HUD_AG_JDAMS		= 12
SRC_HUD_AG_AGMS			= 13
SRC_HUD_AG_NOWPN		= 14
SRC_HUD_NAV_FAIL_INS	= 15
SRC_HUD_NAV_FAIL_MSC	= 16
SRC_HUD_VTOL_FAIL_INS	= 17
SRC_HUD_VTOL_FAIL_MSC	= 18
SRC_HUD_AA_STANDBY		= 19
SRC_HUD_AG_STANDBY		= 20
SRC_HUD_STBY			= 50
