dofile(LockOn_Options.script_path.."CDU/indicator/CDU_definitions.lua")

-- Annunciations --
AddText("NUM", 1, 2, LFT,  {{"annunciationCounter"}})

AddText("ANN1", 2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 1}},  "CADC FAIL")
AddText("ANN2", 2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 2}},  "DTS FAIL")
AddText("ANN3", 2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 3}},  "CICU FAIL")
AddText("ANN4", 2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 4}},  "EGI FAIL")
AddText("ANN5", 2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 5}},  "EGI FLT INST FAIL")
AddText("ANN6", 2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 6}},  "GPS FAIL")
AddText("ANN7", 2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 7}},  "HARS FAIL")
AddText("ANN8", 2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 8}},  "INS FAIL")
AddText("ANN9", 2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 9}},  "INS FLT INST FAIL")

AddText("ANN10",2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 10}}, "BLENDED GPS DIFFER")
AddText("ANN11",2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 11}}, "CADC NOT RDY")
AddText("ANN12",2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 12}}, "CDU UPLOAD FAIL")
AddText("ANN13",2, 2, LFT, {{"AnnVisible", 1}, {"AnnMsg",  13}}, "CICU NOT RDY")
AddText("ANN14",2, 2, LFT, {{"AnnVisible", 1}, {"AnnMsg",  14}}, "DOWNLOAD COMPLETE")
AddText("ANN15",2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 15}}, "DOWNLOAD FAILED")
AddText("ANN16",2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 16}}, "DTC FULL")
AddText("ANN17",2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 17}}, "DTC UPLOAD COMPLETE")
AddText("ANN18",2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 18}}, "DTSAS FAIL")
AddText("ANN19",2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 19}}, "DTS NOT RDY")
AddText("ANN20",2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 20}}, "EGI NOT RDY")
AddText("ANN21",2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 21}}, "FP UPLOAD ERROR")
AddText("ANN22",2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 22}}, "INIT POS")
AddText("ANN23",2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 23}}, "INS DEGRADED")
AddText("ANN24",2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 24}}, "IFFCC NOT RDY")
AddText("ANN25",2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 25}}, "LASTE UPLOAD FAIL")
AddText("ANN26", 2, 2, LFT, {{"AnnVisible", 1}, {"AnnMsg", 26}}, "MARK")
AddText("ANN26a",7, 2, LFT, {{"AnnVisible", 1}, {"AnnMsg", 26}, {"AnnMarkLetter"}})
AddText("ANN27",2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 27}}, "OFP LOAD FAIL")
AddText("ANN28",2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 28}}, "OFP VERIFY FAIL")
AddText("ANN29",2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 29}}, "POWER EGI OFF")
AddText("ANN30",2, 2, LFT,  {{"AnnVisible", 1}, {"AnnMsg", 30}}, "SCALE ERROR")
AddText("ANN31", 2, 2, LFT, {{"AnnVisible", 1}, {"AnnMsg", 31}}, "VERT MODE INPUT ERR")
AddText("ANN32", 2, 2, LFT, {{"AnnVisible", 1}, {"AnnMsg", 32}}, "WP UPLOAD ERR")

AddText("ANN33", 2, 2, LFT, {{"AnnVisible", 1}, {"AnnMsg", 33}}, "DTC ERASED")
AddText("ANN34", 2, 2, LFT, {{"AnnVisible", 1}, {"AnnMsg", 34}}, "DTSAS OFF MAP")
AddText("ANN35", 2, 2, LFT, {{"AnnVisible", 1}, {"AnnMsg", 35}}, "ALMS LOAD ERR")
AddText("ANN36", 2, 2, LFT, {{"AnnVisible", 1}, {"AnnMsg", 36}}, "GPS KEY ERASE FAIL")
AddText("ANN37", 2, 2, LFT, {{"AnnVisible", 1}, {"AnnMsg", 37}}, "GPS KEY LOAD FAIL")
AddText("ANN38", 2, 2, LFT, {{"AnnVisible", 1}, {"AnnMsg", 38}}, "GPS KEY 2HR WARNING")
AddText("ANN39", 2, 2, LFT, {{"AnnVisible", 1}, {"AnnMsg", 39}}, "GPS KEYS ERASED")
AddText("ANN40", 2, 2, LFT, {{"AnnVisible", 1}, {"AnnMsg", 40}}, "GPS NEEDS ALMS")
AddText("ANN41", 2, 2, LFT, {{"AnnVisible", 1}, {"AnnMsg", 41}}, "GPS NEEDS KEYS")
AddText("ANN42", 2, 2, LFT, {{"AnnVisible", 1}, {"AnnMsg", 42}}, "WARM START")

AddText("ANN43", 2, 2, LFT, {{"AnnVisible", 1}, {"AnnMsg", 43}, {"AnnBlink"}}, "INS NAV RDY")
