livery = {


--Diffuse  -----------------------------------

{"HB_F14_EXT_01", 0 ,"HB_F14_EXT_01",false};
{"HB_F14_EXT_02", 0 ,"HB_F14_EXT_02",false};
{"HB_F14_EXT_03", 0 ,"HB_F14_EXT_03",false};
{"HB_F14_EXT_04", 0 ,"HB_F14_EXT_04",false};
{"HB_F14_EXT_TAIL", 0 ,"HB_F14_EXT_TAIL",false};
{"HB_F14_WING_LEFT_01", 0 ,"HB_F14_WING_LEFT",false};
{"HB_F14_WING_RIGHT", 0 ,"HB_F14_WING_RIGHT",false};

{"HB_F14_EXT_INTAKERAMPS", 0 ,"HB_F14_EXT_INTAKERAMPS",false};

{"HB_F14_TCS", 0 ,"HB_F14_EXT_TCS",false};

{"HB_F14_EXT_PHOENIXRAILS", 0 ,"HB_F14_EXT_PHOENIXPYLONS",false};
{"HB_F14_EXT_PYLONS", 0 ,"HB_F14_EXT_PYLONS_01",false};
{"HB_F14_EXT_LANTIRN_PYLON", 0 ,"HB_F14_EXT_LANTIRN_PYLON",false};
{"HB_F14_EXT_LAU-7", 0 ,"HB_F14_EXT_LAU_7",false};


{"HB_F14_EXT_DROPTANKS", 0 ,"HB_F14_EXT_DROPTANK",false};

{"HB_F14_EXT_PILOT_SUIT", 0 ,"HB_F14_EXT_PILOT_SUIT",false};
{"HB_F14_EXT_PILOT_SUIT", 1 ,"HB_F14_EXT_PILOT_SUIT_NORMAL",false};
{"HB_F14_EXT_PILOT", 0 ,"HB_F14_EXT_PILOT",false};

{"HB_F14_EXT_PILOT_HELMET", 0 ,"HB_F14_EXT_PILOT_HELMET",false};
{"HB_F14_EXT_PILOT_HELMET", 1 ,"HB_F14_EXT_PILOT_HELMET_NORMAL",false};
{"HB_F14_EXT_PILOT_HELMET", ROUGHNESS_METALLIC ,"HB_F14_EXT_PILOT_HELMET_RoughMet",false};

{"HB_F14_EXT_RIO_HELMET", 0 ,"HB_F14_EXT_RIO_HELMET",false};
{"HB_F14_EXT_RIO_HELMET", 1 ,"HB_F14_EXT_PILOT_HELMET_NORMAL",false};
{"HB_F14_EXT_RIO_HELMET", ROUGHNESS_METALLIC ,"HB_F14_EXT_PILOT_HELMET_RoughMet",false};

{"HB_F14_LOD1_3in1", 0 ,"HB_F14_LOD1_3in1",false};

}
name = "IRAN Cat Blue Gray"

--countries = {}


--by MAX Discord 5353