monitorpos = "R"
dofile(LockOn_Options.script_path.."MPCD/indicator/MPCD_init.lua")

brightness_sensitive_materials = {
	"mpcd_align_mtl_y",
	"mpcd_symbols_1_w",
	"mpcd_symbols_1_b",
	"mpcd_symbols_2_w",
	"mpcdr_symbols_1_g",
	"mpcdr_symbols_2_g",
	"mpcdr_symbols_3",
	"mpcdr_symbols_4",
	"mpcdr_symbols_5",
	"mpcdr_symbols_6",
	"mpcdr_symbols_1",
	"tpod_symbols_R",
	-- EHSD
	"mpcdr_font_base",
	"mpcdr_tpod_font",
	"mpcdr_lmav_font",
	"mpcd_tpod_font_bg",
	"mpcd_ehsd_lines_fg",
	"mpcd_ehsd_lines_bg",
	"mpcd_ehsd_lines_fg",
	"mpcd_ehsd_lines_bg",
	"mpcd_ehsd_route_lines_fg",
	"mpcd_ehsd_dashed_lines_bg",
	"mpcd_ehsd_dashed_lines_fg",
	"mpcd_ehsd_route_lines_gr",
	"mpcd_ehsd_route_lines_bl",
	"mpcd_ehsd_route_lines_or",
	"mpcd_ehsd_route_lines_vl",
	"mpcd_ehsd_route_lines_rd",
	"mpcdr_ehsd_dashed_lines_bg",
	"mpcdr_ehsd_dashed_lines_fg",
	-- Stroke
	"mpcdr_strk_symb_fg",
	"mpcdr_strk_symb_bg",
	"font_MPCDR_stroke",
	"font_MPCDR_stroke_outline",
	-- HUD Repeater
	"hrr_pitch_ladder",
	"hrr_ind_material",
	"hrr_hdg_material",
	"hrr_align_material",
	"hrr_lines_material",
	"hrr_dashed_lines_material",
	"hrr_indication_font",
	"font_HUD_stroke_rr",
	"font_HUD_stroke_ol_rr",
	"HUD_RR_GREEN_BRIGHT",
	"BLACK",
}

opacity_sensitive_materials = {
	"mpcd_align_mtl_y",
	"mpcd_symbols_1_w",
	"mpcd_symbols_1_b",
	"mpcd_symbols_2_w",
	"mpcdr_symbols_1_g",
	"mpcdr_symbols_2_g",
	"mpcdr_symbols_3",
	"mpcdr_symbols_4",
	"mpcdr_symbols_5",
	"mpcdr_symbols_6",
	"mpcdr_symbols_1",
	"tpod_symbols_R",
	--EHSD
	"mpcdr_font_base",
	"mpcdr_tpod_font",
	"mpcdr_lmav_font",
	"mpcd_tpod_font_bg",
	"mpcd_ehsd_lines_fg",
	"mpcd_ehsd_lines_bg",
	"mpcd_ehsd_route_lines_fg",
	"mpcd_ehsd_dashed_lines_bg",
	"mpcd_ehsd_dashed_lines_fg",
	"mpcd_ehsd_route_lines_gr",
	"mpcd_ehsd_route_lines_bl",
	"mpcd_ehsd_route_lines_or",
	"mpcd_ehsd_route_lines_vl",
	"mpcd_ehsd_route_lines_rd",
	-- Stroke
	"mpcdr_strk_symb_fg",
	"mpcdr_strk_symb_bg",
	"font_MPCDR_stroke",
	"font_MPCDR_stroke_outline",
	"mpcdr_ehsd_dashed_lines_bg",
	"mpcdr_ehsd_dashed_lines_fg",
	-- HUD Repeater
	"hrr_pitch_ladder",
	"hrr_ind_material",
	"hrr_hdg_material",
	"hrr_align_material",
	"hrr_lines_material",
	"hrr_dashed_lines_material",
	"hrr_indication_font",
	"font_HUD_stroke_rr",
	"font_HUD_stroke_ol_rr",
	"HUD_RR_GREEN_BRIGHT",
	"BLACK",
}

color_sensitive_materials = {
	"mpcdr_symbols_1_g",
	"mpcdr_symbols_2_g",
	"mpcdr_symbols_3",
	"mpcdr_symbols_4",
	"mpcdr_symbols_5",
	"mpcdr_symbols_6",
	"mpcdr_symbols_1",
	"tpod_symbols_R",
	-- EHSD
	"mpcdr_font_base",
	"mpcdr_tpod_font",
	"mpcdr_lmav_font",
	-- Stroke
	"mpcdr_strk_symb_fg",
	"font_MPCDR_stroke",
	-- HUD Repeater
	"hrr_pitch_ladder",
	"hrr_ind_material",
	"hrr_hdg_material",
	"hrr_align_material",
	"hrr_lines_material",
	"hrr_dashed_lines_material",
	"hrr_indication_font",
	"font_HUD_stroke_rr",
	"font_HUD_stroke_ol_rr",
	"HUD_RR_GREEN_BRIGHT",
}

--try_find_assigned_viewport("RIGHT_MFCD")