dofile(LockOn_Options.script_path.."/KNEEBOARD/pages/common.lua")

addChecklistTitle(1, _("BEFORE APU START_board"), _("LSHIFT+NUM1"))

addChecklistItem(1,		_("BATTERY_board"),							_("ON. VOLTAGE NORMAL_board"))
addChecklistItem(2,		_("RECORDER_board"),						_("ON. WORKS_board"))
addChecklistItem(3,		_("SPU READABILITY_board"),					_("GOOD_board"))
addChecklistItem(4,		_("COLLECTIVE LOCK_board"),					_("OPENED_board"))
addChecklistItem(5,		_("SPUU-52_board"),							_("ON. OK_board"))
addChecklistItem(6,		_("STICK AND PEDALS_board"),				_("NEUTRAL_board"))
addChecklistItem(7,		_("CIRCUIT-BREAKERS_board"),				_("ON_board"))
addChecklistItem(8,		_("DOORS_board"),							_("CLOSED_board"))
addChecklistItem(9,		_("WHEEL BRAKES_board"),					_("OK. AT STOPPING. PRESSURE NORMAL_board"))
addChecklistItem(10,	_("ROTOR BRAKE_board"),						_("DISINHIBITED_board"))
addChecklistItem(11,	_("THROTTLES_board"),						_("MIDDLE POSITION. LOCKED_board"))
addChecklistItem(12,	_("COLLECTIVE. CORRECTION LEVER_board"),	_("DOWN. LEFT_board"))
addChecklistItem(13,	_("LAMPS_board"),							_("OK_board"))
addChecklistItem(14,	_("BETTY_board"),							_("OK_board"))
addChecklistItem(15,	_("VIBRATION EQUIPMENT_board"),				_("OK_board"))
addChecklistItem(16,	_("SARPP-12_board"),						_("ON. MANUAL_board"))
addChecklistItem(17,	_("EXTINGUISHING SYSTEM_board"),			_("EXTINGUISHING. OK_board"))
addChecklistItem(18,	_("FEED SWITCH_board"),						_("ON_board"))
addChecklistItem(19,	_("FUEL GAUGE_board"),						_("OK_board"))
addChecklistItem(20,	_("GENERATORS_board"),						_("OFF_board"))
addChecklistItem(21,	_("FUEL VALVES_board"),						_("OPENED_board"))
addChecklistItem(22,	_("ENGINE STOP LEVERS_board"),				_("REAR POSITION_board"))
