dofile(LockOn_Options.script_path.."/KNEEBOARD/pages/common.lua")

addChecklistTitle(4, _("CORRECTION LEVER RIGHT_board"), _("LSHIFT+NUM4"))

addChecklistItem(1,		_("GENERATORS AND RECTIFIERS_board"),			_("ON_board"))
addChecklistItem(2,		_("EMERGENCY GENERATOR AND APU_board"),			_("OFF_board"))
addChecklistItem(3,		_("PO-115 AND PT-36 SWITCHES_board"),			_("AUTO_board"))
addChecklistItem(4,		_("SARPP-12_board"),							_("ON. MANUAL_board"))
addChecklistItem(5,		_("ROTOR RATE_board"),							_("OK_board"))
addChecklistItem(6,		_("ATTITUDE INDICATORS_board"),					_("ON. READINGS NORMAL_board"))
addChecklistItem(7,		_("COURSE SYSTEM_board"),						_("ON. SLAVED_board"))
addChecklistItem(8,		_("ADF_board"),									_("ON_board"))
addChecklistItem(9,		_("DOPPLER NAVIGATION_board"),					_("ON. READY_board"))
addChecklistItem(10,	_("IDENTIFICATION_board"),						_("ON_board"))
addChecklistItem(11,	_("RADAR ALTIMETER_board"),						_("ON_board"))
addChecklistItem(12,	_("QFE ON ALTIMETERS_board"),					_("SET_board"))
addChecklistItem(13,	_("EEC. EM_board"),								_("OK. EM ON_board"))
addChecklistItem(14,	_("ENGINES AND REDUCTORS PARAMETERS_board"),	_("NORMAL_board"))
addChecklistItem(15,	_("EMERGENCY AND WARNING LAMPS_board"),			_("DO NOT LIT_board"))
addChecklistItem(16,	_("WHEEL BRAKES_board"),						_("OK_board"))
