local skin = {
	["skinData"] = {
		["params"] = {
			["insets"] = {
				["bottom"] = 0,
				["left"] = 0,
				["right"] = 0,
				["top"] = 0,
			},
			["maxSize"] = {
				["horz"] = 0,
				["vert"] = 0,
			},
			["minSize"] = {
				["horz"] = 0,
				["vert"] = 0,
			},
			["textLineHeight"] = 0,
		},
		["states"] = {
			["disabled"] = {
				[1] = {
					["bkg"] = {
						["center_bottom"] = "0xffffffff",
						["center_center"] = "0xffffffff",
						["center_top"] = "0xffffffff",
						["file"] = "dxgui\\skins\\skinME\\images\\manager_modules\\btn page_moduls_unselected.png",
						["insets"] = {
							["bottom"] = 2,
							["left"] = 3,
							["right"] = 3,
							["top"] = 10,
						},
						["left_bottom"] = "0xffffffff",
						["left_center"] = "0xffffffff",
						["left_top"] = "0xffffffff",
						["rect"] = {
							["x1"] = 0,
							["x2"] = 0,
							["y1"] = 0,
							["y2"] = 0,
						},
						["right_bottom"] = "0xffffffff",
						["right_center"] = "0xffffffff",
						["right_top"] = "0xffffffff",
					},
					["text"] = {
						["bkgColor"] = "0x00000000",
						["blur"] = 0,
						["blurColor"] = "0x00000000",
						["color"] = "0xe0deda47",
						["font"] = "DejaVuLGCSans-Bold.ttf",
						["fontSize"] = 16,
						["horzAlign"] = {
							["offset"] = 20,
							["type"] = "min",
						},
						["lineHeight"] = 0,
						["lineThroughColor"] = "0x00000000",
						["lineThroughHeight"] = 1,
						["shadowColor"] = "0x00000000",
						["shadowOffset"] = {
							["horz"] = 0,
							["vert"] = 0,
						},
						["vertAlign"] = {
							["offset"] = 4,
							["type"] = "middle",
						},
					},
				},
				[2] = {
					["bkg"] = {
						["center_bottom"] = "0xffffffff",
						["center_center"] = "0xffffffff",
						["center_top"] = "0xffffffff",
						["file"] = "dxgui\\skins\\skinME\\images\\manager_modules\\btn page_moduls_selected.png",
						["insets"] = {
							["bottom"] = 1,
							["left"] = 7,
							["right"] = 7,
							["top"] = 6,
						},
						["left_bottom"] = "0xffffffff",
						["left_center"] = "0xffffffff",
						["left_top"] = "0xffffffff",
						["rect"] = {
							["x1"] = 0,
							["x2"] = 0,
							["y1"] = 0,
							["y2"] = 0,
						},
						["right_bottom"] = "0xffffffff",
						["right_center"] = "0xffffffff",
						["right_top"] = "0xffffffff",
					},
					["text"] = {
						["bkgColor"] = "0x00000000",
						["blur"] = 0,
						["blurColor"] = "0x00000000",
						["color"] = "0x00000047",
						["font"] = "DejaVuLGCSans-Bold.ttf",
						["fontSize"] = 16,
						["horzAlign"] = {
							["offset"] = 20,
							["type"] = "min",
						},
						["lineHeight"] = 0,
						["lineThroughColor"] = "0x00000000",
						["lineThroughHeight"] = 1,
						["shadowColor"] = "0x00000000",
						["shadowOffset"] = {
							["horz"] = 0,
							["vert"] = 0,
						},
						["vertAlign"] = {
							["offset"] = 0,
							["type"] = "middle",
						},
					},
				},
			},
			["hover"] = {
				[1] = {
					["bkg"] = {
						["center_bottom"] = "0xffffffff",
						["center_center"] = "0xffffffff",
						["center_top"] = "0xffffffff",
						["file"] = "dxgui\\skins\\skinME\\images\\manager_modules\\btn page_moduls_unselected.png",
						["insets"] = {
							["bottom"] = 0,
							["left"] = 0,
							["right"] = 0,
							["top"] = 0,
						},
						["left_bottom"] = "0xffffffff",
						["left_center"] = "0xffffffff",
						["left_top"] = "0xffffffff",
						["rect"] = {
							["x1"] = 0,
							["x2"] = 0,
							["y1"] = 0,
							["y2"] = 0,
						},
						["right_bottom"] = "0xffffffff",
						["right_center"] = "0xffffffff",
						["right_top"] = "0xffffffff",
					},
					["text"] = {
						["bkgColor"] = "0x00000000",
						["blur"] = 0,
						["blurColor"] = "0x00000000",
						["color"] = "0xe0dedae3",
						["font"] = "DejaVuLGCSans-Bold.ttf",
						["fontSize"] = 16,
						["horzAlign"] = {
							["offset"] = 20,
							["type"] = "min",
						},
						["lineHeight"] = 0,
						["lineThroughColor"] = "0x00000000",
						["lineThroughHeight"] = 1,
						["shadowColor"] = "0x00000000",
						["shadowOffset"] = {
							["horz"] = 0,
							["vert"] = 0,
						},
						["vertAlign"] = {
							["offset"] = 4,
							["type"] = "middle",
						},
					},
				},
				[2] = {
					["bkg"] = {
						["center_bottom"] = "0xffffffff",
						["center_center"] = "0xffffffff",
						["center_top"] = "0xffffffff",
						["file"] = "dxgui\\skins\\skinME\\images\\manager_modules\\btn page_moduls_pressed.png",
						["insets"] = {
							["bottom"] = 0,
							["left"] = 0,
							["right"] = 0,
							["top"] = 0,
						},
						["left_bottom"] = "0xffffffff",
						["left_center"] = "0xffffffff",
						["left_top"] = "0xffffffff",
						["rect"] = {
							["x1"] = 0,
							["x2"] = 0,
							["y1"] = 0,
							["y2"] = 0,
						},
						["right_bottom"] = "0xffffffff",
						["right_center"] = "0xffffffff",
						["right_top"] = "0xffffffff",
					},
					["text"] = {
						["bkgColor"] = "0x00000000",
						["blur"] = 0,
						["blurColor"] = "0x00000000",
						["color"] = "0xfbb941ff",
						["font"] = "DejaVuLGCSans-Bold.ttf",
						["fontSize"] = 16,
						["horzAlign"] = {
							["offset"] = 20,
							["type"] = "min",
						},
						["lineHeight"] = 0,
						["lineThroughColor"] = "0x00000000",
						["lineThroughHeight"] = 1,
						["shadowColor"] = "0x00000000",
						["shadowOffset"] = {
							["horz"] = 0,
							["vert"] = 0,
						},
						["vertAlign"] = {
							["offset"] = 0,
							["type"] = "middle",
						},
					},
				},
			},
			["pressed"] = {
				[1] = {
					["bkg"] = {
						["center_bottom"] = "0xffffffff",
						["center_center"] = "0xffffffff",
						["center_top"] = "0xffffffff",
						["file"] = "dxgui\\skins\\skinME\\images\\mission_editor\\switchbtn_ME_sel.png",
						["insets"] = {
							["bottom"] = 2,
							["left"] = 3,
							["right"] = 3,
							["top"] = 2,
						},
						["left_bottom"] = "0xffffffff",
						["left_center"] = "0xffffffff",
						["left_top"] = "0xffffffff",
						["rect"] = {
							["x1"] = 0,
							["x2"] = 0,
							["y1"] = 0,
							["y2"] = 0,
						},
						["right_bottom"] = "0xffffffff",
						["right_center"] = "0xffffffff",
						["right_top"] = "0xffffffff",
					},
					["text"] = {
						["blur"] = 0,
						["color"] = "0x88631bff",
						["font"] = "DejaVuLGCSansCondensed-Bold.ttf",
						["fontSize"] = 12,
						["horzAlign"] = {
							["offset"] = 0,
							["type"] = "middle",
						},
						["lineHeight"] = 0,
						["shadowOffset"] = {
							["horz"] = 0,
							["vert"] = 0,
						},
						["vertAlign"] = {
							["offset"] = 0,
							["type"] = "middle",
						},
					},
				},
				[2] = {
					["bkg"] = {
						["center_bottom"] = "0xffffffff",
						["center_center"] = "0xffffffff",
						["center_top"] = "0xffffffff",
						["file"] = "dxgui\\skins\\skinME\\images\\mission_editor\\switchbtn_ME_sel.png",
						["insets"] = {
							["bottom"] = 4,
							["left"] = 3,
							["right"] = 3,
							["top"] = 7,
						},
						["left_bottom"] = "0xffffffff",
						["left_center"] = "0xffffffff",
						["left_top"] = "0xffffffff",
						["rect"] = {
							["x1"] = 0,
							["x2"] = 0,
							["y1"] = 0,
							["y2"] = 0,
						},
						["right_bottom"] = "0xffffffff",
						["right_center"] = "0xffffffff",
						["right_top"] = "0xffffffff",
					},
					["text"] = {
						["blur"] = 0,
						["color"] = "0xf7b940ff",
						["font"] = "DejaVuLGCSansCondensed-Bold.ttf",
						["fontSize"] = 12,
						["horzAlign"] = {
							["offset"] = 0,
							["type"] = "middle",
						},
						["lineHeight"] = 0,
						["shadowOffset"] = {
							["horz"] = 0,
							["vert"] = 0,
						},
						["vertAlign"] = {
							["offset"] = 0,
							["type"] = "middle",
						},
					},
				},
			},
			["released"] = {
				[1] = {
					["bkg"] = {
						["center_bottom"] = "0xffffffff",
						["center_center"] = "0xffffffff",
						["center_top"] = "0xffffffff",
						["file"] = "dxgui\\skins\\skinME\\images\\manager_modules\\btn page_moduls_unselected.png",
						["insets"] = {
							["bottom"] = 0,
							["left"] = 0,
							["right"] = 0,
							["top"] = 0,
						},
						["left_bottom"] = "0xffffffff",
						["left_center"] = "0xffffffff",
						["left_top"] = "0xffffffff",
						["rect"] = {
							["x1"] = 0,
							["x2"] = 0,
							["y1"] = 0,
							["y2"] = 0,
						},
						["right_bottom"] = "0xffffffff",
						["right_center"] = "0xffffffff",
						["right_top"] = "0xffffffff",
					},
					["text"] = {
						["bkgColor"] = "0x00000000",
						["blur"] = 0,
						["blurColor"] = "0x00000000",
						["color"] = "0xe0dedaff",
						["font"] = "DejaVuLGCSans-Bold.ttf",
						["fontSize"] = 16,
						["horzAlign"] = {
							["offset"] = 20,
							["type"] = "min",
						},
						["lineHeight"] = 0,
						["lineThroughColor"] = "0x00000000",
						["lineThroughHeight"] = 1,
						["shadowColor"] = "0x00000000",
						["shadowOffset"] = {
							["horz"] = 0,
							["vert"] = 0,
						},
						["vertAlign"] = {
							["offset"] = 4,
							["type"] = "middle",
						},
					},
				},
				[2] = {
					["bkg"] = {
						["center_bottom"] = "0xffffffff",
						["center_center"] = "0xffffffff",
						["center_top"] = "0xffffffff",
						["file"] = "dxgui\\skins\\skinME\\images\\manager_modules\\btn page_moduls_pressed.png",
						["insets"] = {
							["bottom"] = 0,
							["left"] = 0,
							["right"] = 0,
							["top"] = 0,
						},
						["left_bottom"] = "0xffffffff",
						["left_center"] = "0xffffffff",
						["left_top"] = "0xffffffff",
						["rect"] = {
							["x1"] = 0,
							["x2"] = 0,
							["y1"] = 0,
							["y2"] = 0,
						},
						["right_bottom"] = "0xffffffff",
						["right_center"] = "0xffffffff",
						["right_top"] = "0xffffffff",
					},
					["text"] = {
						["bkgColor"] = "0x00000000",
						["blur"] = 0,
						["blurColor"] = "0x00000000",
						["color"] = "0xfbb941ff",
						["font"] = "DejaVuLGCSans-Bold.ttf",
						["fontSize"] = 16,
						["horzAlign"] = {
							["offset"] = 20,
							["type"] = "min",
						},
						["lineHeight"] = 0,
						["lineThroughColor"] = "0x00000000",
						["lineThroughHeight"] = 1,
						["shadowColor"] = "0x00000000",
						["shadowOffset"] = {
							["horz"] = 0,
							["vert"] = 0,
						},
						["vertAlign"] = {
							["offset"] = 0,
							["type"] = "middle",
						},
					},
				},
			},
		},
		["type"] = "TabGroupItem",
	},
	["version"] = 1,
}

return skin