local skin = {
	["skinData"] = {
		["params"] = {
			["insets"] = {
				["left"] = 10,
				["right"] = 10,
			},
			["maxSize"] = {
				["vert"] = 0,
			},
		},
		["states"] = {
			["disabled"] = {
				[1] = {
					["bkg"] = {
						["center_bottom"] = "0xffffff80",
						["center_center"] = "0xffffff80",
						["center_top"] = "0xffffff80",
						["file"] = "dxgui\\skins\\skinme\\images\\m1\\buttons\\btnmini\\btnbig2.png",
						["insets"] = {
							["bottom"] = 3,
							["left"] = 3,
							["right"] = 3,
							["top"] = 3,
						},
						["left_bottom"] = "0xffffff80",
						["left_center"] = "0xffffff80",
						["left_top"] = "0xffffff80",
						["right_bottom"] = "0xffffff80",
						["right_center"] = "0xffffff80",
						["right_top"] = "0xffffff80",
					},
					["picture"] = {
						["tileHorizontally"] = false,
						["tileVertically"] = false,
					},
					["text"] = {
						["bkgColor"] = "0x00000000",
						["blur"] = 0,
						["blurColor"] = "0x00000000",
						["color"] = "0xffffff80",
						["font"] = "DejaVuLGCSansCondensed-Bold.ttf",
						["fontSize"] = 12,
						["horzAlign"] = {
							["offset"] = 0,
							["type"] = "middle",
						},
						["lineHeight"] = 0,
						["lineThroughColor"] = "0x00000000",
						["lineThroughHeight"] = 1,
						["lineThroughOffset"] = 1,
						["shadowColor"] = "0x00000000",
						["shadowOffset"] = {
							["horz"] = 0,
							["vert"] = 0,
						},
						["vertAlign"] = {
							["offset"] = 0,
							["type"] = "middle",
						},
					},
				},
				[2] = {
					["bkg"] = {
						["center_bottom"] = "0xffffff80",
						["center_center"] = "0xffffff80",
						["center_top"] = "0xffffff80",
						["file"] = "dxgui\\skins\\skinme\\images\\m1\\buttons\\btnmini\\btnbig2select.png",
						["insets"] = {
							["bottom"] = 3,
							["left"] = 3,
							["right"] = 3,
							["top"] = 3,
						},
						["left_bottom"] = "0xffffff80",
						["left_center"] = "0xffffff80",
						["left_top"] = "0xffffff80",
						["right_bottom"] = "0xffffff80",
						["right_center"] = "0xffffff80",
						["right_top"] = "0xffffff80",
					},
					["picture"] = {
						["color"] = "0xffffff80",
						["file"] = "dxgui\\skins\\skinme\\images\\m1\\buttons\\btnmini\\btnbig2select.png",
						["horzAlign"] = {
							["offset"] = 0,
							["type"] = "middle",
						},
						["resizeToFill"] = false,
						["size"] = {
							["horz"] = 0,
							["vert"] = 0,
						},
						["tileHorizontally"] = false,
						["tileVertically"] = false,
						["userTexSampler"] = 0,
						["vertAlign"] = {
							["offset"] = 0,
							["type"] = "middle",
						},
					},
					["text"] = {
						["bkgColor"] = "0x00000000",
						["blur"] = 0,
						["blurColor"] = "0x00000000",
						["color"] = "0x6ed8f380",
						["font"] = "DejaVuLGCSansCondensed-Bold.ttf",
						["fontSize"] = 12,
						["horzAlign"] = {
							["offset"] = 0,
							["type"] = "middle",
						},
						["lineHeight"] = 0,
						["lineThroughColor"] = "0x00000000",
						["lineThroughHeight"] = 1,
						["lineThroughOffset"] = 1,
						["shadowColor"] = "0x00000000",
						["shadowOffset"] = {
							["horz"] = 0,
							["vert"] = 0,
						},
						["vertAlign"] = {
							["offset"] = 0,
							["type"] = "middle",
						},
					},
				},
			},
			["hover"] = {
				[1] = {
					["bkg"] = {
						["center_bottom"] = "0xffffffff",
						["center_center"] = "0xffffffff",
						["center_top"] = "0xffffffff",
						["file"] = "dxgui\\skins\\skinme\\images\\m1\\buttons\\btnmini\\btnbig2.png",
						["insets"] = {
							["bottom"] = 3,
							["left"] = 3,
							["right"] = 3,
							["top"] = 3,
						},
						["left_bottom"] = "0xffffffff",
						["left_center"] = "0xffffffff",
						["left_top"] = "0xffffffff",
						["right_bottom"] = "0xffffffff",
						["right_center"] = "0xffffffff",
						["right_top"] = "0xffffffff",
					},
					["picture"] = {
						["tileHorizontally"] = false,
						["tileVertically"] = false,
					},
					["text"] = {
						["bkgColor"] = "0x00000000",
						["blur"] = 0,
						["blurColor"] = "0x00000000",
						["color"] = "0xffffffff",
						["font"] = "DejaVuLGCSansCondensed-Bold.ttf",
						["fontSize"] = 12,
						["horzAlign"] = {
							["offset"] = 0,
							["type"] = "middle",
						},
						["lineHeight"] = 0,
						["lineThroughColor"] = "0x00000000",
						["lineThroughHeight"] = 1,
						["lineThroughOffset"] = 1,
						["shadowColor"] = "0x00000000",
						["shadowOffset"] = {
							["horz"] = 0,
							["vert"] = 0,
						},
						["vertAlign"] = {
							["offset"] = 0,
							["type"] = "middle",
						},
					},
				},
				[2] = {
					["bkg"] = {
						["center_bottom"] = "0xffffffff",
						["center_center"] = "0xffffffff",
						["center_top"] = "0xffffffff",
						["file"] = "dxgui\\skins\\skinme\\images\\m1\\buttons\\btnmini\\btnbig2select.png",
						["insets"] = {
							["bottom"] = 3,
							["left"] = 3,
							["right"] = 3,
							["top"] = 3,
						},
						["left_bottom"] = "0xffffffff",
						["left_center"] = "0xffffffff",
						["left_top"] = "0xffffffff",
						["right_bottom"] = "0xffffffff",
						["right_center"] = "0xffffffff",
						["right_top"] = "0xffffffff",
					},
					["picture"] = {
						["tileHorizontally"] = false,
						["tileVertically"] = false,
					},
					["text"] = {
						["bkgColor"] = "0x00000000",
						["blur"] = 0,
						["blurColor"] = "0x00000000",
						["color"] = "0x6ed8f3ff",
						["font"] = "DejaVuLGCSansCondensed-Bold.ttf",
						["fontSize"] = 12,
						["horzAlign"] = {
							["offset"] = 0,
							["type"] = "middle",
						},
						["lineHeight"] = 0,
						["lineThroughColor"] = "0x00000000",
						["lineThroughHeight"] = 1,
						["lineThroughOffset"] = 1,
						["shadowColor"] = "0x00000000",
						["shadowOffset"] = {
							["horz"] = 0,
							["vert"] = 0,
						},
						["vertAlign"] = {
							["offset"] = 0,
							["type"] = "middle",
						},
					},
				},
			},
			["pressed"] = {
				[1] = {
					["bkg"] = {
						["center_bottom"] = "0xffffffff",
						["center_center"] = "0xffffffff",
						["center_top"] = "0xffffffff",
						["file"] = "dxgui\\skins\\skinme\\images\\m1\\buttons\\btnmini\\btnbig2.png",
						["insets"] = {
							["bottom"] = 3,
							["left"] = 3,
							["right"] = 3,
							["top"] = 3,
						},
						["left_bottom"] = "0xffffffff",
						["left_center"] = "0xffffffff",
						["left_top"] = "0xffffffff",
						["right_bottom"] = "0xffffffff",
						["right_center"] = "0xffffffff",
						["right_top"] = "0xffffffff",
					},
					["picture"] = {
						["tileHorizontally"] = false,
						["tileVertically"] = false,
					},
					["text"] = {
						["bkgColor"] = "0x00000000",
						["blur"] = 0,
						["blurColor"] = "0x00000000",
						["color"] = "0xffffff80",
						["font"] = "DejaVuLGCSansCondensed-Bold.ttf",
						["fontSize"] = 12,
						["horzAlign"] = {
							["offset"] = 0,
							["type"] = "middle",
						},
						["lineHeight"] = 0,
						["lineThroughColor"] = "0x00000000",
						["lineThroughHeight"] = 1,
						["lineThroughOffset"] = 1,
						["shadowColor"] = "0x00000000",
						["shadowOffset"] = {
							["horz"] = 0,
							["vert"] = 0,
						},
						["vertAlign"] = {
							["offset"] = 0,
							["type"] = "middle",
						},
					},
				},
				[2] = {
					["bkg"] = {
						["center_bottom"] = "0xffffffff",
						["center_center"] = "0xffffffff",
						["center_top"] = "0xffffffff",
						["file"] = "dxgui\\skins\\skinme\\images\\m1\\buttons\\btnmini\\btnbig2select.png",
						["insets"] = {
							["bottom"] = 3,
							["left"] = 3,
							["right"] = 3,
							["top"] = 3,
						},
						["left_bottom"] = "0xffffffff",
						["left_center"] = "0xffffffff",
						["left_top"] = "0xffffffff",
						["right_bottom"] = "0xffffffff",
						["right_center"] = "0xffffffff",
						["right_top"] = "0xffffffff",
					},
					["picture"] = {
						["tileHorizontally"] = false,
						["tileVertically"] = false,
					},
					["text"] = {
						["bkgColor"] = "0x00000000",
						["blur"] = 0,
						["blurColor"] = "0x00000000",
						["color"] = "0x6ed8f380",
						["font"] = "DejaVuLGCSansCondensed-Bold.ttf",
						["fontSize"] = 12,
						["horzAlign"] = {
							["offset"] = 0,
							["type"] = "middle",
						},
						["lineHeight"] = 0,
						["lineThroughColor"] = "0x00000000",
						["lineThroughHeight"] = 1,
						["lineThroughOffset"] = 1,
						["shadowColor"] = "0x00000000",
						["shadowOffset"] = {
							["horz"] = 0,
							["vert"] = 0,
						},
						["vertAlign"] = {
							["offset"] = 0,
							["type"] = "middle",
						},
					},
				},
			},
			["released"] = {
				[1] = {
					["bkg"] = {
						["center_bottom"] = "0xffffffff",
						["center_center"] = "0xffffffff",
						["center_top"] = "0xffffffff",
						["file"] = "dxgui\\skins\\skinme\\images\\m1\\buttons\\btnmini\\btnbig2.png",
						["insets"] = {
							["bottom"] = 3,
							["left"] = 3,
							["right"] = 3,
							["top"] = 3,
						},
						["left_bottom"] = "0xffffffff",
						["left_center"] = "0xffffffff",
						["left_top"] = "0xffffffff",
						["right_bottom"] = "0xffffffff",
						["right_center"] = "0xffffffff",
						["right_top"] = "0xffffffff",
					},
					["picture"] = {
						["horzAlign"] = {
							["type"] = "middle",
						},
						["vertAlign"] = {
							["type"] = "middle",
						},
					},
					["text"] = {
						["blur"] = 0,
						["color"] = "0xffffffcc",
						["font"] = "DejaVuLGCSansCondensed-Bold.ttf",
						["fontSize"] = 12,
						["horzAlign"] = {
							["type"] = "middle",
						},
						["shadowOffset"] = {
							["horz"] = 0,
							["vert"] = 0,
						},
						["vertAlign"] = {
							["type"] = "middle",
						},
					},
				},
				[2] = {
					["bkg"] = {
						["center_bottom"] = "0xffffffff",
						["center_center"] = "0xffffffff",
						["center_top"] = "0xffffffff",
						["file"] = "dxgui\\skins\\skinme\\images\\m1\\buttons\\btnmini\\btnbig2select.png",
						["insets"] = {
							["bottom"] = 3,
							["left"] = 3,
							["right"] = 3,
							["top"] = 3,
						},
						["left_bottom"] = "0xffffffff",
						["left_center"] = "0xffffffff",
						["left_top"] = "0xffffffff",
						["right_bottom"] = "0xffffffff",
						["right_center"] = "0xffffffff",
						["right_top"] = "0xffffffff",
					},
					["picture"] = {
						["tileHorizontally"] = false,
						["tileVertically"] = false,
					},
					["text"] = {
						["blur"] = 0,
						["color"] = "0x6ed8f3cc",
						["font"] = "DejaVuLGCSansCondensed-Bold.ttf",
						["fontSize"] = 12,
						["horzAlign"] = {
							["type"] = "middle",
						},
						["shadowOffset"] = {
							["horz"] = 0,
							["vert"] = 0,
						},
						["vertAlign"] = {
							["type"] = "middle",
						},
					},
				},
			},
		},
		["type"] = "ToggleButton",
	},
	["version"] = 1,
}

return skin